### ISSUE TITLE
Validation schema apis return 404 for mpOpenApi-3.0

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/open-liberty#20262] opened 2022-02-24 20:16 UTC
/openapi/platform/validation/ returns 404

**Steps to Reproduce**  
1. Enabled validation using just these features
`<feature>adminCenter-1.0</feature>`
`<feature>jdbc-4.2</feature>`
`<feature>mpOpenApi-3.0</feature>  `
2. API returns 404:
scheme
	https
host
	localhost:9443
filename
	/openapi/platform/validation/
Address
	127.0.0.1:9443
Status
404
Not Found

**Expected behavior**  
It was expected that the validation apis would work for mpOpenApi-3.0

Log info
`I SRVE0242I: [io.openliberty.microprofile.openapi.2.0.internal.jakarta] [/openapi] [ApplicationServlet]: Initialization successful.
[2/24/22, 14:13:09:103 CST] 0000002e com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [adminCenter-1.0, cdi-3.0, concurrent-2.0, distributedMap-1.0, expressionLanguage-4.0, jdbc-4.2, jndi-1.0, json-1.0, jsonp-2.0, mpConfig-3.0, mpOpenAPI-3.0, pages-3.0, restConnector-2.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0].`

**Comment by Azquelt** [comment] 2022-02-25 14:39
I wasn't able to reproduce this after testing 
* my development environment
* the 22.0.0.2 openliberty kernel package after running `featureUtility installServerFeatures`
* the 22.0.0.2 openliberty "All GA features" package

In all cases, `https://localhost:9443/openapi/platform/validation/` loaded correctly and showed the openapi schema.

Was there a particular runtime package or version you used in your testing?

Do you see either of the following lines in your log?
```
A CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/platform/
I SRVE0242I: [io.openliberty.rest.handler.config.openapi.common.jakarta] [/openapi/platform] [ConfigValidationSchemaRESTProxy]: Initialization successful.
```

This was the server.xml I used:
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

        <!-- Enable features -->
        <featureManager>
                <feature>adminCenter-1.0</feature>
                <feature>jdbc-4.2</feature>
                <feature>mpOpenApi-3.0</feature>
        </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />

    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <quickStartSecurity userName="test" userPassword="test"/>

    <!-- Default SSL configuration enables trust for default certificates from the Java runtime --> 
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
</server>
```

**Comment by Azquelt** [comment] 2022-03-21 11:40
@k8vance88 Are you still seeing this problem? Can you provide more information to help me reproduce it?

**Comment by Azquelt** [comment] 2022-09-21 10:00
Given there's been no updates on this defect and I can't reproduce it, I'm going to close it. Please re-open if you still have this issue.

**Closed as completed by Azquelt** 2022-09-21 10:00 UTC
Labels: release bug
