### ISSUE TITLE
Spring boot 2.3.4 application stops on wlp 22.0.0.7

### ISSUE THREAD

**Issue by uvglord** [OpenLiberty/open-liberty#22007] opened 2022-08-06 13:27 UTC
Hi, 

I have recently upgraded the liberty server from 21.0.0.12 to 22.0.0.7
After this my spring boot application has stopped starting.
I am getting below error on startup. Incident files attached for reference.

 :: Spring Boot ::        (v2.3.4.RELEASE)
2022-08-06 18:54:19.440  INFO 11272 --- [ecutor-thread-4] c.hsbc.ccoonboarding.ServletInitializer  : Starting ServletInitializer on LPT3802 with PID 11272 (D:\Softwares\wlp8-22.0.0.7\usr\servers\defaultServer\apps\expanded\cco-onboarding.war\WEB-INF\classes started by saurabhsingh in D:\Softwares\wlp8-22.0.0.7\usr\servers\defaultServer)
2022-08-06 18:54:19.440 DEBUG 11272 --- [ecutor-thread-4] c..ccoonboarding.ServletInitializer  : Running with Spring Boot v2.3.4.RELEASE, Spring v5.2.9.RELEASE
2022-08-06 18:54:19.440  INFO 11272 --- [ecutor-thread-4] c..ccoonboarding.ServletInitializer  : The following profiles are active: ldap,mail,common
18:54:21,640 |-INFO in ch.qos.logback.classic.servlet.LogbackServletContextListener@40d3c251 - About to stop ch.qos.logback.classic.LoggerContext [default]
[ERROR   ] SRVE0285E: Exception caught while destroying context: java.lang.NullPointerException
	at org.jboss.weld.module.web.servlet.WeldInitialListener.contextDestroyed(WeldInitialListener.java:113)
	at [internal classes]
[ffdc_22.08.06_18.54.21.1.log](https://github.com/OpenLiberty/open-liberty/files/9275110/ffdc_22.08.06_18.54.21.1.log)
[exception_summary_22.08.06_18.54.16.0.log](https://github.com/OpenLiberty/open-liberty/files/9275111/exception_summary_22.08.06_18.54.16.0.log)

[AUDIT   ] CWWKZ0012I: The application cco-onboarding was not started.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/onboarding/

**Comment by jhanders34** [comment] 2022-08-06 14:11
The exception_summary has a NoClassDefFoundError in it.  That would be a good FFDC to get to see what is happening.  The NullPointerException is fallout of stop being called by the start path where things are not fully initialized.  I believe that is a red herring and the NoClassDefFoundError will be more telling.  Seeing the entire messages.log would also be helpful.  May want to have some trace as well for this issue depending on what is happening.

**Comment by uvglord** [comment] 2022-08-08 07:43
Please find attached the messages.log file and pom.xml(attached as txt file).
Also, please note that I have another spring boot application Spring Boot v1.5.3.RELEASE, Spring v4.3.8.RELEASE
This application is running fine on both the server. I trying to lower or change the version but no luck, as there are few dependencies which not available in Spring boot 1.x.

P.S. : I have also tried excluding/including tomcat dependencies, but still the issue not resolved.

[messages_22.08.06_18.54.01.0.log](https://github.com/OpenLiberty/open-liberty/files/9279797/messages_22.08.06_18.54.01.0.log)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/9279798/messages.log)

Let me know what else I can share
[pom.txt](https://github.com/OpenLiberty/open-liberty/files/9279823/pom.txt)

**Comment by jhanders34** [comment] 2022-08-08 12:36
With the entire messages.log, I see the following message in the log:

[6/8/22 18:54:21:631 IST] 0000002b com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration due to javax/cache/Caching not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake) com.ibm.ws.webcontainer.osgi.DynamicVirtualHost startWebApp" at ffdc_22.08.06_18.54.21.0.log

That log statement does tie into something that changed earlier this year where JCache APIs used to be exposed and were erroneously no longer exposed.  In 22.0.0.8, @jvanhill worked with PR #21263 and #21543 to resolve issue #20939.

If running with 22.0.0.8 resolves this problem and you are satisfied, let me know and I can close out this issue.

**Comment by uvglord** [comment] 2022-08-08 13:56
Just checked with WLP 22.0.0.8 and yes its working fine now without any issues. Closing this ticket for good.

Thanks for the help.

**Comment by jhanders34** [comment] 2022-08-08 14:11
Duplicate of #20939.

**Closed as not planned** 2022-08-08 17:49 UTC
Labels: Needs member attention
