### ISSUE TITLE
Faces 4.0 Beta - Could not generate LambdaPropertyDescriptor

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#24110] opened 2023-01-30 19:34 UTC
I am trying to run my application with the JakartaEE10 beta features and I am getting into following exception in the logs.

```
org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils I Could not generate LambdaPropertyDescriptor for org.j4fry.dojo.beans.DojoHelper. Use PropertyDescriptor...
java.lang.invoke.LambdaConversionException: Invalid caller: org.j4fry.dojo.beans.DojoHelper
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:125)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:175)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:336)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.createLambdaPropertyDescriptor(PropertyDescriptorUtils.java:193)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.getLambdaPropertyDescriptors(PropertyDescriptorUtils.java:226)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.getPropertyDescriptors(PropertyDescriptorUtils.java:115)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.lambda$getCachedPropertyDescriptors$0(PropertyDescriptorUtils.java:90)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.getCachedPropertyDescriptors(PropertyDescriptorUtils.java:90)
	at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getPropertyDescriptor(LambdaBeanELResolver.java:152)
	at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:72)
	at jakarta.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:100)
	at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:433)
	at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:465)
	at jakarta.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:141)
	at org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.createComponent(ComponentTagHandlerDelegate.java:531)
	at org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:275)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:52)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:57)
	at org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:362)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:52)
	at org.apache.myfaces.view.facelets.tag.faces.core.ViewHandler.apply(ViewHandler.java:195)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at org.apache.myfaces.view.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:67)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at org.apache.myfaces.view.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:49)
	at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:523)
	at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:579)
	at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:556)
	at org.apache.myfaces.view.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:216)
	at org.apache.myfaces.view.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:138)
	at org.apache.myfaces.view.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:67)
	at org.apache.myfaces.view.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:49)
	at org.apache.myfaces.view.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:195)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.buildView(FaceletViewDeclarationLanguage.java:423)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:83)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:241)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:225)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1004)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5078)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:316)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1246)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:567)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:501)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:361)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:328)
	at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1789)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jagraj** [comment] 2023-01-31 17:24
I moved to latest daily build and this issue seems to be open and not fixed.

```
1/31/23, 12:15:17:778 EST] 0000004c .apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils I Could not generate LambdaPropertyDescriptor for com.ibm.websphere.svt.gs.gsdb.jaxws.client.MfgCategoryWrapper. Use PropertyDescriptor...
java.lang.invoke.LambdaConversionException: Invalid caller: com.ibm.websphere.svt.gs.gsdb.jaxws.client.MfgCategoryWrapper
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:125)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:175)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:336)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.createLambdaPropertyDescriptor(PropertyDescriptorUtils.java:196)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.getLambdaPropertyDescriptors(PropertyDescriptorUtils.java:229)
	at org.apache.myfaces.core.api.shared.lang.PropertyDescriptorUtils.getPropertyDescriptors(PropertyDescriptorUtils.java:115)
```

**Comment by volosied** [comment] 2023-02-03 03:01
Ah, you're right. 

The property which enabled the lambda bean resolver was changed here: https://issues.apache.org/jira/browse/MYFACES-4548 

It has not been ported to Liberty just yet, but should be with my RC4 PR: #24114

**Comment by volosied** [comment] 2023-02-13 22:56
There error is thrown here: https://github.com/apache/myfaces/blob/myfaces-core-module-4.0.0-RC2/api/src/main/java/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorUtils.java#L193-L198

Something with the look up went wrong.  The JavaDoc can be found here:

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/LambdaMetafactory.html#metafactory(java.lang.invoke.MethodHandles.Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.invoke.MethodType,java.lang.invoke.MethodHandle,java.lang.invoke.MethodType)

Thomas, the individual who implemented this code, mentioned it can be fixable in some cases via the user: 
https://issues.apache.org/jira/browse/MYFACES-4554?focusedCommentId=17681586&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17681586

I'll need more information to figure out what went wrong, but  there is a fallback for when the lambas fail. The app should work fine.

With RC4, the context parameter, _org.apache.myfaces.USE_LAMBDA_METAFACTORY_, has been disabled, so this error shouldn't be seen unless this property is enabled. 

______

Code for the dojoHelper:

` <h:panelGroup id="messages" binding="#{dojoHelper.binding['messages']}"> `


	public Map<String, UIComponent> getBinding() {
		return binding;
	}

**Comment by volosied** [comment] 2023-02-14 16:37
JDK code:
```
    AbstractValidatingLambdaMetafactory(MethodHandles.Lookup caller,
                                       MethodType invokedType,
                                       String samMethodName,
                                       MethodType samMethodType,
                                       MethodHandle implMethod,
                                       MethodType instantiatedMethodType,
                                       boolean isSerializable,
                                       Class<?>[] markerInterfaces,
                                       MethodType[] additionalBridges)
            throws LambdaConversionException {
        if ((caller.lookupModes() & MethodHandles.Lookup.PRIVATE) == 0) {
            throw new LambdaConversionException(String.format(
                    "Invalid caller: %s",
                    caller.lookupClass().getName()));
        }
```

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#lookupModes()

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#PRIVATE 

Looks like some sort of permissions / access issue? 

I'm not able to reproduce this problem myself (and it's sort of resolved via the property change), so I will close it.

**Comment by jagraj** [comment] 2023-02-14 16:40
@volosied - This issue has been resolved in latest daily build. Thanks for the fix.

**Comment by pnicolucci** [comment] 2023-02-14 18:52
Closing!

**Closed as completed by pnicolucci** 2023-02-14 18:52 UTC
Labels: bug, in:Web Components, team:Sirius, jakartaEE10, SVT
