### ISSUE TITLE
Occasional ArrayIndexOutOfBoundsException in JaspiServiceImpl.getDescription during Arquillian Tests

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#11504] opened 2020-03-27 07:59 UTC
**Describe the bug**
During Arquillian Tests on our Jenkins Platform we see occasional Exceptions. 
It is always a other Testcase so it could not be the Test itself.

In the Jenkins Log we see following Log
`Error launching test at http://localhost:9009/arquillian-managed/ArquillianServletRunner?outputMode=serializedObject&className=at.gv.tirol.dda.arquillian.dvtadministration.service.submitsendung.SubmitSendungZustelltypSuccessIT&methodName=testElektronischNonRsSuccess. Got 500 (Internal Server Error)`

Entries in the messages.log File

`[INFORMATION] SRVE0242I: [arquillian-managed] [/arquillian-managed] [ArquillianServletRunner]: Initialisierung erfolgreich.
[INFORMATION] FFDC1015I: Es wurde ein FFDC-Vorfall erstellt: "java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0 com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters 1105" unter ffdc_20.03.26_21.01.00.0.log
[FEHLER  ] SRVE0315E: Es ist eine Ausnahme eingetreten: java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5079)
	at [internal classes]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at com.ibm.ws.security.jaspi.JaspiServiceImpl.getDescription(JaspiServiceImpl.java:614)
	... 1 more
`

This is the ffdc-File 
[ffdc_20.03.26_21.01.00.0.log](https://github.com/OpenLiberty/open-liberty/files/4392162/ffdc_20.03.26_21.01.00.0.log)

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.3
 - Java Version: Eclipse OpenJ9 VM, Version 11.0.5+10 (de_AT)

**Additional context**

**Comment by arkarkala** [comment] 2020-03-28 03:09
To confirm, different test cases are failing at different times with same error - intermittently ?
Looks like the AuthConfigFactory is not returning any AuthConfigurationProvider registrations here causing the issue.
Any pointers that can help to recreate this locally?

**Comment by c-koell** [comment] 2020-03-30 06:11
Yes thats right. 
Unfortunately we are not able to create any local testcase nor give any pointers to recreate it locally ...

Is it maybe a race condition or fixable with synchronisation ?

**Comment by teddyjtorres** [comment] 2020-03-30 14:29
At this particular code location, the provider is missing the registration ID. It will need to be determined why the required registration ID is missing intermittently.

**Comment by teddyjtorres** [comment] 2020-04-02 21:04
Please indicate what features are enabled, if a custom AuthConfigFactory was set using -Dauthconfigprovider.factory, and if a JASPIC provider was configured via a user feature.  Thanks.

**Comment by c-koell** [comment] 2020-04-03 05:46
Following features are enabled.

```
<feature>webProfile-8.0</feature>
<feature>jaxws-2.2</feature>
<feature>mpConfig-1.3</feature>
<feature>javaMail-1.6</feature>
<feature>localConnector-1.0</feature>
<feature>mpJwt-1.1</feature>
```

In our Application we have implemented a HttpAuthenticationMechanism.

If you need more informations please tell me ..

**Comment by c-koell** [comment] 2020-04-28 09:10
Any news here ?

**Comment by teddyjtorres** [comment] 2020-04-28 14:17
We are reviewing the provider registration with the AuthConfigFactory implementation. At the moment we have not been able to reproduce the error, and there is synchronization already in the factory in registerConfigProvider and removeRegistration. One possibility we are looking into is if the AuthConfigFactory impl is changing from underneath us during your Arquillian Tests since the internal provider that handles the HttpAuthenticationMechanism was just obtained before the attempt to get its registration id and this provider is never deregistered.

If it is possible to enable traces, please enable traces for com.ibm.ws.security.jaspi.*=all. This will help determine if the right factory is still being called and how the registration and removal of the provider is taking place in your environment.

Regards.

**Comment by teddyjtorres** [comment] 2020-04-28 14:20
Also, if you have support for Liberty, we are more than happy to assist you if you open a case while we review the specifics of this setup. It helps when reviewing information from your environment and avoids putting that in the public.

**Comment by c-koell** [comment] 2020-04-29 10:56
At the moment i think we have no support contract. We are migrate from our WebSphere 9 environment (where we have a contract) to OpenLiberty.
Maybe we should clarify if we have a support contract if we a valid WebSphere 9 support  contract.
I will enable that trace and attach it as soon as the exception occurs.

**Comment by c-koell** [comment] 2020-05-04 12:26
I have attached the trace log running a Testcase where the ArrayIndexOutOfBoundsException has occurred.

[trace_20.05.04_14.06.54.0.log](https://github.com/OpenLiberty/open-liberty/files/4574579/trace_20.05.04_14.06.54.0.log)
[ffdc_20.05.04_14.06.39.0.log](https://github.com/OpenLiberty/open-liberty/files/4574580/ffdc_20.05.04_14.06.39.0.log)

**Comment by c-koell** [comment] 2020-05-29 05:09
Do you have found any hints within the attached logs ?

**Comment by teddyjtorres** [comment] 2020-06-02 14:56
Thank you for the traces. We will review them and provide an update with findings or next steps.

**Comment by teddyjtorres** [comment] 2020-06-02 15:59
It was determined that there is problem when registering the internal AuthConfigProvider for JSR 375. There are 2 threads registering 2 instances of the provider. Additional synchronization will be added so that a single internal provider is registered.

Thank you for providing the data that made finding the cause of the problem possible.

**Comment by c-koell** [comment] 2020-06-03 06:33
Good to hear that you have found the cause !

**Comment by c-koell** [comment] 2020-06-09 10:59
Have you created a new issue to see when it will be fixed ?

**Comment by teddyjtorres** [comment] 2020-06-11 13:35
Greetings. We will be using this same issue to fix the problem. Any pull requests will be associated with this issue.

Regards.

**Comment by c-koell** [comment] 2020-07-20 06:29
Hi again !

Any news here ?
.. thanks in advance

**Comment by teddyjtorres** [comment] 2020-07-21 20:15
Hi,

I apologize for the delay. It is being fixed in https://github.com/OpenLiberty/open-liberty/pull/13127. It will be merged once our builds complete to ensure no regressions.

Thank you.

**Comment by teddyjtorres** [comment] 2020-07-27 13:56
Closing the issue since the fix was merged.

**Closed by teddyjtorres** 2020-07-27 13:56 UTC
Labels: Needs member attention, release bug

**Comment by praveenkat1** [comment] 2021-09-22 11:46
On the similar lines, I have the same kind of error  as below described.
I am using 
(1) openliberty-20.0.0.7_01
(2) Java System Library (JavaSE-1.8)


Description:
[ERROR   ] CNTR0020E: EJB threw an unexpected (non-declared) exception during invocation of method "fetchMyBagDocumentCount" on bean "BeanId(xx-yyy-web#xx-yyy-web-0.0.1.war#MsdeWsClientBo, null)". Exception data: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61
	at com.ibm.ws.common.internal.encoder.Base64Coder.base64Decode(Base64Coder.java:139)
	at [internal classes]
	at com.xxxcom.lessy.business.bo.EJSLocalNSLEdmsWsClientBo_b54ef372.fetchMyBagDocumentCount(EJSLocalNSLMsdeWsClientBo_b54ef372.java)
	at com.xxxcom.lessy.business.bo.MyBagsBo.getStandaloneMyBags(MyBagsBo.java:623)
	at com.xxxcom.lessy.business.bo.MyBagsBo.getMyBagsList(MyBagsBo.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ejs.container.EJSContainer.invokeProceed(EJSContainer.java:4886)
	at [internal classes]
	at com.xxxcom.lessy.business.bo.EJSLocalNSLMyBagsBo_1b2581f8.getMyBagsList(EJSLocalNSLMyBagsBo_1b2581f8.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
	at [internal classes]
	at com.xxxcom.lessy.business.bo.MyBagsBo$Proxy$_$$_Weld$EnterpriseProxy$.getMyBagsList(Unknown Source)
	at com.xxxcom.lessy.web.rest.service.v1.BagsService.getBags(MyBagsService.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ejs.container.EJSContainer.invokeProceed(EJSContainer.java:4886)
	at [internal classes]
	at com.swissre.ctc.web.rest.service.v1.EJSLocalNSLMyBagsService_06a90b16.getMyBags(EJSLocalNSLMyBagsService_06a90b16.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.ejb.JaxRsFactoryBeanEJBCustomizer.serviceInvoke(JaxRsFactoryBeanEJBCustomizer.java:335)
	at [internal classes]
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:105)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at [internal classes]

[INFO    ] FFDC1015I: An FFDC Incident has been created: "java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61 com.ibm.ejs.container.BusinessExceptionMappingStrategy.setUncheckedException 506" at ffdc_21.09.22_16.25.29.0.log
[INFO    ] FFDC1015I: An FFDC Incident has been created: "com.ibm.websphere.csi.CSITransactionRolledbackException com.ibm.ejs.container.EJSContainer.postInvoke 2326" at ffdc_21.09.22_16.25.29.1.log
[ERROR   ] nested exception is: javax.ejb.EJBException: See nested exception; nested exception is: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61
nested exception is: javax.ejb.EJBException: See nested exception; nested exception is: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61
[ERROR   ] javax.ejb.EJBTransactionRolledbackException: nested exception is: javax.ejb.EJBException: See nested exception; nested exception is: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61
javax.ejb.EJBTransactionRolledbackException: nested exception is: javax.ejb.EJBException: See nested exception; nested exception is: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -61
[ERROR   ] CNTR0020E: EJB threw an unexpected (non-declared) exception during invocation of method "getMyBagsList" on bean "BeanId(sr-xxx-web#sr-xxx-web-0.0.1.
