### ISSUE TITLE
Library dependencies

### ISSUE THREAD

**Issue by tschurins** [OpenLiberty/open-liberty#9684] opened 2019-11-07 11:24 UTC
## Problem
I need a way to define a library that would references/extends another library.  

I'm developing a datasource driver and this driver has an API that would be used by the application. So I've put this API in a separated jar. 
When defining the datasource in the server.xml, I'm referencing the library containing the driver code, including the public API:
```xml
<dataSource id="ds" jndiName="jdbc/ds" type="javax.sql.XADataSource">
    <jdbcDriver libraryRef="driverLibrary"
                javax.sql.DataSource="com.acme.MyXADataSource"/>
    <properties URL="${database.url}"
                user="${database.user}" password="${database.password}"/>
</dataSource>
```
When defining the application in the server.xml, I'm referencing the library conatining the driver public API:
```xml
<enterpriseApplication id="demo-ear" location="demo-ear.ear">
    <classloader commonLibraryRef="driverPublicAPI"/>
</enterpriseApplication>
```
The libraries are defined like this:
```xml
<library id="driverPublicAPI">
    <fileset dir="/driver/" includes="driver-public-api.jar"/>
</library>
<library id="driverLibrary">
    <fileset dir="/driver/" includes="driver.jar driver-public-api.jar"/>
</library>
```
Of course this is not working because the driver-public-api.jar is loaded in 2 different class-loaders.
The only solution is to make the application depends on the full driver code, including the internal jars, which is not ideal because of classpath clashes (same referenced jar with different versions &c.)

## Dreamed solution
It would be nice if it was possible to define that a library extends another one:
```xml
<library id="driverPublicAPI">
    <fileset dir="/driver/" includes="driver-public-api.jar"/>
</library>
<library id="driverLibrary">
    <fileset dir="/driver/" includes="driver.jar"/>
    <libraryRef id="driverPublicAPI"/>
</library>
```

## Alternatives
I have also played with defining a fileset and using that fileset in the library definition via the filesetRef attribute. But this does not change the fact that the libraries from the common fileset are loaded in 2 different classpaths.

**Comment by andymc12** [comment] 2019-11-11 22:20
Hi @tschurins - thanks for opening this issue.  I have seen similar issues in the past.  IIUC, the problem is that at least one `library` element is used by both the user application _and_ the JDBC driver - both with different classloaders.  So then when the application attempts to cast a class from the JDBC framework into an interface loaded by the app's classloader, a ClassCastException is thrown.  Is that the general problem?

If so, I don't think splitting the interface and implementation into separate-but-includeable library elements will solve the problem.  The JDBC framework in Liberty would still continue to load the interfaces and implementation classes using it's own classloader - and then the cast to the interface in the user application will still fail because it still uses a different classloader.

I think there is some value in the separate-but-includeable, but it would essentially be a way of merging the files, folders, and filesets of one library into another.  The relationship between the library and the classloader is controlled by the classloader configuration, not the other way around.

Another alternative might be to more easily expose classes in a library to the entire runtime (JDBC framework as well as user applications).  This should be possible today using a user feature (more info here: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_feat_example.html ) - basically you would put the API portion of your code in a user feature and expose it's packages as an API.  Then it is loaded by the same loader for both the app and the JDBC framework.

Maybe we could make that a little easier - perhaps some kind of new configuration that essentially treats classes in a library element as if they were an API bundle that shipped with Liberty.  I'm just thinking out load here, but maybe something like:
```xml
<library id="driverPublicAPI">
    <fileset dir="/driver/" includes="driver-public-api.jar"/>
</library>
<library id="driverLibrary">
    <fileset dir="/driver/" includes="driver.jar"/>
</library>

<!-- new element platformExtension exposes all packages in that library as a stable API -->
<platformExtension libraryRef="driverPublicAPI" apiType="stable" />

<dataSource id="ds" jndiName="jdbc/ds" type="javax.sql.XADataSource">
    <!-- references the driverLibrary - but the classloader that loads classes in that library is a child loader of the classloader that loads the platformExtension libraries, so it has access to the driver-public-api.jar classes -->
    <jdbcDriver libraryRef="driverLibrary"
                javax.sql.DataSource="com.acme.MyXADataSource"/>
    <properties URL="${database.url}"
                user="${database.user}" password="${database.password}"/>
</dataSource>

<!-- no need to reference the driverPublicAPI since it is now a stable API via the platformExtension -->
<enterpriseApplication id="demo-ear" location="demo-ear.ear" />
```

I am making several assumptions here that I would need to nail down before proceeding, but wanted to let you know that I'm looking into this... Can you confirm that I understand the problem correctly (ClassCastExceptions due to different classloaders for the various classes/interfaces)?  If you have some free cycles, it might also help if you could try packaging the driver-public-api.jar in a user feature and seeing if that solves the problem.  If so, that might make it easier for me to convince my peers that an easier solution like the one I sketched out above should be prioritized.

Thanks again, Andy

**Comment by tschurins** [comment] 2019-11-12 13:25
Hello @andymc12 
Yes, you understand the problem correctly. While we don't have any ClassCastException, it is the same: we have the classes of the API which are loaded twice in the classloader of the driver and the classloader of the application. Without going to much in the details, the goal of the API is to allow the application to set some parameters that the driver will read before returning a connection. This is what Oracle recommends when using Oracle Sharding - see for example https://blogs.oracle.com/dev2dev/oracle-sharding-with-ucp-spring-hibernate-mybatis .

I'll try to create a user feature - thanks for the tip!

**Comment by tschurins** [comment] 2019-11-12 14:54
I was able to use the user feature as you proposed. It solves the problem.
But it is true that it is a bit cumbersome to deploy the API as a feature.

**Comment by andymc12** [comment] 2019-11-12 15:09
Excellent!  I'm glad it worked.  I'll continue to pursue an easier solution.  If you have any thoughts on how to make it easier, please let me know.  Thanks!

**Comment by NottyCode** [comment] 2021-04-06 14:34
A Liberty feature is the best solution to this. Shared libraries are really intended to provide a solution to share implementation between JDBC drivers and applications, it was never designed to provide the desired kind of visibility protection. This kind of visibility constraint isn't common inside Java SE, either through normal class loader semantics, or via JPMS. Since this is the only request we have received and since there is a solution to the requirement we are going to close this.

**Closed by NottyCode** 2021-04-06 14:34 UTC
Labels: Needs member attention, design-issue, enhancement
