### ISSUE TITLE
JspCoreException not creating ffdc in some cases

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#22363] opened 2022-09-01 15:21 UTC
**Describe the bug**  
On first failure of a compile getting JspCoreException it may not cause an ffdc in some cases.

com.ibm.ws.jsp.JspCoreException: /xxx.jsp(yyy,zzz) JSPG0077E:  [variable text here]
 at Line: 1 Col: 1
        at com.ibm.ws.jsp.translator.document.Jsp2Dom.getJspDocumentAsJspPage(Jsp2Dom.java:530)
        at com.ibm.ws.jsp.translator.document.Jsp2Dom.getJspDocument(Jsp2Dom.java:197)
        at com.ibm.ws.jsp.translator.JspTranslator.<init>(JspTranslator.java:76)
        at com.ibm.ws.jsp.translator.JspTranslatorFactory.createTranslator(JspTranslatorFactory.java:119)
        at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJsp(JspTranslatorUtil.java:265)
        at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJspAndCompile(JspTranslatorUtil.java:113)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:54
5)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper
.java:462)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.
java:252)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.findWrapper(AbstractJSPExtensionProcessor.java:512)
        at com.ibm.ws.jsp.webcontainerext.ws.PrepareJspHelper$PrepareJspHelperThread.handleCompile(PrepareJspHelper.java:491)
        at com.ibm.ws.jsp.webcontainerext.ws.PrepareJspHelper$PrepareJspHelperThread.run(PrepareJspHelper.java:458)
        at java.lang.Thread.run(Thread.java:822)

**Steps to Reproduce**  
Attempt to compile a JSP file with syntax error that prevents compile, i.e. the JSP file contains \<%="hello"\>.  The missing % before the \> is a syntax error causing JspCoreException.

**Expected behavior**  
This exception should have normal ffdc handling, which it does not currently.

**Diagnostic information:**  
 - OpenLiberty Version: all
 - Affected feature(s) jsp-2.2, jsp-2.3
 - Java Version: any

**Additional context**  
none.

**Comment by volosied** [comment] 2022-09-07 21:07
I think the FFDC is not generated due to this catch block:

https://github.com/OpenLiberty/open-liberty/blob/37f32580fa965edb464370a30014dc5e46b54126/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java#L368-L387

If you look at the annotations, you'll see 
https://github.com/OpenLiberty/open-liberty/blob/37f32580fa965edb464370a30014dc5e46b54126/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java#L341-L343


I uncommented FFDCIgnore, but I didn't get any FFDC errors created? 

I think we may need to add our own FFDC code? such as 
```
  com.ibm.ws.ffdc.FFDCFilter.processException(e, "com.ibm.ws.jsp.webcontainerext.JspExtensionProcessor.getServletWrapper", "89", this);
  ```

**Comment by volosied** [comment] 2022-09-07 21:20
In the "good' FFDC case, we see enter the catch block here which generates the FFDC: 

https://github.com/OpenLiberty/open-liberty/blob/37f32580fa965edb464370a30014dc5e46b54126/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java#L179

**Comment by volosied** [comment] 2022-10-05 21:53
After discussing with our internal teams, we will close this issue without any changes. The FFDC reporting is for IBM to diagnose problems and not necessarily for application developers.   In this scenario, the FFDC is typically caused by some translations and compilation issues within the JSP which the application developers can quickly fix.

As noted in my last comment, we log an FFDC when an edit has been made to a previously compiled JSP. We will leave this behavior as it's been this way for a while.

**Closed as completed by volosied** 2022-10-05 21:53 UTC
Labels: in:Web Components, team:Sirius
