### ISSUE TITLE
Json traces should include log context 

### ISSUE THREAD

**Issue by sdehors-ibm** [OpenLiberty/open-liberty#20256] opened 2022-02-24 07:31 UTC
**Describe the use case that you want to enable:**

When a trace is printed in json, there is no context information associated unlike with logs. We'd like the log context set for normal logging to be taken into account when liberty outputs traces as well.

**Describe why this is important to you:**
The log context this is an essential feature to investigate problems from logs. For instance in micro services environment the context is used to record a correlationId of the request. Without context the request that caused the trace log cannot be 
identified.

**Additional context**
Traces go through a log record created in com.ibm.ws.logging.internal.WsLogRecord#createWsLogRecord. But it seems in that case, that the LogRecordContext is not taken into account and no extensions are logged in the trace output.

**Comment by pgunapal** [comment] 2022-02-28 16:30
Hi @sdehors-ibm, this enhancement request should already be supported in Open Liberty. Whenever, a LogRecordContext extension is registered, it should be included in the JSON logs, regardless if it's a `liberty_message` or a `liberty_trace` message, represented by JSON fields that have a prefix of `ext_`. You should see something similar to the following, where the `ext_thread` is shown:
`{"type":"liberty_trace","host":"localhost","ibm_userDir":"\/wlp\/usr\/","ibm_serverName":"json","message":"hello.  I'm chatty","ibm_threadId":"00000050","ibm_datetime":"2022-02-24T11:29:10.248-0500","module":"com.ibm.ws.lumberjack.badness.Chatty","loglevel":"FINE","ibm_sequence":"1645720150248_0000000000200","ext_thread":"Default Executor-thread-18"}`

To help diagnose the issue that you're facing, we have some questions for you:
- How did you register the LogRecordContext extension in your applications? 
- How did you configure JSON logging in your Liberty server? 
- What version of Liberty are you using? 
- You mentioned that the LogRecordContext extensions are shown in the normal Liberty logging, but not in Liberty traces, can you please elaborate on that? It would be helpful if you send examples of logs that contain the LogRecord Context extensions and the traces you would expect to see them in as well.

**Comment by pgunapal** [comment] 2022-05-02 15:34
Hi @sdehors-ibm, following up on this issue, are you still experiencing this issue? If you are, can you please answer the questions from https://github.com/OpenLiberty/open-liberty/issues/20256#issuecomment-1054436394, to help us diagnose the issue better. If the issue is resolved, please close this issue. Thank you!

**Comment by sdehors-ibm** [comment] 2022-05-05 11:46
Hello @pgunapal, 

I still observe this behaviour with 22.0.0.4.

It can be reproduced with a simple rest-endpoint:

```
  @GET
    public String about() throws Throwable {
        LogRecordContext.addExtension("test", "bob");
        logger.info("before boom");
        throw new Throwable("boom");
     }
```

In the attached log you can see the output of a call to this endpoint. The last entry with message "SRVE0777E: Exception thrown by application class ..." does not contain the ext_test field unlike the other ones.
[messages.log](https://github.com/OpenLiberty/open-liberty/files/8630876/messages.log)

Logging is configured with 
WLP_LOGGING_MESSAGE_SOURCE=message,trace,accessLog,ffdc,audit
WLP_LOGGING_MESSAGE_FORMAT=json

**Comment by pgunapal** [comment] 2022-06-17 14:15
#build

**Closed as completed** 2022-06-20 15:46 UTC
Labels: enhancement, Needs member attention, team:Lumberjack

**Comment by pgunapal** [comment] 2022-06-20 15:55
Hi @sdehors-ibm, a quick update, we were able to reproduce the issue locally on our end and was able to identify the root cause. We recently merged a [PR](https://github.com/OpenLiberty/open-liberty/pull/21465) with the potential fix, where the LogRecordContext extensions will be included in exception messages and traces as well, such as `SRVE0777E`.
