### ISSUE TITLE
Iterate on ResteasyEndpointIntrospector to work with multiple applications with same resource class 

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#19023] opened 2021-10-18 15:58 UTC
Currently the ResteasyEndpointIntrospector does not handle a case where (in dropins) there are multiple applications that both use the same resource class.  An example of this is com.ibm.ws.jaxrs.fat.helloworld.HelloWorldApplication and HelloWorldApplicaiton2.  Neither is defined in server.xml, but HelloWorldApplication is specified in the web.xml and HelloWorldApplication2 uses the @ApplicationPath annotation.

When running with the introspector enabled the endpoints are listed multiple times but only the HelloWorldApplication is identified.  The output should use the application name when identifying the endpoints and should list each application.

The description of this introspector:
Log the JAX-RS endpoints for each Application.
helloworld endpoints:
- GET /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#getMessage()
- GET /helloworld/helloworld/{uniqueid : ([0-9a-t]{8}|[0-9a-t]{11})}/{testString} - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#getMessage()
- DELETE /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#deleteMessage()
- PUT /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#putMessage()
- POST /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#postMessage()
- GET /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#getMessage()
- GET /helloworld/helloworld/{uniqueid : ([0-9a-t]{8}|[0-9a-t]{11})}/{testString} - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#getMessage()
- DELETE /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#deleteMessage()
- PUT /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#putMessage()
- POST /helloworld/helloworld - com.ibm.ws.jaxrs.fat.helloworld.HelloWorldResource#postMessage()

**Comment by WhiteCat22** [comment] 2021-11-01 14:58
dupe of https://github.com/OpenLiberty/open-liberty/issues/18581

**Closed as completed by WhiteCat22** 2021-11-01 14:58 UTC
Labels: in:JAX-RS
