### ISSUE TITLE
Extraneous messages logged when running fat jar with Open Liberty

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/open-liberty#6314] opened 2019-01-28 20:49 UTC
When running Open Liberty via a "fat jar" application (```java -jar myapp.jar```), I am seeing several additional messages getting logged -- none of which seem to affect the execution of the server.  And, to be honest, I don't find them useful.  For example, there are a few INFO messages related to "Aries Blueprint".  There are also several messages relating to the creation of session contexts and associated session managers.  Lots of "noise" in my opinion...

I am comparing this output with what I get when use the Liberty maven plugin and execute ```mvn liberty:run-server```.  This provides a much more readable and clean output.  I will attempt to attach two files to show the difference in logging between the two mechanisms...

I am running with Open Liberty 18.0.0.4 on a Mac using Java 8 (standard install on a Mac).

[plugin.txt](https://github.com/OpenLiberty/open-liberty/files/2804864/plugin.txt)
[fatjar.txt](https://github.com/OpenLiberty/open-liberty/files/2804867/fatjar.txt)

If you need to reproduce this, just clone this repo, go to dukes-liberty directory and execute maven commands to build the app and create the server:
https://github.com/kwsutter/dukes-microprofile

```
cd dukes-liberty
mvn clean install -P runnable

mvn liberty:run-server
or
cd target
java -jar dukes-liberty.jar
```

**Comment by Emily-Jiang** [comment] 2019-01-28 23:02
+1 on getting this fixed! I was surprised to see this extra log. @NottyCode thinks this might be caused by the incorrect setup of JUL.

**Comment by donbourne** [comment] 2019-01-28 23:37
Looks like it could be missing our LogManager (which is normally set up with -D parms when starting the JVM).

**Comment by pgunapal** [comment] 2019-03-01 22:11
From investigation, it looks like the SelfExtractor is calling Logger.getLogger, before the WsLogManager is set. This initializes the JUL LogManager before the WsLoggerManager is available, which causes the extra INFO messages (unformatted) to be displayed onto the console. This issue only occurs, when the server is started inline (and in-process), using a packaged Liberty jar (java -jar <jar_name>).

Had a discussion with Don and Alasdair, below are the possible options to resolve this issue:
1) Calling main is ws-server.jar is probably only something we do and I think updating SelfExtract to either not bootstrap logger (get rid of the use of Logger, in the SelfExtractor), or move wslogger into it would work fine (issue with latter is classloader visibility)

2) Bootstrapping Liberty in another JVM should work without taking over the world. So I think eliminating the need for LogManager is a good idea, but I think we should address 1 first.

**Comment by pgunapal** [comment] 2019-05-08 14:56
Merged PR, the solution was to get rid of the use of Logger in the SelfExtract package, so our WsLogManager is loaded and set properly (Option #1).

**Closed** 2019-05-09 14:41 UTC
Labels: team:Lumberjack
