### ISSUE TITLE
Custom JAX-RS ParamConverter doesn't work for collection and array types

### ISSUE THREAD

**Issue by sithmein** [OpenLiberty/open-liberty#6761] opened 2019-03-04 14:33 UTC
I was trying to create a custom `javax.ws.rs.ext.ParamConverter<List<String>>`. The idea is to convert query parameters such as "ids=i1,i2,i3" into a list of strings i1, i2, i3 in the resource class. The convert is instantiated correctly and used but the call actually fails with

> java.lang.ClassCastException: Cannot cast java.util.Arrays$ArrayList to java.lang.String

I did a bit of debugging and it seems there is some special treatment for collections and arrays in `org.apache.cxf.jaxrs.utils.InjectionUtils` which partially ignores the custom `ParamConverter`. It's called but the returned value as assume to be the type inside the collection.
Attached is a small example project to reproduce the issue:
* `mvn package`
* `java -jar com.knime.enterprise.cloud.service.repository.app/target/cloud.service.repository.app-0.0.2-SNAPSHOT.jar`
* `curl http://localhost:9080/repository/foo?ids=1,2,3`

The relevant code is in _com.knime.enterprise.cloud.service.repository.impl/src/main/java/com/knime/enterprise/cloud/service/repository/impl/v4_
This occurs in Open Liberty 18.0.0.3.

[jar-zip.zip](https://github.com/OpenLiberty/open-liberty/files/2926729/jar-zip.zip)

**Comment by bpaskin-ibm** [comment] 2019-03-04 17:25
This has nothing to do with the findings of the IBM team, but I believe you need a `?` instead of a `/` after `foo` to read in the query parameters, which `1,2,3` will be read in as a `String` first.

**Comment by WhiteCat22** [comment] 2019-03-04 22:47
Looks like some of the logic we are doing in InjectionUtils.injectIntoCollectionOrArray() to get the realType could use some work.

paramType=interface java.util.List and genericType=java.util.List<java.lang.String> until that point.

**Comment by WhiteCat22** [comment] 2019-03-13 19:53
I tested with CXF 3.2.8 and the issue does not occur, so this must be the result of some change we've made to CXF.

Uploading the war file (with source) I used to reproduce with vanilla CXF (change .zip to .war)
[CXFParamConverter.zip](https://github.com/OpenLiberty/open-liberty/files/2963410/CXFParamConverter.zip)

**Comment by andymc12** [comment] 2019-03-18 16:44
This issue should be resolved in the next Liberty release.  Thanks.

**Closed by andymc12** 2019-03-18 16:44 UTC
Labels: in:JAX-RS, release bug, team:Wendigo West
