### ISSUE TITLE
Generate jaxrs stubs for an openAPI v3 service

### ISSUE THREAD

**Issue by igbch** [OpenLiberty/open-liberty#3366] opened 2018-04-30 19:09 UTC
I miss the possibility to generate jaxrs stubs out of an openAPI v3 service and let it run on open liberty, that would help the contract first design.

**Comment by tevans78** [comment] 2018-08-23 15:42
Closing as a duplicate of the OpenAPITools issue

**Closed by tevans78** 2018-08-23 15:42 UTC
Labels: Needs member attention, duplicate, enhancement
