### ISSUE TITLE
getManagedConnection: illegal state exception. State = STATE_INACTIVE

### ISSUE THREAD

**Issue by Tr4m4** [OpenLiberty/open-liberty#10929] opened 2020-02-17 15:25 UTC
We have run parallel thread and one of them gone in "transaction timeout":
```

 Caused by: java.nio.channels.AsynchronousCloseException 
 	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:223) 
 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:421) 
 	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:178) 
 	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:544) 
 	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:234) 
 	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:174) 
 	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:122) 
 	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:100) 
 	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:86) 
 	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:762) 
 	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:427) 
 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:394) 
 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255) 
 	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610) 
 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:253) 
 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:86) 
 	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:765) 
 	... 97 more 

```
For the successive thread this exception has logged:
```

Caused by: java.lang.IllegalStateException: getManagedConnection: illegal state exception. State = STATE_INACTIVE MCW = 1df9dfdf 
 	at com.ibm.ejs.j2c.MCWrapper.getManagedConnection(MCWrapper.java:700) 
 	at com.ibm.ejs.j2c.FreePool.getMCWrapperFromMatch(FreePool.java:1302) 
 	at com.ibm.ejs.j2c.FreePool.getFreeConnection(FreePool.java:600) 
 	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1329) 
 	at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:581) 
 	at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:314) 
 	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:138) 
 	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:112) 

```
This bug is the same of issue https://github.com/OpenLiberty/open-liberty/issues/7211 and it was be fixed in release 19.0.0.4 i don't know why it's happen.

 - OpenLiberty Version: Open Liberty Version 19.0.0.9 - (19.0.0.9-201909050201)

**Comment by njr-11** [comment] 2020-02-17 15:37
Although the message is similar, issue #7211 had a different exception stack.  It fixed a different problem, isolated to a connection error being reported on transaction timeout/abort code path, that does not apply to the stack that you posted.
Thank you for reporting the issue.  A separate investigation into the cause and a different fix will be needed for this.

**Comment by KyleAure** [comment] 2022-08-25 21:28
This issue should have been fixed with PR: https://github.com/OpenLiberty/open-liberty/pull/12025
Please upgrade past 20.0.6 and if the issue persists re-open this issue.

**Closed by KyleAure** 2022-08-25 21:28 UTC
Labels: bug, team:Zombie Apocalypse
