### ISSUE TITLE
Jaxrs client - thrown exception in ClientResponseFilter is not catchable in client code

### ISSUE THREAD

**Issue by waynecs12** [OpenLiberty/open-liberty#12586] opened 2020-06-12 11:30 UTC
I added a ClientResponseFilter to throw an exception when an error response is returned (like 404). However, the exception never makes it back to my client code, I end up getting a Response object anyway.
This works if I use the jersey jaxrs2 client.

**Steps to Reproduce**
Sample filter code:

```
> public class TestClientResponseFilter implements ClientResponseFilter {
> 
>   @Override
>   public void filter(ClientRequestContext requestContext, ClientResponseContext responseContext)
>       throws IOException {
>     if (responseContext.getStatus() >= 400) {
>       throw new WebApplicationException("exception thrown", responseContext.getStatus());
>     }
>   }
> }
> 
```
Calling code:

```
> @Path("")
> public class TestResource {
> 
>   @GET
>   @Produces(MediaType.APPLICATION_JSON)
>   public Response hello() {
>     try {
>       return ClientBuilder.newClient()
>           .target("http://localhost/nothing")
>           .register(TestClientResponseFilter.class)
>           .request()
>           .get();
>     } catch (Exception e) {
>       // exception should get here
>       return Response.status(Status.INTERNAL_SERVER_ERROR).entity(e).build();
>     }
>   }
> }
```

**Expected behavior**
Expected the exception to be thrown rather than a Response returned.

**Diagnostic information:**
 - WebSphere Application Server 20.0.0.3 (1.0.38.cl200320200305-1433) on IBM J9 VM, version 8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10) (en_US)
 - Java Version: java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200402_443261 (JIT enabled, AOT enabled)
OpenJ9   - 35ef566
OMR      - 4bca4f4
IBM      - 55acf4a)
JCL - 20200407_01 based on Oracle jdk8u251-b08

 ```
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>concurrent-1.0</feature>
        <feature>jndi-1.0</feature>
        <feature>localConnector-1.0</feature>
		<feature>jaxrs-2.0</feature>
		<feature>cdi-1.2</feature>
	</featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint host="*" httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"/>
                  
    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <applicationMonitor updateTrigger="mbean"/>
    <quickStartSecurity userName="admin" userPassword="admin"/>
    <logging traceSpecification="com.ibm.ws.jaxrs*=all:com.ibm.websphere.jaxrs*=all:org.apache.cxf.*=all:org.apache.cxf.*=all"/>

    <webApplication id="test-service" location="test-service.war" name="test-service"/>
</server>
```

messages.log file:
```
********************************************************************************
product = WebSphere Application Server 20.0.0.3 (wlp-1.0.38.cl200320200305-1433)
wlp.install.dir = /x/wlp/
java.home = /usr/lib/jvm/java-1.8.0-ibm-1.8.0.6.10-1jpp.1.el7.x86_64/jre
java.version = 1.8.0_251
java.runtime = Java(TM) SE Runtime Environment (8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10))
os = Linux (3.10.0-1062.18.1.el7.x86_64; amd64) (en_US)
process = 20265@127.0.0.1
********************************************************************************
[6/12/20 7:16:27:648 EDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server defaultServer has been launched.
[6/12/20 7:16:28:022 EDT] 00000028 com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:com.ibm.websphere.jaxrs*=all:com.ibm.ws.jaxrs*=all:org.apache.cxf.*=all:org.apache.cxf.*=all.
[6/12/20 7:16:28:090 EDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 0.536 seconds
[6/12/20 7:16:28:115 EDT] 0000002c com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[6/12/20 7:16:28:254 EDT] 00000021 com.ibm.ws.annocache.service                                 I OSGi Work Path [ /x/wlp/usr/servers/defaultServer/workarea/org.eclipse.osgi/41/data ]
[6/12/20 7:16:28:320 EDT] 00000024 com.ibm.ws.app.manager.internal.monitor.DropinMonitor        A CWWKZ0058I: Monitoring dropins for applications.
[6/12/20 7:16:28:994 EDT] 00000037 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application test-service.
[6/12/20 7:16:28:995 EDT] 00000037 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0134I: The test-service application is using the loose application definition at the /x/wlp/usr/servers/defaultServer/apps/test-service.war.xml location.
[6/12/20 7:16:29:177 EDT] 00000037 com.ibm.ws.session.WASSessionCore                            I SESN8501I: The session manager did not find a persistent storage location; HttpSession objects will be stored in the local application server's memory.
[6/12/20 7:16:29:191 EDT] 00000037 org.jboss.weld.Version                                       I WELD-000900: 2.4.8 (Final)
[6/12/20 7:16:29:689 EDT] 00000037 com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: test-service.
[6/12/20 7:16:29:691 EDT] 00000037 com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module test-service has been bound to default_host.
[6/12/20 7:16:29:691 EDT] 00000037 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://172.27.0.1:9080/test-service/
[6/12/20 7:16:29:697 EDT] 00000037 com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application test-service started in 0.703 seconds.
[6/12/20 7:16:29:705 EDT] 0000003d com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/test-service
[6/12/20 7:16:29:712 EDT] 0000003d com.ibm.ws.util                                              I SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[6/12/20 7:16:29:721 EDT] 0000002c com.ibm.ws.tcpchannel.internal.TCPPort                       I CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv6) port 9080.
[6/12/20 7:16:29:739 EDT] 0000002c com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [cdi-1.2, concurrent-1.0, jaxrs-2.0, jaxrsClient-2.0, jndi-1.0, json-1.0, localConnector-1.0, servlet-3.1].
[6/12/20 7:16:29:740 EDT] 0000002c com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 1.650 seconds.
[6/12/20 7:16:29:740 EDT] 0000002c com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.187 seconds.
[6/12/20 7:16:30:020 EDT] 00000038 com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /x/wlp/usr/servers/defaultServer/logs/state/plugin-cfg.xml.
[6/12/20 7:16:36:393 EDT] 0000003a .ibm.ws.jaxrs.2.0.common:1.0.38.cl200320200305-1433(id=121)] I Setting the server's publish address to be /
[6/12/20 7:16:36:839 EDT] 0000003a com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [test-service] [/test-service] [test.TestServiceApplication]: Initialization successful.
[6/12/20 7:16:37:647 EDT] 0000003a .ibm.ws.jaxrs.2.0.common:1.0.38.cl200320200305-1433(id=121)] W Interceptor for {http://localhost/nothing}WebClient has thrown exception, unwinding now
javax.ws.rs.WebApplicationException: exception thrown
	at test.TestClientResponseFilter.filter(TestClientResponseFilter.java:15)
	at org.apache.cxf.jaxrs.client.spec.ClientResponseFilterInterceptor.handleMessage(ClientResponseFilterInterceptor.java:66)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.jaxrs.client.ClientMessageObserver.onMessage(ClientMessageObserver.java:56)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1744)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1620)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1417)
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:685)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:715)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1038)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:427)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1551)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1546)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1466)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:84)
	at test.resources.TestResource.hello(TestResource.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:334)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:271)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5021)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)

[6/12/20 7:16:37:948 EDT] 0000003a com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.io.IOException: stream is closed org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor 267" at ffdc_20.06.12_07.16.37.0.log
[6/12/20 7:16:37:953 EDT] 0000003a org.apache.cxf.jaxrs.utils.JAXRSUtils                        E Problem with writing the data, class sun.net.www.protocol.http.HttpURLConnection$HttpInputStream, ContentType: text/html;charset=iso-8859-1
[6/12/20 7:16:37:976 EDT] 0000003a .ibm.ws.jaxrs.2.0.common:1.0.38.cl200320200305-1433(id=121)] W Interceptor for {http://resources.test/}TestResource has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: stream is closed
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:394)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:269)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:271)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5021)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
Caused by: java.io.IOException: stream is closed
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.ensureOpen(HttpURLConnection.java:3439)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3464)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3459)
	at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:196)
	at org.apache.cxf.helpers.IOUtils.copyAndCloseInput(IOUtils.java:161)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.copyInputToOutput(BinaryDataProvider.java:184)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:148)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1483)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1480)
	at java.security.AccessController.doPrivileged(AccessController.java:734)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1480)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:243)
	... 37 more

[6/12/20 7:16:44:286 EDT] 0000004f com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  A CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[6/12/20 7:16:44:289 EDT] 00000037 com.ibm.ws.tcpchannel.internal.TCPChannel                    I CWWKO0220I: TCP Channel defaultHttpEndpoint has stopped listening for requests on host *  (IPv6) port 9080.
[6/12/20 7:16:44:290 EDT] 00000037 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0017I: Web application removed (default_host): http://172.27.0.1:9080/test-service/
[6/12/20 7:16:45:291 EDT] 0000004f com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  I CWWKE1101I: Server quiesce complete.
[6/12/20 7:16:45:306 EDT] 00000042 com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [test-service] [/test-service] [test.TestServiceApplication]: Destroy successful.
[6/12/20 7:16:45:312 EDT] 00000042 com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0009I: The application test-service has stopped successfully.
[6/12/20 7:16:45:548 EDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0036I: The server defaultServer stopped after 17.995 seconds.


```

**Comment by jim-krueger** [comment] 2020-06-15 15:54
Wayne,  After reproducing this and fully investigating the code path, I believe that this is working as designed (at least from CXF's perspective).  Technically you are getting the exception,  but it is contained within the response object's InputStream you are getting.  In my repro it is something like this:

<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">javax.ws.rs.ProcessingException: Jim Test</ns1:faultstring></ns1:XMLFault>

Note:  If you specify and object in your get(),  such as get(String.class), then the exception will arrive as you expect.

In the related CXF code it is pretty clear that this is the behavior they want.  See line 939 in https://github.com/apache/cxf/blob/master/rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/WebClient.java:

_if (status != 304 && status >= 300 && responseClass != Response.class) {
            throw convertToWebApplicationException(r);_

Therefore I would suggest checking the status code, and if it is 300 or over, you should be able to just return the response object, it is the same as the one you are creating and returning in your current catch block.

Hopefully this helps.

**Comment by jim-krueger** [comment] 2020-06-25 12:45
Closing issue since it appears to be working as designed.

**Closed by jim-krueger** 2020-06-25 12:45 UTC
Labels: Needs member attention, bug
