### ISSUE TITLE
ServletContext getContextPath() does not end with forward slash.

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#14345] opened 2020-10-06 13:29 UTC
ServletContext.getContextPath() - The context path always comes first in a request URI. The path starts with a "/" character but does not end with a "/" character.

Currently getContextPath() does not check for the ending slash and includes it in the return.
Fix: check and remove the ending slash.  An info will be logged when this happens.  The flow continues.

Workaround: remove the configured ending / in the context root.

**Comment by pmd1nh** [comment] 2020-10-08 19:43
https://github.com/OpenLiberty/open-liberty/pull/14400

**Comment by pmd1nh** [comment] 2020-10-21 00:44
Additional information:

https://jakarta.ee/specifications/platform/8/apidocs/javax/servlet/ServletContext.html#getContextPath--

=====
String getContextPath()

Returns the context path of the web application.

The context path is the portion of the request URI that is used to select the context of the request. The context path always comes first in a request URI. If this context is the "root" context rooted at the base of the Web server's URL name space, this path will be an empty string. Otherwise, **if the context is not rooted at the root of the server's name space, the path starts with a / character but does not end with a / character.**

It is possible that a servlet container may match a context by more than one context path. In such cases the HttpServletRequest.getContextPath() will return the actual context path used by the request and it may differ from the path returned by this method. The context path returned by this method should be considered as the prime or preferred context path of the application.

Returns:
    The context path of the web application, or "" for the root context
=====

**Comment by mbroz2** [comment] 2020-10-28 14:13
The vote for [Do we Agree to change the default behavior of future versions of Java Servlet (starting with 5.0) to strip the trailing `/` (forward slash) if present, and print an Info msg?](https://github.ibm.com/was-liberty/POC-Meeting/issues/8) has been Approved

**Comment by tarator** [comment] 2021-03-03 18:50
**Actual behaviour:** When calling `getContextPath()` Jetty 11 returns a "/" (Slash) when an app is deployed in ROOT Context. 

**Expected behaviour:** Jetty should return an empty string in this case.

Because:
A context path should not end with "/" (In Jetty 10 I get an empty string as expected).

**Comment by bmarwell** [comment] 2021-04-14 19:57
@mbroz2 @pnicolucci can this be merged at some point? :)

**Comment by pnicolucci** [comment] 2021-04-15 17:28
@bmarwell  yes we're working to get this delivered in the next couple of days! Sorry for the delay!

**Closed** 2021-04-21 14:39 UTC
Labels: POC Approved, bug, in:Web Components, release bug, team:Sirius

**Comment by pmd1nh** [comment] 2021-04-21 14:41
merged.
