### ISSUE TITLE
Cannot download open liberty from official website

### ISSUE THREAD

**Issue by Nekyt** [OpenLiberty/open-liberty#26229] opened 2023-09-11 08:54 UTC
Hello,

When I go to https://openliberty.io/start/ and click to download the Jakarta ee 10 23.0.0.8 zip version of open liberty i get a server error, see screnshot.
![error-openliberty](https://github.com/OpenLiberty/open-liberty/assets/31213138/e821dbc4-4cda-43fe-8087-3df8b2bc60f4)

Have a nice day,
Sincerely,
Nykyta

**Comment by yeekangc** [comment] 2023-09-11 13:00
We are looking into this.

**Comment by Nekyt** [comment] 2023-09-11 15:12
Seems like it is fixed. I can download open liberty now.

**Comment by mbroz2** [comment] 2023-09-11 16:19
The issue is specific to the EU mirror.  While the underlying issue there is being investigated and resolved, the traffic will instead be routed to the US mirror (so the response may be slightly degraded until EU mirror is restored).

Given the above, I'm going to close this issue.  If the problem returns, or a new one is spotted, don't hesitate to open a new issue.

**Closed as completed** 2023-09-11 16:21 UTC
Labels: Needs member attention
