### ISSUE TITLE
JAXRS leaks memory when applications do not close their Client references

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#11249] opened 2020-03-10 18:52 UTC
When applications are poorly coded to not close their JAXRS Client objects when they are done with them, the JAXRS runtime will leak.  The JAXRS runtime should be able to handle this situation so as not to leak.

**Comment by jhanders34** [comment] 2020-08-31 15:19
The issue is that clientsPerModule in JAXRSClientImpl keeps a hard reference on the client so it won't garbage collect.  If we changed the value to be a WeakReference and poll when accessing the collection, things would clean up nicely and not leak.

**Comment by jhanders34** [comment] 2020-10-07 14:01
FYI, I have started work on resolving this issue and hope to have a PR available soon for review.

**Closed** 2021-02-10 14:53 UTC
Labels: in:JAX-RS, release bug, team:Wendigo West
