### ISSUE TITLE
JakartaEE: PackageRename: Enable Batch for JakartaEE

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#11724] opened 2020-04-09 20:04 UTC
* Package rename
* support for new XML NS for job XML, batch.xml files
* support within the job XML for javax.* => jakarta.* property names.

**Comment by jhanders34** [comment] 2021-09-22 15:57
Duplicate of #11863

**Closed by jhanders34** 2021-09-22 15:57 UTC
Labels: story, Epic, team:Batch, jakartaEE, packageRename
