### ISSUE TITLE
server.bat has wrong goto lines in release bundle causing error

### ISSUE THREAD

**Issue by newmangreen** [OpenLiberty/open-liberty#27894] opened 2024-03-12 09:44 UTC
Hi,

Release bundle appends following lines to the end of server.bat file and that causes following error when running server.bat:
`The system cannot find the batch label specified - eof`

"server.bat" in this repository doesn't have last buggy section, I think it is appended during release bundle preparation. This error appears when JAVA_HOME is not specified. Download openliberty-24.0.0.2.zip from link given here and see end of server.bat;
[https://github.com/OpenLiberty/open-liberty/releases/tag/gm-24.0.0.2](https://github.com/OpenLiberty/open-liberty/releases/tag/gm-24.0.0.2)

![Liberty server bat error](https://github.com/OpenLiberty/open-liberty/assets/26571935/5559d3ef-9271-4b88-80cd-4974357f916c)

These 2 lines should be fixed like this;
goto :eof --> goto:eof
goto eof --> goto:eof

This bug is also seen in commercial WebSphere Liberty releases.

**Comment by tevans78** [comment] 2024-03-12 09:52
Looks like that section was introduced by https://github.com/OpenLiberty/open-liberty/pull/26197 but then removed again by https://github.com/OpenLiberty/open-liberty/pull/27654. So the problem should be fixed in the next release.

**Comment by tevans78** [comment] 2024-03-12 09:55
#regression

**Comment by jimblye** [comment] 2024-03-19 12:28
Affects 23.0.0.10-24.0.0.2.  Fixed in 24.0.0.3.    APAR PH60430 created.

**Closed as completed by jimblye** 2024-03-19 12:28 UTC
Labels: regression, release bug, Acknowledged

**Comment by jimblye** [comment] 2024-03-19 13:26
Also, to reproduce the error, I found that JAVA_HOME must not be set AND Java must not be in the PATH.

Only the bottom "goto eof" is incorrect.   The other one, "goto :eof", is perfectly fine.  The space is optional.  The colon is not.   So if java.exe is found in the PATH, then the incorrect statement is not encountered.
