### ISSUE TITLE
Can not disable default welcome page: removeServerHeader does not work

### ISSUE THREAD

**Issue by takakiyo** [OpenLiberty/open-liberty#5578] opened 2018-11-01 02:48 UTC
[Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_httpOptions.html) says `removeServerHeader` attribute of `httpOptions` element disables default welcome page.

> Removes server implementation information from HTTP headers and also disables the default Liberty profile welcome page.

With OpenLiberty 18.0.0.3, changed server.xml like this.

```xml
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443">
        <httpOptions removeServerHeader="true"></httpOptions>
    </httpEndpoint>
```

But the welcome page (http://localhost:9080/) is still displayed.

**Comment by aguibert** [comment] 2018-11-01 13:53
Hi @takakiyo, thanks for reporting this issue.  I've done a quick test locally and confirmed that the server behavior is indeed inconsistent with the documentation.  Marking this as a bug.

**Comment by aguibert** [comment] 2018-11-01 14:45
The [`<httpOptions removeServerHeader="true"/>`](https://openliberty.io/docs/ref/config/#httpOptions.html) option seems to conflict with the [`<httpDispatcher enableWelcomePage="true"/>`](https://openliberty.io/docs/ref/config/#httpDispatcher.html) default value.

Looking at the code, I think we just need to make `com.ibm.ws.http.dispatcher.internal.HttpDispatcher.modified(Map<String, Object>)` take into account both `removeServerHeader` and `enableWelcomePage` values.

@NottyCode @pnicolucci what do you think about this?  IMO we should remove the documentation that `removeServerHeader=true` disables the welcome page, since we already have the `enableWelcomePage` attribute specifically for this.  Additionally, the intended behavior seems unclear if I were to configure these values so that they conflict (removeHeader=true and enableWelcomePage=true)

**Comment by NottyCode** [comment] 2018-12-11 15:33
@aguibert I think we need to update the metatype documentation for removeServerHeader. I don't believe this was ever intended to work this way and since there is a specific option on the httpDispatcher to disable the welcome page I think that is a better solution than making removeServerHeader work.

**Comment by pnicolucci** [comment] 2019-03-19 17:11
Manuel is going to take a look at making the doc updates.

**Closed** 2019-04-10 14:38 UTC
Labels: Needs member attention, bug, in:Web Components, team:Sirius
