### ISSUE TITLE
SCIM count parameter fails when specific attributes of user links to non-existing user

### ISSUE THREAD

**Issue by shubjit** [OpenLiberty/open-liberty#16202] opened 2021-03-11 09:47 UTC
**Describe the bug**
The following SCM URL fails where LDAP attribute , example "manager" refers to non-existing user.

ibm/api/scim/Users?count=1&startIndex=1&attributes=*

--------------

```
  FFDC1015I: An FFDC Incident has been created: "com.ibm.wsspi.security.wim.exception.EntityNotFoundException: CWIML4527E: The LDAP operation could not be completed. The LDAP entry uid=notexisting,ou=Users,dc=test,dc=com was not found: javax.naming.NameNotFoundException: [LDAP: error code 32 - NO_SUCH_OBJECT: failed for MessageType : SEARCH_REQUEST
Message ID : 8
    SearchRequest
        baseDn : 'uid=notexisting,ou=Users,dc=test,dc=com'
        filter : '(objectClass=*)'
        scope : base object
        typesOnly : false
        Size Limit : no limit
        Time Limit : no limit
        Deref Aliases : deref Always
        attributes : 'objectClass'
org.apache.directory.api.ldap.model.message.SearchRequestImpl@d0323f29: ERR_648 Invalid search base uid=notexisting,ou=Users,dc=test,dc=com]; remaining name 'uid=notexisting,ou=Users,dc=test,dc=com'; resolved object com.sun.jndi.ldap.LdapCtx@512b9d0e Specify the correct unique name of the entity and define the correct node mapping for the LDAP repository. com.ibm.ws.security.wim.adapter.ldap.LdapAdapter 1293" at ffdc_21.03.11_09.13.21.0.log
```

--------

**Steps to Reproduce**
- Create a sample LDAP server - Apache Directory Server (ou=Users,dc=test,dc=com)
- Create multiple users
- Create one User with ID , example user1  (uid=user1,ou=Users,dc=test,dc=com)
- Add a Attribute of type "manager" for this user
- Add a dummy user as value for manager - "uid=notexisting,ou=Users,dc=test,dc=com"
- Configure SCIM on Liberty using the above ldap server
- Access the Liberty URL https://LIBERTYSERVER:PORT/ibm/api/scim/Users?count=1&startIndex=1&attributes=*

** Result **
********************************************************************************
`{"Errors":[{"code":"500","description":"com.ibm.wsspi.security.wim.exception.WIMSystemException: CWIML1013E: The user registry operation could not be completed. The entered value of the property manager is not valid for the entity uid=user1,ou=Users,dc=ldap3,dc=com. The value of the property must be correct and must be of the correct data type."}]}`
********************************************************************************

**Expected behavior**
The error should be ignored, log as Warning and continue. It should list out one user along with the attributes.

**Diagnostic information:**
********************************************************************************
product = WebSphere Application Server 20.0.0.12 (wlp-1.0.47.cl201220201111-0736)
wlp.install.dir = /opt/test/wlp/
java.home = /opt/test/java/jre
java.version = 1.8.0_261
java.runtime = Java(TM) SE Runtime Environment (8.0.6.15 - pxa6480sr6fp15-20200724_01(SR6 FP15))
os = Linux (4.18.0-193.1.2.el8_2.x86_64; amd64) (en_US)
********************************************************************************

**Additional context**
`[3/11/21 9:16:10:661 UTC] 0000002c com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "com.ibm.wsspi.security.wim.exception.WIMSystemException: CWIML1013E: The user registry operation could not be completed. The entered value of the property manager is not valid for the entity uid=user1,ou=Users,dc=test,dc=com. The value of the property must be correct and must be of the correct data type. com.ibm.ws.security.wim.ProfileManager 571" at ffdc_21.03.11_09.16.10.1.log`

**Comment by shubjit** [comment] 2021-03-11 09:50
Our Application uses liberty SCIM URLs to validate users and group and the first lookup URL is 
https://libertyserverHOST/ibm/api/scim/Users?count=1&startIndex=1&attributes=*

Due to this issue our application setup fails. Prior to editing our code, we would like to understand if this is an easy fix from Liberty.

**Comment by jvanhill** [comment] 2021-03-11 14:35
@shubjit - 

The scim-1.0 feature is included in WebSphere LIberty, but not in Open Liberty. To open a support issue against WebSphere Liberty, please visit this link to create a new case: https://www.ibm.com/mysupport/s/createrecord/NewCase

I am closing this issue.

**Closed by jvanhill** 2021-03-11 14:35 UTC
Labels: Needs member attention, bug, team:Wendigo East

**Comment by jvanhill** [comment] 2021-03-11 14:55
@shubjit - I looked closer at the code, and we throw this error when we are looking up attributes that are identifier types, such as looking up managers, and we can't find that entity. That is probably what is happening here since you are asking for all attributes. Perhaps one of the attributes on the users you are looking up is invalid or does not exist.

**Comment by shubjit** [comment] 2021-03-11 15:33
> @shubjit - I looked closer at the code, and we throw this error when we are looking up attributes that are identifier types, such as looking up managers, and we can't find that entity. That is probably what is happening here since you are asking for all attributes. Perhaps one of the identifier attributes on the users you are looking up is invalid or does not exist.

@jvanhill  Yes. testing with corporate ID, In particular there is a Secretary attribute, and for some reason they value that in there does not exist. In this case I am unable to use scim at with my corporate ID

**Comment by jvanhill** [comment] 2021-03-11 15:49
@shubjit - Please open a case, and my team can take a closer look.

**Comment by shubjit** [comment] 2021-03-11 15:50
Thank you so much. I will do that.

**Comment by jvanhill** [comment] 2021-03-11 15:50
I think at a minimum the message should be updated to help in understanding what the issue is.

**Comment by jvanhill** [comment] 2021-03-11 17:55
@shubjit - I did think of a work-around for you. You can remap the identifier attributes. For example, manager could be remapped in my example below.

The example is creating a new myManager extended property that can be used to look up the manager DN as a String, and not an identifier. The LDAP registry is being configured so that any requests for the manager property will be mapped to a non-existent LDAP attribute, and thus avoid the error of encountering managers that do not exist. The LDAP registry is also mapping the new myManager property to the manager LDAP attribute. However; since the type of the attribute is defined as string, we don't do an entity lookup and instead just return the manager DN as a string for myManager.

Also, although it appears that SCIM in Liberty supports it, technically a wildcard on attributes doesn't appear to be in the SCIM 1.0 specification. Changes could make it non-operational in the future, though it is probably unlikely.

```
  <ldapRegistry ... >
    ...
    <attributeConfiguration>
      ...
      <!--
            1. We are mapping the manager property to a non-existent attribute so that no value is found.
            2. We are mapping the newly defined extended property myManager to manager. We have 
                 defined the syntax as a string so that it will not treat it as an Identifier and try to look it up.
        -->
      <attribute name="notsupported" propertyName="manager" syntax="Identifier" entityType="PersonAccount" />
      <attribute name="manager" propertyName="myManager" syntax="String" entityType="PersonAccount" />
    </attributeConfiguration>
  </ldapRegistry>
  
  <federatedRepository ...>
    <!--
         Add an extended property myManager that we can use to look up any managers.
      -->
    <extendedProperty dataType="String" name="myManager" entityType="PersonAccount" />
  </federatedRepository>
```

**Comment by shubjit** [comment] 2021-03-12 05:37
@jvanhill the workaround is awesome. We had two attributes manager and secretary that were causing errors, I added similar configurations for secretary and did some quick tests and it works like a charm

Thank you for helping out even though it was specific to WebSphere Liberty. We will update our documentation with these additional configurations. Thanks Again for such quick responses.
