### ISSUE TITLE
OL 18.0.0.4 server package does not generate jar file

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#6061] opened 2018-12-18 17:22 UTC
For 18.0.0.3, the following server package command generated jar file
```
[INFO] CWWKM2001I: Invoke command is [/Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/liberty/wlp/bin/server, package, GettingStartedServer, --archive=/Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/getting-started.zip, --include=runnable].
[INFO] Packaging server GettingStartedServer.
[INFO] Server GettingStartedServer package complete in /Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/getting-started.jar.

```
But in 18.0.0.4, zip file was generated.
```
[INFO] CWWKM2001I: Invoke command is [/Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/liberty/wlp/bin/server, package, GettingStartedServer, --archive=/Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/getting-started.zip, --include=runnable].
[INFO] Packaging server GettingStartedServer.
[INFO] CWWKE0070W: The loose file /Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/liberty/wlp/usr/servers/GettingStartedServer/apps/getting-started.war.xml is invalid.
[INFO] Server GettingStartedServer package complete in /Users/gkwan/tasks/CNAI/guides/opensite/guide-getting-started/finish/target/getting-started.zip.
```

**Comment by cbridgha** [comment] 2019-01-03 16:41
Closing this as dup of https://github.com/openliberty/open-liberty/issues/6073. (All caused by same archive regression)

**Comment by andrewdes** [comment] 2019-02-01 16:25
Problem still exists in OL 19.0.0.1 even though https://github.com/OpenLiberty/open-liberty/issues/6073 was resolved.

**Comment by gkwan-ibm** [comment] 2019-02-04 14:42
hi @cbridgha I would like to make sure that you are aware of this issue and it must be fixed in 19.0.0.2.

**Comment by gkwan-ibm** [comment] 2019-02-04 19:44
In 18.0.0.3, the command `./server package GettingStartedServer --archive=ggs.zip --include=runnable` can package the server GettingStartedServer to a jar file with following message 
`Server GettingStartedServer package complete in /Users/gkwan/tasks/RASPMI/Liberty/wlps/18.0.0.3/wlp/usr/servers/GettingStartedServer/ggs.jar.`

But in 19.0.0.1, the same command packaged the server to a zip file with following message
`Server GettingStartedServer package complete in /Users/gkwan/tasks/RASPMI/Liberty/wlps/19.0.0.1/wlp/usr/servers/GettingStartedServer/ggs.zip.`

**Comment by gkwan-ibm** [comment] 2019-02-04 20:12
@hlhoots  ^

**Comment by marikaj123** [comment] 2019-02-20 22:19
According to the defect owner, a workaround solution was found.

**Comment by yeekangc** [comment] 2019-02-21 17:04
@cbridgha, do we have an outlook for when this will be addressed?  It's been an issue since 18.0.0.4.

**Comment by gkwan-ibm** [comment] 2019-02-21 17:47
Before the pom.xml in the getting start guide is defined as
```
<profile>
    <id>runnable-package</id>
    <properties>
       <packaging.type>runnable</packaging.type>
    </properties>
</profile>
```
in default --archive is used zip file.  When 18.0.0.3, jar file is generated but not 18.0.0.4+

For 19.0.0.1, the workaround is to specify the `<package.file/>`
```
<profile>
        <id>runnable-package</id>
        <properties>
            <package.file>
                ${project.build.directory}/${app.name}.jar
            </package.file>
            <packaging.type>runnable</packaging.type>
        </properties>
</profile>
```

**Comment by gkwan-ibm** [comment] 2019-02-21 18:04
We just like to know whether this behavior change is a regression or design change. If a design change, l will open a ci.maven issue to address this issue if possible.

**Comment by cbridgha** [comment] 2019-02-21 18:46
After our discussion:

A behavior change did occur when a related change was made  for 19001, but it was determined the behavior to create a runnable jar while at the same time passing an archive extension of "zip" is an invalid scenario, and the runtime should return an error code.

So this change isn't a regression, but rather fixing behavior to be what was originally intended.

The work to return an error code and message will be tracked by this issue

**Comment by gkwan-ibm** [comment] 2019-02-21 20:26
I am ok to treat following as the right way to tell readers to define if they want to build a runnable package
```
<profile>
        <id>runnable-package</id>
        <properties>
            <package.file>
                ${project.build.directory}/${app.name}.jar
            </package.file>
            <packaging.type>runnable</packaging.type>
        </properties>
</profile>
```
No further action for the getting start guide.

But, if they define following
```
<profile>
        <id>runnable-package</id>
        <properties>
            <packaging.type>runnable</packaging.type>
        </properties>
</profile>
```
either 1) it is an error, 2) maven should generate a jar file, or 3) maven should generate a zip file which is runnable

I think 3) is possible and right behavior but I doubt the current server package command can do that, because 4) currently maven generate a zip but not runnable.

Which is the right behavior, 1), 2) or 3)?

This question also applies to the server command 
```
server package --archive=<fileName>.zip --include=runnable
```

**Comment by yeekangc** [comment] 2019-02-22 14:13
My take is that it should be a runnable jar by default.  So, the minimum where the users specify only the packaging.type should produce a runnable jar.  That's the original intention of the capability too IIRC and AFAIK.

I would think if a zip file and runnable are specified, it should produce an error unless there is really a runnable zip?

Tagging @NottyCode @lauracowen for their thoughts in case they aren't tracking the issue.

**Comment by tevans78** [comment] 2019-02-26 17:06
Let Liberty output an error message if runnable is specified but the filename does not end in `.jar`.

Update the maven task to always output a `.jar` file. To be decided how this should be achieved. Could either replace any existing extension or simply append to it.

**Comment by tevans78** [comment] 2019-03-19 15:47
Maven should replace the zip extension with a jar extension.

**Closed by tevans78** 2019-03-19 15:47 UTC
Labels: design-issue
