### ISSUE TITLE
Messages.log is not displaying logs in correct format as it did in WAS8.5

### ISSUE THREAD

**Issue by amskamath** [OpenLiberty/open-liberty#15378] opened 2020-12-29 08:06 UTC
In WAS 8.5
**Logs contain only class name**
[8/6/20 12:34:39:670 UTC] 000000ed **BaseModule**    I   FXHUI012I: *** Framework UI Module initializing
[8/6/20 12:34:44:012 UTC] 000000ed **BaseModule**    I   FXHUI029I: *** Financial Transaction Manager build information: Component name: Framework UI Module, Product id: FXH, Specification-Version=--, Implementation-Version=-- -- --
[8/6/20 12:34:44:016 UTC] 000000ed **BaseModule**    I   FXHUI013I: *** Framework UI Module initialized
[8/6/20 12:34:44:027 UTC] 000000ed **BaseModule**    I   FXHUI012I: *** Core UI Module initializing
[8/6/20 12:34:46:808 UTC] 000000ed **BaseModule**    I   FXHUI029I: *** Financial Transaction Manager build information: Component name: Core UI Module, Product id: IYB, Specification-Version=--, Implementation-Version=-- -- --
[8/6/20 12:34:46:811 UTC] 000000ed BaseModule    I   FXHUI013I: *** Core UI Module initialized

In Liberty 20.0.012
**Logs contain package names**
[8/5/20 2:02:01:771 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI012I: *** Framework UI Module initializing
[8/5/20 2:02:06:000 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI029I: *** Financial Transaction Manager build information: Component name: Framework UI Module, Product id: FXH, Specification-Version=4.0.0.0, Implementation-Version=Bld20200804-2209 08/04/2020 22:09:00
[8/5/20 2:02:06:020 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI013I: *** Framework UI Module initialized
[8/5/20 2:02:06:052 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI012I: *** Core UI Module initializing
[8/5/20 2:02:08:270 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI029I: *** Financial Transaction Manager build information: Component name: Core UI Module, Product id: IYB, Specification-Version=4.0.0.0, Implementation-Version=Bld20200804-2209 08/04/2020 22:09:00
[8/5/20 2:02:08:280 UTC] 0000003f **com.ibm.fxh.framework.utilities.modules.BaseModule**           I FXHUI013I: *** Core UI Module initialized

Below settings were applied in server.xml to get logs in required format
 logging traceSpecification="*=info:" messageFormat="SIMPLE"

This doesn't seem to work. Do we have any settings to be applied to get this working.

**Comment by Channyboy** [comment] 2021-01-07 19:44
Hello @amskamath , 
In OpenLiberty the usage of the full package name is the default format for the log events in `messages.log`.
This is not configurable.

The `messageFormat` configuration is to specify whether the log _type_ for `messages.log` is in `json` or `simple`. Simple indicates _text_ format.

**Comment by Channyboy** [comment] 2021-01-07 20:31
@amskamath  May I ask what issue is being caused by the full package name?
If you have been parsing the fields of the logging event in WebSphere Application Sever then perhaps consider using the JSON log capability in OpenLiberty.

**Comment by Channyboy** [comment] 2021-01-13 16:55
@amskamath Hello, if there are no more concerns I will close this issue.

**Comment by amskamath** [comment] 2021-01-13 17:04
> @amskamath May I ask what issue is being caused by the full package name?
> If you have been parsing the fields of the logging event in WebSphere Application Sever then perhaps consider using the JSON log capability in OpenLiberty.

The issue we notices in messages.log.. sometimes it doesnt add class name and only package name was getting displayed.

**Comment by Channyboy** [comment] 2021-01-13 17:22
> The issue we noticed in messages.log is that sometimes it doesn't add class name and only package name was getting displayed in logs.

Do you have a snippet of the `messages.log` where the class name is missing from the package name and may you paste it here?

>Can we have similar behavior as we have in console logs as below:
The console logs were having the expected format.
[8/19/20 12:04:47:334 UTC] 00000055 BaseModule I FXHUI013I: *** Risk UI Module initialized
[8/19/20 12:04:47:360 UTC] 00000055 BaseModule I FXHUI012I: *** Approvals Module initializing

You can open a Feature Request issue to request this functionality and it will be up for deliberation.

**Comment by amskamath** [comment] 2021-01-13 18:20
> > The issue we noticed in messages.log is that sometimes it doesn't add class name and only package name was getting displayed in logs.
> 
> Do you have a snippet of the `messages.log` where the class name is missing from the package name and may you paste it here?
Below is the snippet:
The error log contained a log line that only had a part of the package name which made the stacktrace confusing to read
[8/7/20 11:07:08:402 UTC] 00000082 ies.managers.**CXCPaymentEntityManager**[Web_Services:WS_MODULE] E CXCUI999S: General Entity Manager failure.  Yoko encountered an internal error

> 
> > Can we have similar behavior as we have in console logs as below:
> > The console logs were having the expected format.
> > [8/19/20 12:04:47:334 UTC] 00000055 BaseModule I FXHUI013I: *** Risk UI Module initialized
> > [8/19/20 12:04:47:360 UTC] 00000055 BaseModule I FXHUI012I: *** Approvals Module initializing
> 
> You can open a Feature Request issue to request this functionality and it will be up for deliberation.

**Comment by Channyboy** [comment] 2021-01-13 19:03
I am unfamiliar with `ies.managers.CXCPaymentEntityManager`. That does not appear to be part of the OpenLiberty code-base. 

But based on the the semantics of `CXCPaymentEntityManager` that appears to be a class name as evident by the _EntityManager_ portion of the string and thusly `ies.managers.CXCPaymentEntityManager` is the full-package name + class name.

If there are no more issues concerning the formatting of `messages.log` can this issue be closed?

**Comment by Channyboy** [comment] 2021-01-14 18:37
Hi @amskamath If there are no other concerns I will close this issue.

**Comment by amskamath** [comment] 2021-01-15 05:52
> Hi @amskamath If there are no other concerns I will close this issue.

Hi.. In one of your comments you asked to open a feature request to address the formatting issue,  so do you know how can I go about it..So that we could go ahead and close this issue and track the feature request.

**Comment by Channyboy** [comment] 2021-01-18 21:14
@amskamath When you open a new issue in OpenLiberty there is a list of different issues you can open.
One of them is `Feature request`.

**Comment by Channyboy** [comment] 2021-01-21 03:39
As the instructions for pursuing a feature request have been detailed and the reason for this issue has been "resolved" I will be closing this issue.

**Closed by Channyboy** 2021-01-21 03:39 UTC
Labels: Needs member attention, team:Lumberjack
