### ISSUE TITLE
[22.0.0.9] Unmarshaller error  when Unmarshaller obtained [from  pool]

### ISSUE THREAD

**Issue by LucaT75** [OpenLiberty/open-liberty#23583] opened 2022-12-05 11:00 UTC
Hi,
 we have upgrade openliberty to 22.0.0.9, now an existing application throw an excption when mange SOAP call.
 When invoking the service, the exception occurs once every two calls (with the same request message)
 
 When the exception occurs in the logs we see  : _Unmarshaller obtained [from  pool]_
 When the request is succesully manage we see : _Unmarshaller created [not in pool]_

**Comment by jhanders34** [comment] 2022-12-05 15:28
@LucaT75 can you provide more details about what the exception that occurs is?  This will help to determine what the problem is.  Or if you can give information about what makes your scenario different that could explain why this happens for you and not for others.

**Comment by LucaT75** [comment] 2022-12-09 16:35
We send a message that conains an element receiptDate defined as <xs:element minOccurs="0" name="receiptDate" type="xs:anySimpleType"/>

The message is like : 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
.......
    <receiptDate/>
.......
 </soap:Body>
</soap:Envelope>

This field in java is mapped as XMLGregorianCalendar receiptDate;

[ErrorLog.txt](https://github.com/OpenLiberty/open-liberty/files/10196488/ErrorLog.txt)

When the Unmarshaller is not in the pool, we don't have the problem.


At the moment I can provide you more detail only in private way

**Comment by neuwerk** [comment] 2022-12-09 16:46
@LucaT75 thank you for the update! That actually might be enough information to recreate the issue hopefully. Let me try it, and I'll get back to you if I've had success or not.

**Comment by LucaT75** [comment] 2022-12-12 00:51
Hi, I have created an example project to show the problem, the repository is [OpsApplication](https://github.com/LucaT75/OpsApplication)

**Comment by LucaT75** [comment] 2022-12-14 10:37
Hi, @neuwerk have you looked at the project? Were you able to reproduce the anomaly with the example application?

**Comment by neuwerk** [comment] 2022-12-14 14:56
@LucaT75 I sure was, and I was able to recreate the issue. Thank you so much for uploading that. I'm in the process of problem determination and I will update you when I know more.

**Comment by neuwerk** [comment] 2023-01-19 16:32
@LucaT75 I've just merged a fix for this with #23926. This should go out with the 23.0.0.1 version of Liberty, not sure if you can test with what's in the github repo, that would be one way of verifying the change resolves your issue. Other wise, once you've been able to verify with 23.0.0.1 we can hopefully get the issue closed out.

**Comment by LucaT75** [comment] 2023-01-21 09:38
@neuwerk  thanks for your support. I hope to verify soon the fix on versione 23.0.0.1

**Comment by neuwerk** [comment] 2023-01-23 16:07
On second thought, I'm closing this issue in the interim, but please reopen if @LucaT75 this isn't resolved.

**Closed as completed by neuwerk** 2023-01-23 16:07 UTC
Labels: release bug, release:23001
