### ISSUE TITLE
Test Failure: com.ibm.ws.microprofile.metrics20.tck.launcher.FATSuite.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8667] opened 2019-08-19 22:11 UTC
RTC 265032

```
launchTck:junit.framework.AssertionFailedError: Timeout occurred. Please note the time in the report does not reflect the time until the timeout.
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.Try.execute(Try.java:119)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.ForEach.execute(ForEach.java:158)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.If.execute(If.java:85)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.BuildProjects.doExecute(BuildProjects.java:399)
at com.ibm.aries.buildtasks.BuildProjects.execute(BuildProjects.java:231)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base
```

**Comment by lamkavan** [comment] 2019-08-29 16:20
----------------------------------------------------Update---------------------------------------------------
Issues:
The test simply times out for taking to long. The limit for this test is 1-hr long. After which the test is aborted thus returning the error we are getting.

Findings:
After taking a close look at the logs and comparing them to the logs when the test was successful
I was able to make a reasonable hypothesis on the cause of this test failure. We can clearly see in message.log from the failed test that it is able to start and run the test. In fact the execution of the tests are quite quick and match the expected times. However, during the test there are multiple times
where it would need to start new applications (ie/I CWWKZ0018I: Starting application 1d50f5af-d93d-4f52-8fdb-8e4b25a24cc3. ) and also load web modules (I SRVE0250I: Web Module 1d50f5af-d93d-4f52-8fdb-8e4b25a24cc3 has been bound to default_host) and each time it is taking about 1.2 min. From the good logs we can clearly see that this should be taking around 5 sec max. Now take 1.2 min
but multiply that by around 45 times and we realize that this is making the test take much longer to complete. Also, I noticed that the web applications that are no longer needed are not removed. In the clean set of logs I can see lines indicating that web applications are removed but these lines do not appear in the logs from the failed test.

Conclusions:
The test is running and there are no problems with the test code itself. The cause for this issue most likely has to do with a Windows file locking issue. As noted there are many web applications that are not being removed or can not be removed. This would lead the machine running the test to get overloaded as it has to constantly try removing the web applications (probably in a loop). This as a result slows down the machine running the test or even worse makes it incapable of running further test. This is the best explanation for why starting new applications takes around 1.2 mins each as opposed to 5 sec (max). The last piece of evidence as to why I believe this is a windows file locking issue is because from RTC (https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=265032&tab=com.ibm.team.workitem.tab.links) we can see that all the builds reported against are all Windows (the latest one occurring on Aug 15, 2019 as of Aug 29, 2019)

Next Steps:
The team and I will continue to monitor this issue to see if it reoccurs. I have an understanding that the Windows file locking error is a known issue and a fix was but out, but I am not sure on the exact date. I heard it was Aug 17, 2019 which is after the latest date of occurrence for this issue (Aug 15, 2019).

**Comment by lamkavan** [comment] 2019-09-06 14:35
This has not reoccurred within the last 2 weeks. Closing this issue.

**Comment by fmhwong** [comment] 2020-01-07 14:21
Reoccurred on 01/04/2020

**Comment by lamkavan** [comment] 2020-01-07 16:35
------------------------------------------ UPDATE------------------------------------------
The most recent occurrence on 01/04/2020 is indeed a Timeout. However, after studying the logs it is clear that the cause is different from when the issue first appeared back in Aug/July of 2019.
There seems to be an issue with checking the state of applications which is evident from lines such as 
```org.jboss.arquillian.container.spi.client.container.DeploymentException: Exception while checking state of application <app name>``` appearing. All the test cases that failed has this same problem with checking the state of the applications. The issues with checking the state of the application was caused by... java.rmi.ConnectException: Connection refused to host: 127.0.0.1 according to the logs (there is one test case with Caused by: java.rmi.UnmarshalException: Error unmarshaling return header). A connection refused leads to the question if the applications were deployed successfully. 

Furthermore the first test case that fails goes as follows...
```[INFO    ] CWWKZ0018I: Starting application <app name x>.
[INFO    ] CWWKZ0133I: The <app name x> application at the /home/jazz_build/_JbZaMC7ZEeq6Hp0Ls0vRhA-EBC.PROD.WASRTC-6MG-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/MetricsTCKServer/dropins/<app name x>.war location is being expanded to the /home/jazz_build/_JbZaMC7ZEeq6Hp0Ls0vRhA-EBC.PROD.WASRTC-6MG-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/MetricsTCKServer/apps/expanded/<app name x>.war directory.
JVMDUMP039I Processing dump event "user", detail "" at 2020/01/05 00:24:00 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/jazz_build/_JbZaMC7ZEeq6Hp0Ls0vRhA-EBC.PROD.WASRTC-6MG-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/MetricsTCKServer/javacore.20200105.002400.28222.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/jazz_build/_JbZaMC7ZEeq6Hp0Ls0vRhA-EBC.PROD.WASRTC-6MG-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/MetricsTCKServer/javacore.20200105.002400.28222.0001.txt
JVMDUMP013I Processed dump event "user", detail "".
[WARNING ] RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44437] throws
Accept timed out
org.jboss.arquillian.container.spi.client.container.DeploymentException: Exception while checking state of application <app name x>```

The test cases that ran before the first failed one had no problems and usually if the app was deployed properly then we see the following...
```[INFO    ] SRVE0169I: Loading Web Module: <app name x>.
[INFO    ] SRVE0250I: Web Module <app name x> has been bound to default_host.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://<some url>/<app name x>/```

So the root cause seems to be something with failing to successfully deploy applications during the test cases.

**Comment by lamkavan** [comment] 2020-01-22 19:51
This has not reoccurred in over two weeks. Closing this issue. Occurrence on Jan 6, 2020 is most likely a one off.

**Closed by lamkavan** 2020-01-22 19:51 UTC
Labels: team:Lumberjack
