### ISSUE TITLE
Bean validation APIs leaking into container

### ISSUE THREAD

**Issue by davidkarlsen** [OpenLiberty/open-liberty#782] opened 2017-11-02 12:05 UTC
Hi - see details in https://github.com/spring-projects/spring-boot/issues/10877 .
It seems that validation-api classes are leaking into the application even though there is no feature enabled that should make this happen.

**Comment by aguibert** [comment] 2017-11-02 16:18
From the referenced issue, the set of features enabled are:

```xml
        <feature>monitor-1.0</feature>
        <feature>servlet-3.1</feature>
        <feature>localConnector-1.0</feature>
        <feature>jsp-2.3</feature>
        <feature>cdi-1.2</feature>
        <feature>jndi-1.0</feature>
        <feature>concurrent-1.0</feature>
        <feature>collectiveMember-1.0</feature>
```

**Comment by aguibert** [comment] 2017-11-02 16:53
I see that the cdi-1.2 feature pulls in the beanval API as a bundle (which is fine), but also exports the package as `type="internal"`, which will expose the package to the application classloader.

@tevans78 do you know why the cdi-1.2 feature needs to export javax.validation to the application classloader?

**Comment by aguibert** [comment] 2017-11-02 23:13
@davidkarlsen the issue here is that only some of the beanval packages (`javax.validatoin` specifically) are exposed to the app classloader when `cdi-1.2` is enabled.  After chatting w/ @Emily-Jiang , this is because CDI needs to generate proxies in the javax.validation package within the app classloader.

When you say "it works with webProfile-7.0", I suspect this is because one of two things are happening:
1. The regular `beanValidation-1.1` feature is being enabled, and your app is using that.
or
1. The regular `beanValidation-1.1` exposes all of the bean val packages to the app classloader, so you no longer have bean val packages/classes coming from two different sources (server and app).

In any case, I don't think we can resolve this API leak, because other user apps may be depending on the javax.validation package being exposed to the app classloader when they enable `cdi-1.2`.  Even if we did remove the API leak from the `cdi-1.2` feature, your app-provided beanval would not have any CDI integration, so at that point wouldn't it be better to just use the bean val provided by Liberty in the `beanValidation-1.1` feature?

**Comment by davidkarlsen** [comment] 2017-11-03 08:32
The challenge for me is that my app is a small side-car addon-on (used for monitoring and service-discovery) - so the server.xml is really configured (e.g. <features> selected) for the primary application. The challenge for me is that the classes are there half-ways, if CDI meant a transitive dependency to/included beanValidation-1.1 it would probably work. 

I'll try to get rid of validation all-together - but that was a bit tricky with spring-boot - but probably the way to go.

**Comment by Emily-Jiang** [comment] 2017-11-03 09:50
@davidkarlsen Do you have to package the api jars in your app? Have you tried to remove the api jar from your app? If you add beanValidation-1.1, it should also work. Please let us know what you think.

**Comment by wilkinsona** [comment] 2017-11-03 10:05
If the leak cannot be removed, would it be possible to make a change in WLP so that it leaks all of the API rather than a subset of its packages? The problem that @davidkarlsen is hitting is a side-effect of the `javax.validation` package being available but other packages in the API not being available. We can work around that in Boot if needs be, but I suspect there's lots of other code out there that expects the availability of the Bean Validation API to be all or nothing.

> Have you tried to remove the api jar from your app? If you add beanValidation-1.1, it should also work.

How would that work for an app that wants to use bean validation 2.0 by packaging the API and, say, Hibernate Validator 6.0 and trying to use that in favour of whatever WLP places on the app's classpath?

> I'll try to get rid of validation all-together - but that was a bit tricky with spring-boot - but probably the way to go.

@davidkarlsen I think we'll have to work around WLP's leak in Boot. To determine if the bean validation API is available, we currently look for `javax.validation.Validator` and `javax.validation.ValidatorFactory`. We find both of those and then assume that the rest of the API will be available. That assumption doesn't hold true here so a failure occurs. I'll re-open the Boot issue so that we can implement a workaround. Hopefully WLP can be updated so that the workaround will become unnecessary, but we should be able to get things working on the current version and the workaround won't cause any harm should an improvement be made to WLP in the future.

**Comment by wilkinsona** [comment] 2017-11-03 10:15
Having just looked at exactly what Boot's is doing, the leak is a bit worse than I'd realised.

Boot calls the static `javax.validation.Validation.byDefaultProvider()` method. This seems like a reasonable course of action having checked that the `javax.validation` package is available. The problem is that this method returns a `javax.validation.bootstrap.GenericBootstrap` instance and the leak currently means that the `javax.validation.bootstrap` package is unavailable. In effect, the partial leak means that the functionality provided by `javax.validation` is broken and cannot be relied upon.

**Comment by Emily-Jiang** [comment] 2017-11-03 10:38
> How would that work for an app that wants to use bean validation 2.0 by packaging the API and, say, Hibernate Validator 6.0 and trying to use that in favour of whatever WLP places on the app's classpath?

In @davidkarlsen 's app, it uses Bean Validation 1.1 api though. For bean validation 2.0, the bean validation team is working to get the api into Open Liberty.

@wilkinsona 
>To determine if the bean validation API is available, we currently look for javax.validation.Validator and javax.validation.ValidatorFactory. We find both of those and then assume that the rest of the API will be available. 
What do you mean the rest of apis? What are they?

**Comment by wilkinsona** [comment] 2017-11-03 10:59
> What do you mean the rest of apis? What are they?

The classes in the other packages in the Bean Validation API:

- `javax.validation.bootstrap`
- `javax.validation.contraints`
- `javax.validation.constrainvalidation`
- `javax.validation.executable`
- `javax.validation.groups`
- `javax.validation.metadata`
- `javax.validation.spi`

As I understand it, the leak being discussed here means that only `javax.validation` is available to the application's class loader. This is problematic as classes in that package refer to classes in other packages in the API:

- `javax.validation.BootstrapConfiguration.getDefaultValidatedExecutableTypes()` returns `Set<javax.validation.executable.ExecutableType>`
- `javax.validation.ConstraintViolation.getConstraintDescriptor()` returns `javax.validation.metadata.ConstraintDescriptor`
- `javax.validation.MessageInterpolator.Context.getConstraintDescriptor()` returns `javax.validation.metadata.ConstraintDescriptor`
- `javax.validation.Validation.byDefaultProvider()` returns `javax.validation.bootstrap.GenericBootstrap`
- `javax.validation.Validation.byProvider(Class<U>)` returns `javax.validation.bootstrap.ProviderSpecificBootstrap` and `U` is constrained to extending `javax.validation.spi.ValidationProvider`
- `javax.validation.ValidationProviderResolver.getValidationProviders()` returns `List<javax.validation.spi.ValidationProvider>`
- `javax.validation.Validator.getConstraintsForClass(Class)` returns `javax.validation.metadata.BeanDescriptor`
- `javax.validation.Validator.forExecutables()` returns `javax.validation.executable.ExecutableValidator`

The one that's tripping things up in @davidkarlsen's case is `javax.validation.Validation.byDefaultProvider()` returning `javax.validation.bootstrap.GenericBootstrap`. Calling that method results in the following exception:

```
Caused by: java.lang.ClassNotFoundException: javax.validation.bootstrap.GenericBootstrap
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:499)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:282)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:850)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:829)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:477)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:449)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:809)
	... 76 more
```

**Comment by davidkarlsen** [comment] 2017-11-03 12:56
@Emily-Jiang @wilkinsona It will even fail if I leave out both the imp (hibernate-validator) and the api (javax.validation): https://www.pastefile.com/Mvglv2

I have also tried excluding the validation auto-configuration like this:
```
@SpringBootApplication( exclude = ValidationAutoConfiguration.class )
```

**Comment by wilkinsona** [comment] 2017-11-03 12:59
@davidkarlsen That's to be expected, unfortunately. Please see the final paragraph of my [comment above](https://github.com/OpenLiberty/open-liberty/issues/782#issuecomment-341662391). We'll need to add a workaround in Boot for WLP exposing an incomplete view of the Bean Validation API.

**Comment by davidkarlsen** [comment] 2017-11-03 13:06
@wilkinsona Absolutely agree - I started my comment before you had posted your but got stuck in a meeting before I posted :). However a bit surprised that it still fails when I exclude auto-configuration for validation.

**Comment by davidkarlsen** [comment] 2017-11-03 13:09
@Emily-Jiang "@davidkarlsen Do you have to package the api jars in your app? Have you tried to remove the api jar from your app? If you add beanValidation-1.1, it should also work. Please let us know what you think." - as initially mentioned this is not an option for me - as I am just an addon-war - so it is the primary application that select their set of <feature>'s. Also see comments above - it will fail with or without adding the .jars to my app - but <feature> is out of my hands. Basically the only thing I can expect to be there is the servlet-api.

**Comment by aguibert** [comment] 2017-11-03 13:25
Not being able to add features you need to run your app is a pretty big limitation =)

I think the "intentionally leaking all bval API" approach may work, although at that point I think we should just make a private/protected bean val API feature and have the packages properly exported as type="spec".

**Comment by wilkinsona** [comment] 2017-11-03 13:46
Neither the  app itself nor Spring Boot need Bean Validation to run. What they need is a clear view of whether it’s there or not. The problem is that Spring Boot is being confused by the fact that `javax.validation` is available while `javax.validation.bootstrap` is not, despite the former requiring the latter. If the Bean Validation API was all there or all absent, the problem wouldn’t occur.

**Comment by aguibert** [comment] 2017-11-03 14:18
I agree that that the liberty CDI feature should either expose all of the bean val API or none of it, preferably the latter.

I made the necessary code change yesterday and put it through a functional test build and everything seems to work OK with the removal.  I'll get it merged in the next few days.  

Thanks for reporting this @davidkarlsen and @wilkinsona!

**Comment by Emily-Jiang** [comment] 2017-11-03 14:20
Thanks @davidkarlsen @wilkinsona @aguibert ! Great team work!

**Comment by aguibert** [comment] 2017-11-08 15:19
@davidkarlsen the fix for this issue has now been delivered.  Can you please confirm that the issue is resolved using the latest OpenLiberty nightly build?

I confirmed this image contains the fix:
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2017-11-08_0759/openliberty-all-17.0.0.3-201711080751.zip

**Comment by davidkarlsen** [comment] 2017-11-11 23:35
Hi - I tried it - but my particular setup relies on having collectiveMember-1.0 installed - which seems to not be a feature of openliberty.

**Comment by aguibert** [comment] 2017-11-13 14:11
That's correct, the `collectiveMember-1.0` feature is part of WAS Liberty.  The fix will be included in the next release of WAS Liberty (the November Beta), could you give it a try there once it's released?

**Comment by davidkarlsen** [comment] 2017-11-14 14:30
Will do. Where do betas get announced?

**Comment by aguibert** [comment] 2017-11-17 21:45
WAS betas get announced here:  https://developer.ibm.com/wasdev/downloads/liberty-profile-beta/
The November beta will probably come out in the last week of the month.

**Comment by aguibert** [comment] 2017-11-26 00:05
@davidkarlsen FYI the fix should now be available at the above link, since the Nov beta was announced yesterday

**Comment by aguibert** [comment] 2017-12-06 15:19
I'm going to close out this issue since the fix has been available for a bit now.

If for some reason the issue is not resolved for David then we can always re-open the issue.

**Closed by aguibert** 2017-12-06 15:19 UTC
Labels: in:Java EE Platform, team:Zombie Apocalypse
