### ISSUE TITLE
Test Failure: com.ibm.ws.testing.opentracing.test.OpentracingTCKLauncher.launchOpentracingTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8268] opened 2019-07-18 01:34 UTC
RTC 261048

```
launchOpentracingTck
junit.framework.AssertionFailedError: 2019-02-18-11:02:06:028 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs.
ResultsDir: /WebSphere/Misc/jazz_build/jbe_zrock043/jazz/buildsystem/buildengine/eclipse/build/dev/com.ibm.ws.opentracing.1.1_fat/autoFVT/results/tck/surefire-reports
at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:411)
at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:369)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:343)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:317)
at com.ibm.ws.testing.opentracing.test.OpentracingTCKLauncher.launchOpentracingTck(OpentracingTCKLauncher.java:56)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

Occurred on the following Platforms:
Liberty z/OS Platform Build - 20190218-0222

```

**Comment by tonyreigns** [comment] 2019-07-31 19:02
This issue was a duplicate of defect 259487

**Closed** 2019-07-31 19:02 UTC
Labels: team:Lumberjack
