### ISSUE TITLE
`jaxrs-2.0` not handling `beanValidation-1.1` exception with `ExceptionMapper<RuntimeException>` or `ExceptionMapper<Exception>` or `ExceptionMapper<Throwable>`

### ISSUE THREAD

**Issue by rslemos** [OpenLiberty/open-liberty#20031] opened 2022-02-03 15:24 UTC
**Describe the bug**  

`ExceptionMapper<RuntimeException>` or `ExceptionMapper<Exception>` are not being invoked to handle `ConstraintViolationException`.

**Steps to Reproduce**  

With a jaxrs resource like this:

```java
import javax.validation.Valid;
import javax.validation.constraints.Pattern;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

@Path("/inetd")
public class Inetd {
  /* ... */
  @GET
  @Path("/echo/{argument}")
  public String echo(@PathParam("argument") @Valid @Pattern(regexp = "^(?!quack).*$", message = "You know, quacks don't echo") String argument) {
    /* ... */
  }
}
```

An invocation to `.../inetd/echo/quack` will throw a `ConstraintViolationException` without executing the `echo` method.
**This is working fine**. Indeed, liberty shows at console:
```
 [ADVERTÊNCIA] Value 'quack' of Inetd.echo.arg0: You know, quacks don't echo
```

Now add a simple `ExceptionMapper<ConstraintViolationException>` to capture and handle the exception:

```java
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.enterprise.context.ApplicationScoped;
import javax.validation.ConstraintViolationException;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

@Provider
@ApplicationScoped
public class ConstraintViolationExceptionMapper implements ExceptionMapper<ConstraintViolationException> {

  @Override
  public Response toResponse(ConstraintViolationException exception) {
    StringWriter writer = new StringWriter();
    exception.printStackTrace(new PrintWriter(writer));
    return Response.status(Status.BAD_REQUEST)
      .entity(writer.toString())
      .build();
  }
}
```

That same invocation will now trigger the `ExceptionMapper` and nicely return a stacktrace to the client.
**This is also working**, as the http client shows:
```
> GET /[...]/inetd/echo/quack HTTP/1.1
> User-Agent: curl/7.71.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< X-Powered-By: Servlet/3.1
< Content-Type: application/octet-stream
< Date: Thu, 03 Feb 2022 14:51:19 GMT
< Content-Language: pt-BR
< Content-Length: 4175
< Connection: Close
<
javax.validation.ConstraintViolationException
        at org.apache.cxf.validation.BeanValidationProvider.validateParameters(BeanValidationProvider.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.callValidationMethod(LibertyJaxRsInvoker.java:371)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:254)
        [... 37 execution frames removed ...]
        at java.lang.Thread.run(Thread.java:748)
```
(also, no warning at the liberty console, as the exception has been handled)

Now some changes to this fairly general `ExceptionMapper` (to climb up the inheritance tree):
- change to `ExceptionMapper<ValidationException>`;
- change to `ExceptionMapper<RuntimeException>`;
- change to `ExceptionMapper<Exception>`.
(you should change the `toResponse` method signature as well)

Note: `ConstraintViolationException` is a `ValidationException`, which is a `RuntimeException`, which is an `Exception`.

**Expected behavior**  

As far as I can tell from the JAX-RS specs, all 4 ExceptionMappers should work the very same way.
But the `RuntimeException` and `Exception` versions are not.

I didn't investigate if this faulty behavior also happens with exceptions thrown within the resource method, or whether it just surfaces with exceptions thrown even before the method is invoked (the case with `ConstraintViolationException`).

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.1/wlp-1.0.60.cl220120220103-1900
 - Affected feature(s): beanValidation-1.1 jaxrs-2.0
 - Java Version: Java HotSpot(TM) 64-Bit Server VM, versão 1.8.0_271-b09 (pt_BR)
 - server.xml configuration:
```xml
<server>
  <featureManager>
    <feature>jaxrs-2.0</feature>
    <feature>cdi-1.2</feature>
    <feature>beanValidation-1.1</feature>
  </featureManager>

  <variable name="default.http.port" defaultValue="80"/>
  <httpEndpoint id="defaultHttpEndpoint" httpPort="${default.http.port}"/>
</server>
```

**Comment by WhiteCat22** [comment] 2022-02-03 15:35
Hi @rslemos,

Thank you for the great write up!

I should be able to look into this sometime next week. I'll let you know when I manage to reproduce or if I have any problems.

**Comment by rslemos** [comment] 2022-02-03 15:45
I've created [this repo](https://github.com/rslemos/liberty-20031) to show the bug.

To run the server:
```sh
mvn clean compile liberty:run
```

To invoke the invalid endpoint (and trigger the `ConstraintViolationException`):
```sh
curl -v localhost:9080/liberty-20031/rest/inetd/echo/quack
```

Hope this helps.

**Comment by rslemos** [comment] 2022-02-04 13:36
It is also not working with `ExceptionMapper<Throwable>`.

**Comment by jim-krueger** [comment] 2022-02-11 22:02
Hi @rslemos,
The ConstrainViolationExceptionMapper in the example you sent is running.   It is just returning an entity containing the Stack from the exception so that is what is being displayed when you run the curl command.   If you were to change your toResponse() method to something like the following, you would see "In exception mapper" in the logs on the server and you would not see the exception test displayed from the curl execution.

```
  @Override
  public Response toResponse(ConstraintViolationException exception) {
  System.out.println("In exception mapper");
  return null;
/*
   StringWriter writer = new StringWriter();
    exception.printStackTrace(new PrintWriter(writer));
    return Response.status(Status.BAD_REQUEST)
      .entity(writer.toString())
      .build();
*/
  }

```
Hopefully this helps.

**Comment by jim-krueger** [comment] 2022-02-11 22:03
I'm going to close this issue for now.   Please re-open if there are more questions.

**Comment by rslemos** [comment] 2022-02-12 01:03
I'm sorry for not being clear enough.

See, I know the `ConstrainViolationExceptionMapper` (as a `ExceptionMapper<ConstraintViolationException>`) in the example is working, as I stated in the opening post 

> **This is also working**, as the http client shows

and later on

> also, no warning at the liberty console, _as the exception has been handled_

[emphasis added].

**To trigger the real bug you have to proceed** with the proposed changes: from `ExceptionMapper<ConstraintViolationException>` to `ExceptionMapper<RuntimeException>`, or `ExceptionMapper<Exception>`, or `ExceptionMapper<Throwable>`.

Here is one such exercise:
```java
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

@Provider
@ApplicationScoped
public class ConstraintViolationExceptionMapper implements ExceptionMapper<Exception> {

  @Override
  public Response toResponse(Exception exception) {
    StringWriter writer = new StringWriter();
    exception.printStackTrace(new PrintWriter(writer));
    return Response.status(Status.BAD_REQUEST)
      .entity(writer.toString())
      .build();
  }
}
```

**With this `ExceptionMapper` in place (instead of the original one), the exception is no longer being handled**. And that's the bug.

**Comment by rslemos** [comment] 2022-02-12 01:07
I kindly ask you to reopen this issue.

**Comment by rslemos** [comment] 2022-02-12 01:16
Please, pay attention to the `ExceptionMapper` type parameter. Summarizing here (and trying to be clearer):

* `<ConstraintViolationException>`: it works;
* `<ValidationException>`: it works;
* `<RuntimeException>`: **not working**;
* `<Exception>`: **not working**;
* `<Throwable>`: **not working**.

By "not working" (for exception type E), I mean a sole `ExceptionMapper<E>` is not handling the `ConstraintViolationException` that is thrown outside (before) the jaxrs resource method has a chance to run (the `ConstraintViolationException` is expected, per validation rules; the bug lies solely on exception handling, which is not working with `<RuntimeException>`, `<Exception>` and `<Throwable>` type parameters).

**Comment by jim-krueger** [comment] 2022-02-13 17:40
My apologies @rslemos, I should have read this more carefully.  Also, I should have known better than to grab an issue and try to resolve it quickly on a later Friday afternoon :-)

Anyhow, I now realize why you are seeing this behavior.   The logic for exception mappers works by picking and executing the closest ExceptionMapper match to the exception being thrown.   So when you implement using "ConstraintViolationException" then that is the closest match.   Likewise when you use "ValidationException" that also works (although that might just be luck of the draw).  

What I've discovered is that CXF packages its own "ValidationException" [exception mapper](https://github.com/apache/cxf/blob/master/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/validation/ValidationExceptionMapper.java). So when you change your exception mapper to "RuntimeException", "Exception",  or "Throwable" then CXF's mapper is the closer match and is used.

I haven't done an exhaustive search, but on the surface there doesn't appear to be an easy way to disable CXF's mapper so you may need to have your mapper use "ConstraintViolationException" so it is chosen.

And I won't make the same mistake twice and close this issue immediately, in case more discussion is needed.

**Comment by jim-krueger** [comment] 2022-02-17 17:02
Closing this now.  Will re-open if more discussion is needed.

**Closed as completed by jim-krueger** 2022-02-17 17:02 UTC
Labels: in:JAX-RS, release bug

**Comment by rslemos** [comment] 2022-02-17 17:35
That's it? An application running in openliberty can't have its own `ExceptionMapper<ValidationException>`? Or its own catch-all `ExceptionMapper<Exception>` (regarding `ValidationException` and its subclasses)?

Per jax-rs spec, § 4.1.3 (Priorities)

> Application-supplied providers enable developers to extend and customize the JAX-RS runtime. Therefore,
> an application-supplied provider MUST always be preferred over a pre-packaged one if a single one is
> required.

Also, § 4.4 (Exception Mapping Providers) mandates

> When choosing an exception mapping provider to map an exception, an implementation MUST use the
> provider whose generic type is the nearest superclass of the exception. If two or more exception providers
> are applicable, the one with the highest priority MUST be chosen as described in Section 4.1.3.

**Comment by jim-krueger** [comment] 2022-02-17 18:41
Yes,  the sections you post from the spec match the behavior you are seeing.

- When your exceptionMapper is configured for `<ConstraintViolationException>` it works because (per 4.4) its type is the nearest superclass of the exception.
- When your exceptionMapper is configured for `<ValidationException>` it works  (per 4.1.3) your application-supplied provider is preferred.
- When your exceptionMapper is configured for `<RuntimeException>, <Exception>, or <Throwable>` your exceptionMapper is not executed because (per 4.4), CXF's exceptionMapper configured for `<ValidationException>` is the nearest superclass of the exception.
