### ISSUE TITLE
Health check endpoint throws exceptions

### ISSUE THREAD

**Issue by kenji1bm** [OpenLiberty/open-liberty#13064] opened 2020-07-16 03:28 UTC
Hello, we're using WebSphere Liberty 19.0.0.12 with microProfile-1.3 feature. When the health check endpoint was invoked, we got the following exceptions.

[2020-07-03T16:46:10.566+0900] 00000062 com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [com.ibm.ws.microprofile.health] [/health] [HealthCheckServlet]: Initialization successful.
[2020-07-03T16:46:10.800+0900] 00000062 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#AIF#AIF.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at com.ibm.ws.classloading.internal.ClassLoadingServiceImpl.getClassLoaderIdentifier(ClassLoadingServiceImpl.java:707)
	at com.ibm.ws.microprofile.health.services.impl.AppModuleContextService.getContextClassLoaderIdentifier(AppModuleContextService.java:145)
...

With a quick check, I found the issue with a same symptom.
https://github.com/OpenLiberty/open-liberty/issues/8573

But in this case, the condition where the issue happens is only for applications where the name attribute is explicitly specified in the server.xml and it does not match the WAR file name. We use a webApplication element in the server.xml and it does match the WAR file name. Is it supposed to a problem with a different root cause?

Here is the related parts of our server.xml.
```server.xml
    <webApplication id="AIF" location="AIF.war" name="AIF" contextRoot="generalreception">
        <classloader apiTypeVisibility="spec,ibm-api,api,stable,third-party" commonLibraryRef="failsafe"/>
        <web-ext enable-directory-browsing="false" enable-file-serving="false"/>
    </webApplication>
```

**Comment by pgunapal** [comment] 2020-07-16 16:05
Hi @kenji1bm This was fixed in 19.0.0.9 with https://github.com/OpenLiberty/open-liberty/pull/8631, its weird that you are seeing this in 19.0.0.12.

I could not reproduce it with your related server.xml configuration, where the application name matches with the WAR file name.

I also noticed that you are using microProfile-1.3 feature, which includes mpHealth-1.0, which is really old, and significant changes were made in the future microProfile releases, that improved functionality and fixed a lot of issues. Can you try to reproduce it using the latest WebSphere Liberty version 20.0.0.7 and microProfile-3.3 feature, which includes the improved mpHealth-2.2 feature? 

If you can reproduce it with the latest microProfile-3.3 feature, can you enable the following trace specification in your server.xml, reproduce the issue and attach the trace.log file in this issue?

`<logging traceSpecification="HEALTH=all"/>`

For more information on mpHealth-2.2: https://www.openliberty.io/docs/ref/general/?_ga=2.140741873.21673495.1594756670-1273048992.1592511777#health-check-microservices.html

**Comment by pgunapal** [comment] 2020-08-10 14:41
@kenji1bm Were you able to reproduce this issue with the latest MicroProfile feature?

**Comment by kenji1bm** [comment] 2020-08-10 16:29
@pgunapal Thank you for your comments. Sorry for the late reply.

We cannot upgrade the version of MicroProfile feature because our customer fixed their software requirements.

Now we're changing to not use MicroProfile Health endpoints to avoid the issue.

**Comment by pgunapal** [comment] 2020-08-10 17:36
@kenji1bm That is unfortunate to hear. I will close the issue for now, please feel free to open it again, if the issue occurs again with the latest MicroProfile feature.

**Closed by pgunapal** 2020-08-10 17:36 UTC
Labels: Needs member attention, team:Lumberjack
