### ISSUE TITLE
liberty-swagger-ui-d02953ea8a1cbb49e027.css not found

### ISSUE THREAD

**Issue by opaopa6969** [OpenLiberty/open-liberty#20764] opened 2022-04-11 06:35 UTC
**Describe the bug**  

liberty-swagger-ui-d02953ea8a1cbb49e027.css not found

when I open http://localhost:9080/openapi/ui/

**Diagnostic information:**  
 - OpenLiberty Version: generate JAVA17+JavaEE9.1 Microprofile5.0 via https://openliberty.io/start/
 - Java Version: openjdk version "17.0.2" 2022-01-18

regards,

**Comment by tevans78** [comment] 2022-04-11 08:34
This is a duplicate of https://github.com/OpenLiberty/open-liberty/issues/20310

**Closed as completed by tevans78** 2022-04-11 08:34 UTC
Labels: Needs member attention, release bug
