### ISSUE TITLE
Test Failure: io.openliberty.microprofile.health30.fat.DefaultOverallReadinessStatusUpAppStartupTest.testDefaultReadinessOverallStatusUpAtStartUpSingleApp

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#13864] opened 2020-09-10 13:56 UTC
RTC 277676

```
testDefaultReadinessOverallStatusUpAtStartUpSingleApp:junit.framework.AssertionFailedError: 2020-09-09-11:37:02:998 The Response Code was not 200 for the following endpoint: http://localhost:8010/health/ready expected:<200> but was:<503>
at io.openliberty.microprofile.health30.fat.DefaultOverallReadinessStatusUpAppStartupTest.testDefaultReadinessOverallStatusUpAtStartUpSingleApp(DefaultOverallReadinessStatusUpAppStartupTest.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)



```

**Comment by pgunapal** [comment] 2020-09-10 15:18
This was caused by PR https://github.com/OpenLiberty/open-liberty/pull/13218, which was later reverted, will continue to monitor the builds to see if it re-occurs.

**Comment by pgunapal** [comment] 2020-09-18 14:09
Closing, as the issues has not re-occurred again.

**Closed by pgunapal** 2020-09-18 14:09 UTC
Labels: team:Lumberjack
