### ISSUE TITLE
JakartaEE: Jakarta Bean Validation Support

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11855] opened 2020-04-20 21:44 UTC

**Comment by njr-11** [comment] 2020-04-20 21:55
Removed assignment. I will likely not be the person working on this from my team. I'm assigned to cover the build monitor responsibility this iteration.

**Comment by aguibert** [comment] 2020-07-28 17:31
Closing this as a duplicate of https://github.com/OpenLiberty/open-liberty/issues/11916

**Closed by aguibert** 2020-07-28 17:31 UTC
Labels: duplicate, jakartaEE, release:20009-beta, target:20009-beta
