### ISSUE TITLE
FAT Approval Test Summary for #9227

### ISSUE THREAD

**Issue by alvinso** [OpenLiberty/open-liberty#10039] opened 2019-12-05 16:15 UTC
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

The test cases are automated in new FAT "com.ibm.ws.install.featureUtility_fat" (https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat)

Test cases will verify the main functions i.e. "installFeatrure", "InstallServerFeatures", "viewSettings", ,"find", and "help" to ensure they are working as expected.  Also error scenarios are automated to verify that correct error messages are issued.

**InstallFeatureTest:**

testInstallFeature() - Verify that the feature is installed from Maven Central repository onto the Liberty runtime correctly.

testInstallAutoFeature() - Verify that the auto features are installed from Maven Central repository onto the LIberty runtime correctly.
	 
testBaseLicenseAccept()	- Verify that the WebSphere Liberty feature is installed from Maven Central repository onto Open Liberty runtime correctly.
	 
testMultiFeatureLicenseAccept() - Verify that the correct license and product files are laid down correctly when installing WebSphere Liberty features to Open Liberty runtime.

testFeatureLocalRepoOverride() 	 - Verify that the local Maven repository is overridden by featureUtility properties correctly.
	 
testInvalidFeature() - Verify that the expected error message is issued when installing feature with invalid feature name.

testAlreadyInstalledFeature() - Verify that the expected error message is issued when installing the feature that has been installed.

testInvalidMavenCoordinateArtifactId() - Verify that the expected message is issued when installing feature with invalid maven coordinate.
	 
testInvalidMavenCoordinateVersion()  - 	Verify that the expected message is issued when installing feature with invalid version in maven coordinate.
	 
testInvalidMavenCoordinatePackaging() - Verify that the expected message is issued when installing feature with invalid packaging id in maven coordinate.

testInvalidMavenCoordinateFormatting() - Verify that the expected message is issued when installing feature with invalid format in maven coordinate.

testBlankFeature() - Verify that the expected help message is issued when no feature is specified to installed

testSettingsValidationClean() - Verify that the featureUtility.properties is validated by the viewSettings action correctly.

testSettingsValidationInvalid() - Verify that the invalid featureUtility.properties is detected by the viewSettings action correctly

**InstallServerTest:**

testInstallBlankFeatures() - Verify that the correct message is issued when  no features are specified in server.xml

testAlreadyInstalledFeatures() - Verify that the feature is installed from server.xml correctly and correct message is issued when the feature is installed again.

testInstallAutoFeatureServerXml() - Verify that the auto features are triggerred to install from server.xml correctly.

**FindActionTest:**

testFindNoArgs() - Verify that all features available from configured Maven repository are listed correctly.

testFindOpenLibertyFeature() - Verify that the specified Open Liberty feature can be searched from the configured Maven repository

testFindClosedLibertyFeature() - Verify that the specified WebSphere Liberty feature can be searched from the configured Maven repository

testFindMultipleArgs() - Verify that the features can be searched by specified strings

testFindHiddenFeature() - Verify that the private features will not be searched and displayed during the search

**HelpActionTest:**

testHelp() - Verify that the general help message is displayed correctly

testHelpInstallFeature() - Verify that the help message for installFeature action is displayed correctly

testHelpInstallServerFeatures() - Verify that the help message for installServerFeatures action is displayed correctly

testHelpViewSettings() - Verify that the help message for viewSettings action is displayed correctly

testHelpFind() - Verify that the help message for find action is displayed correctly

testHelpHelp() - Verify that the help message for help action is displayed correctly

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

4

**Comment by sabolo** [comment] 2019-12-11 13:25
These new tests failed on Windows in the last SOE.  Defect 10079 was raised to cover this and it appears there is now a fix in integration.  Assuming this gets into a green release build by the time we launch the SOE on Friday, we should be able to verify this feature on Monday.

**Comment by ayoho** [comment] 2019-12-16 21:17
@alvinso Please consider making sure any work items related to this epic actually get linked to the epic (#9227). A wiki was created some time ago to document doing so - [Creating Stories and Features](https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Creating-Stories-and-Features). Having the appropriate links makes it significantly easier for reviewers (and your team, I would imagine) to track all the work that was done to support this feature and any outstanding issues that still need to be fixed.

It looks like https://github.com/OpenLiberty/open-liberty/pull/10079 didn't get merged into master in time for this past weekend's SOE run and https://github.com/OpenLiberty/open-liberty/pull/10117 only made it into master this morning. So looks like this will have to wait for next weekend's SOE before FAT approval can be considered again.

**Comment by alvinso** [comment] 2019-12-17 18:15
@ayoho fyi, both #10079 and #10117 are fixing the test case issues.

**Comment by sabolo** [comment] 2019-12-20 11:13
I have just checked the mini SOE that I kicked off to see if we could progress this feature.  Unfortunately I am seeing consistent failures on Windows caused by 270765.  Please can you look at this defect and see if you can progress its resolution.

**Comment by ayoho** [comment] 2020-05-18 18:33
All defects are addressed and coverage looks good to me. I'll go ahead and close this and approve the feature.

**Closed by ayoho** 2020-05-18 18:33 UTC
Labels: in:Install
