### ISSUE TITLE
openapi.scan.disable overrides servers.url

### ISSUE THREAD

**Issue by baztian** [OpenLiberty/open-liberty#4522] opened 2018-08-08 16:19 UTC
OpenLiberty 18.0.0.2 together with Microprofile OpenAPI automatically modifies the servers.url section  from

    servers:
    - url:

openapi.yml that I'm providing directly in META-INF folder to this unter /openapi

    servers:
    - url: nil

I've configured

    mp.openapi.scan.disable = true

in microprofile-config.properties.

(BTW my service runs on port 15080 but that shouldn't matter.)

This bug also has an effect in SwaggerUI as it uses the current url for the "Try it out" function if it is empty. With value `nil` that function doesn't work anymore.

My current work around is to set the url to `/`.

In my opinion OpenLiberty should not modify the openapi.yml at all unless any filters are in place.

**Comment by arthurdm** [comment] 2018-08-23 14:50
hi @baztian  - thanks for reporting this.  I agree that this value should have not changed.  We're currently looking into this and will post back shortly.

**Comment by arturdzm** [comment] 2018-08-27 15:08
Hi @baztian 
There are few things to note:

This is not valid snippet, since url is required field according to OAS 3.0 specification, and should be not null, empty or nil. They all mean no value

```
servers:
- url: nil
```
So if the user is providing their own server information, url has to be set.

`mp.openapi.scan.disable = true`, turns of JAX-RS annotations scanning. It doesn't affect static document processing. 

So in nutshell if the custom, non empty server url is provided ("\", "https://myhost.com") 
Liberty will use that. Otherwise, the port from httpEndpoint inside server.xml will be used.
Also in case where port is automatically selected, Liberty will try to use host/port from actual request to enable running behind reverse proxy.

**Comment by arturdzm** [comment] 2018-09-04 19:27
Closing this issue as I  think it is working as designed. Feel free to open again if needed.

**Closed by arturdzm** 2018-09-04 19:27 UTC
Labels: in:MicroProfile/OpenAPI
