### ISSUE TITLE
Feature Test Summary for Jakarta WebSocket 2.1

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21089] opened 2022-05-12 15:18 UTC
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* 

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by isaacrivriv** [comment] 2023-01-09 16:14
# WebSocket 2.1: #18745

**Repeated tests**: The bucket io.openliberty.wsoc.internal_fat has been enabled for repeat on EE10. Bucket com.ibm.ws.wsoc_fat on WS-CD-Open with dependencies on features and bundles in WS-CD-Open have been transformed to run with EE10. All tests have been set to repeat on EE10 including cdi-4.0 integration.

**New tests**: A new FAT bucket io.openliberty.wsoc.2.1.internal_fat has been added with specific tests for WebSocket 2.1. This functionality includes:

- WebSocket 2.1 removed restriction that endpoints can only be registered during the deployment of the web application. Test was added to confirm  this behavior.
- WebSocket 2.1 added API for client-side TLS configuration. Tests were added to verify this new TLS configuration.
- WebSocket 2.1 clarified zero or negative value disables the session idle timeout. Tests were added to verify this.
- WebSocket 2.1 clarified that once the container has identified a MessageHandler for a message, the MessageHandler is used for the entirety of the message irrespective of any subsequent changes to the MessageHandlers configured for the Session. No automated tests were added due to the time dependant nature of the feature. Manually confirmed.
- WebSocket 2.1 clarified the expected behaviour for Session.getRequestURI full URI should be returned. Tests was added to confirm this.
- WebSocket 2.1 added new method, ServerContainer.upgradeHttpToWebSocket() that allows a web application to programmatically dispatch a request to a WebSocket endpoint. Added test to verify new method functionality.
- WebSocket 2.1 clarified the expected handling of user properties. Tests were added to verify clarification.
- WebSocket 2.1 added a getter for the default platform configurator. No new method, just method that was exposed publicly. Added automated test for verifying method can be accessed.

**Manual tests**: One verification/change were done manually.
- Manually verified MessageHandler clarification due to the testing being time dependent. This was verified by creating a breakpoint in Eclipse to allow a Message Handler to be removed as a new request came in.

**Confidence**: 5 All feature tests have been passing with no EE10 failures since enabling the feature.

**Comment by ayoho** [comment] 2023-01-17 21:50
Tests appear to cover the points outlined in the UFO. Would love to see if there's a way to automate the MessageHandler behavior change. Same with the default platform configurator getter - even if it's just a trivial check, if it can be done in automation then it would be nice to have. I'm fine closing out this FTS, though.

**Closed as completed by ayoho** 2023-01-17 21:50 UTC
Labels: in:Transport, Feature Test Summary, team:Sirius, jakartaEE10

**Comment by isaacrivriv** [comment] 2023-01-25 18:35
Updated description to add additional automated test for new default platform configurator getter in #23965

**Comment by ayoho** [comment] 2023-01-26 16:36
Thank you, @isaacrivriv 👍
