### ISSUE TITLE
Pull in Jakarta Standard Taglib (Once Available) for JSP-3.0

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#12855] opened 2020-07-01 19:19 UTC
We will need not only the updates _org.apache.taglibs.standard_ classes, but also the TLDs below: 
﻿
<img width="329" alt="image" src="https://user-images.githubusercontent.com/5934310/86282729-c9f16c00-bbad-11ea-8b3a-99f750577b90.png">

They contain references to javax classes.  (see #12841) 

Additionally, the standard.jar that is included within com.ibm.ws.jsp should also reflect the new jakarta namespaces.

This means that the com.ibm.ws.jsp would need to be refactored to support the different files without the use of transformation. 

Latest Update is from 2015: https://tomcat.apache.org/taglibs/standard/

However, Github shows activity: https://github.com/apache/tomcat-taglibs-standard

**Comment by volosied** [comment] 2020-11-09 17:21
tomcat-taglibs-standard has moved to the jakarta namespace, but I don't see any official releases yet.

**Comment by isaacrivriv** [comment] 2021-02-08 14:50
Closing as duplicate of https://github.com/openliberty/open-liberty/issues/15317

**Closed by isaacrivriv** 2021-02-08 14:50 UTC
Labels: in:Web Components, jakartaEE, team:Sirius
