### ISSUE TITLE
Bindings and extensions name validation is not performed when there is no application descriptor

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#15767] opened 2021-02-02 00:30 UTC
Was: NPE occurs when overriding an entry in the web-bnd

The NPE no longer occurs.  However, validation of the web binding module name is no longer performed when there is no application descriptor.  (The name validation does not yet have the list of module names, which is computed when there is no application descriptor. This is a current limitation.  Whether the computed module names can be used by the binding name validation is not clear.)

**Describe the bug**
A NPE happens when overriding an application with ibm-web-bnd.xml
```
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application app. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.NullPointerException: Cannot invoke "com.ibm.ws.javaee.dd.app.Application.getModules()" because "app" is null
```

**Steps to Reproduce**
apps/app.ear.xml:
```xml
<archive>
    <archive targetInArchive="/app1.war">
        <file targetInArchive="/WEB-INF/ibm-web-bnd.xml"
         sourceOnDisk="/tmp/app/WEB-INF/ibm-web-bnd.xml" />
    </archive>

    <archive targetInArchive="/app2.war">
        <file targetInArchive="/WEB-INF/ibm-web-bnd.xml"
         sourceOnDisk="/tmp/app/WEB-INF/ibm-web-bnd.xml" />
    </archive>
</archive>
```
/tmp/app/WEB-INF/ibm-web-bnd.xml:
```xml
<web-bnd
   xmlns="http://websphere.ibm.com/xml/ns/javaee"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://websphere.ibm.com/xml/ns/javaee http://websphere.ibm.com/xml/ns/javaee/ibm-web-bnd_1_0.xsd"
   version="1.0">
   <resource-ref name="jdbc/conn" binding-name="defaultConnection" />
</web-bnd>
```
server.xml:
```xml
    <enterpriseApplication location="${server.config.dir}apps/app.ear">
        <web-bnd moduleName="app2">
            <resource-ref name="jdbc/conn" binding-name="newConnection" />
        </web-bnd>
    </enterpriseApplication>
```

**Expected behavior**
Not having the NPE

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.1

**Additional context**
This error looks very similar to this one: https://github.com/OpenLiberty/open-liberty/issues/6590
And I guess the correction will be very similar to this one: https://github.com/OpenLiberty/open-liberty/pull/6605

Maybe @tbitonti can have a look?

**Comment by Thihup** [comment] 2021-06-28 13:10
I could copy the changes made from WebExtAdapter.java to WebBndAdapter.java, but I guess I would need to sign the CLA in this case.

**Comment by tbitonti** [comment] 2022-07-11 17:56
Duplicate of issue #19510.

**Closed by tbitonti** 2022-07-11 17:56 UTC
Labels: bug, in:Kernel/Bootstrap, Needs member attention
