### ISSUE TITLE
18.0.0.2 CWWKZ0002E: NoClassDefFoundError: javax/ws/rs/core/Application

### ISSUE THREAD

**Issue by mikekuzak** [OpenLiberty/open-liberty#4399] opened 2018-07-31 13:46 UTC
HI .. 

I'm getting a strange exception when starting up the server. It looks like the microprofile is not loaded fully before the app starts. 

```
Launching defaultServer (Open Liberty 18.0.0.2/wlp-1.0.21.cl180220180619-0403) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181-b13 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKS4104A: LTPA keys created in 0.834 seconds. LTPA key file: /opt/ol/wlp/output/defaultServer/resources/security/ltpa.keys
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWPKI0803A: SSL certificate created in 1.574 seconds. SSL key file: /opt/ol/wlp/output/defaultServer/resources/security/key.jks
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-85bb5759f7-ffcmd:9080/openapi/
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application mcm-scheduler-gateway. The exception message was: java.lang.NoClassDefFoundError: javax/ws/rs/core/Application
[AUDIT   ] CWWKF0012I: The server installed the following features: [mpFaultTolerance-1.0, servlet-3.1, microProfile-1.3, ssl-1.0, jndi-1.0, mpHealth-1.0, federatedRegistry-1.0, appSecurity-2.0, jsonp-1.0, jaxrs-2.0, mpConfig-1.2, jaxrsClient-2.0, concurrent-1.0, jwt-1.0, mpRestClient-1.0, mpMetrics-1.1, opentracing-1.0, mpOpenTracing-1.0, mpJwt-1.0, ldapRegistry-3.0, json-1.0, mpOpenAPI-1.0, cdi-1.2, distributedMap-1.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
```

Server.xml has this: 

```
<server description="Java EE App Server">
	<featureManager>
		<feature>microProfile-1.3</feature>
		<feature>ldapRegistry-3.0</feature>
		<feature>appSecurity-2.0</feature>
	</featureManager>
```

After restarting the app it works. So it looks like an loading sequence issue.
Thanks for any advice.

**Comment by mikekuzak** [comment] 2018-08-01 10:33
Might be related to 
https://github.com/OpenLiberty/open-liberty/issues/4404

**Comment by andymc12** [comment] 2018-08-03 15:25
Yes, very likely.  I applied @aguibert 's fix from PR #4407 and have not been able to reproduce the NoClassDefFoundError for the `Application` class.  Can you give that patch a try to see if it works for you too?

**Comment by mikekuzak** [comment] 2018-08-06 15:10
I'm using this in my Docker container
`/repository/maven-central/io/openliberty/openliberty-runtime/$LIBERTY_VERSION/openliberty-runtime-$LIBERTY_VERSION.zip`

What's the URL to test the new build ? 
Thanks

**Comment by aguibert** [comment] 2018-08-06 15:18
@mikekuzak you can try out one of the nightly builds out on openliberty.io, which should contain the fix from #4407.  Try this URL:
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-08-06_1418/openliberty-all-18.0.0.3-20180806-1301.zip

**Comment by mikekuzak** [comment] 2018-08-06 16:38
scaled up to 4 pods .. looks good to me: 

`Launching defaultServer (Open Liberty 18.0.0.3/wlp-1.0.22.20180806-1301) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181-b13 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKS4104A: LTPA keys created in 0.952 seconds. LTPA key file: /opt/ol/wlp/output/defaultServer/resources/security/ltpa.keys
[AUDIT   ] CWPKI0803A: SSL certificate created in 1.166 seconds. SSL key file: /opt/ol/wlp/output/defaultServer/resources/security/key.jks
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://app-scheduler-gateway-698c8cb65f-j88z2:9080/schedulergateway/
[AUDIT   ] CWWKZ0001I: Application mcm-scheduler-gateway started in 4.480 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [mpFaultTolerance-1.0, servlet-4.0, microProfile-1.3, ssl-1.0, jndi-1.0, cdi-2.0, mpHealth-1.0, appSecurity-3.0, jaxrs-2.1, mpRestClient-1.0, mpMetrics-1.1, mpOpenTracing-1.0, federatedRegistry-1.0, jsonp-1.1, mpConfig-1.2, jaxrsClient-2.1, el-3.0, concurrent-1.0, jwt-1.0, opentracing-1.0, mpJwt-1.0, ldapRegistry-3.0, json-1.0, mpOpenAPI-1.0, distributedMap-1.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.`

**Comment by aguibert** [comment] 2018-08-06 17:54
Thanks for confirming @mikekuzak, going to close out this issue as a duplicate of #4404

**Closed by aguibert** 2018-08-06 17:54 UTC
Labels: duplicate, in:Application Services, in:JAX-RS, release bug
