### ISSUE TITLE
Liberty server stops when removing application from dropins directory

### ISSUE THREAD

**Issue by nstewart0206** [OpenLiberty/open-liberty#7571] opened 2019-05-20 22:24 UTC
**Describe the bug**
When an application is removed from the dropins directory while the server is started, the server stops

**To Reproduce**
1. Install Open Liberty 19.0.0.4
1. Add an application to the dropins directory
1. After the liberty server has started the application successfully, remove the application from the dropins directory

**Expected behavior**
Application is successfully removed from the liberty server and the server is still running

**Comment by hibell** [comment] 2019-05-23 02:45
I am not able to figure out the issue, but seeing this in the trace:
```
[5/22/19 22:33:10:619 EDT] 00000060 id=e32c1546 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  > bundleChanged Entry
[5/22/19 22:33:10:628 EDT] 00000060 id=e32c1546 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  > quiesceListeners Entry
[5/22/19 22:33:10:629 EDT] 00000060 id=e32c1546 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  > isServer Entry
[5/22/19 22:33:10:629 EDT] 00000060 id=e32c1546 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  < isServer Exit
[5/22/19 22:33:10:629 EDT] 00000060 id=00000000 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  A CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
```

Attached logs and sample app that reproduces the issue.
[logs_and_sample.zip](https://github.com/OpenLiberty/open-liberty/files/3210067/logs_and_sample.zip)

**Comment by jhanders34** [comment] 2019-06-03 02:58
There are two threads doing work.  One to stop the application:  0000002a and one that is stopping the server:  00000060.  00000060 shows that it detects that a bundle was changed from best I can tell.  the bundle it is detecting that changed is org.eclipse.osgi_3.13.300.cl190420190419-0642 [0] I believe from the below trace in the files you provided:

[5/22/19 22:33:10:619 EDT] 00000060 id=e32c1546 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  > bundleChanged Entry  
                                                                                                               org.osgi.framework.BundleEvent[source=org.eclipse.osgi_3.13.300.cl190420190419-0642 [0]]
com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  > quiesceListeners Entry

**Comment by garypicher** [comment] 2019-06-03 13:29
@nstewart0206 Has this worked on a prior fixpack using this same application?

**Comment by nstewart0206** [comment] 2019-06-03 18:12
@garypicher I believe it was working on 19.0.0.1 but I'm not 100% sure.  I don't know about 19.0.0.2 or 19.0.0.3.

**Comment by shighbar** [comment] 2019-06-04 13:44
I'm not certain if this is a regression or not. The issue happens in the CTS setup we have and I suspect there is something specific to the environment or to the fact that we use the mvn OpenLiberty as the issue does not occur out of the box with initial testing.

**Comment by brenthdaniel** [comment] 2019-06-05 19:03
By design, application clients will stop the server when they stop. This has been the case since the application client feature was introduced in 2015, so I'm removing the regression tag. 

As for the issue itself, there are a couple of ways to handle it. One would be to not allow application clients to be started as part of a server process. However, that could be a breaking change if anyone is doing this today.  Another solution would be to avoid shutting down the process when the client is being run as part of the server process.

**Comment by NottyCode** [comment] 2019-07-30 15:21
Decision is that we should stop calling System.exit when the client apps end in a server process. 

This should go to a vote of the product owner committee since it could possibly break someone if they were depending on updating an app to stop the server, but it seems unlikely

**Comment by hlhoots** [comment] 2019-09-09 18:17
Closing out..Fixed here: https://github.com/OpenLiberty/open-liberty/pull/8509/

**Closed by hlhoots** 2019-09-09 18:17 UTC
Labels: design-issue, in:Application Services, release bug
