### ISSUE TITLE
UUID as primary key when using Jakarta Data fails

### ISSUE THREAD

**Issue by ivargrimstad** [OpenLiberty/open-liberty#26659] opened 2023-10-19 10:39 UTC
**Describe the bug**  
When using UUID as a primary key throws an exception when used with Jakarta Data.

ivar@lanhost44 ~ %  echo -n '{"message":"Hello from Duke", "name":"Duke"}' | http post :9080/dukes-data/api/greetings
HTTP/1.1 500 Internal Server Error
Connection: Close
Content-Language: en-SE
Content-Length: 86
Content-Type: application/json
Date: Thu, 19 Oct 2023 10:34:32 GMT

java.lang.IllegalArgumentException: Source object is not an instance of java.util.UUID

**Steps to Reproduce**  
Steps to reproduce the bug

```
@Repository
public interface GreetingRepository extends CrudRepository<Greeting, UUID>{}
```

```
@Entity
public class Greeting {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    //... rest of class
}
```
```
@Path("/greetings")
public class GreetingResource {

    @Inject
    GreetingRepository greetingRepository;

    @POST()
    @Consumes(MediaType.APPLICATION_JSON)
    public Response addGreeting(Greeting greeting) {
        return Response.ok("Created greeting: " + greetingRepository.save(greeting).getId().toString()).build();
    }
}
```

**Expected behavior**  
The entity is stored in the database.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.11-beta
 - Affected feature(s): data-1.0
 - Java Version: 
openjdk version "21" 2023-09-19 LTS
OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode)

 - server.xml configuration (WITHOUT sensitive information like passwords)
```
<server description="Dukes Data Demo">
    <featureManager>
        <feature>restfulWS-3.1</feature>
        <feature>jsonb-3.0</feature>
        <feature>cdi-4.0</feature>
        <feature>persistence-3.1</feature>
        <feature>data-1.0</feature>
    </featureManager>

    <library id="jdbcLib">
        <fileset dir="jdbc" includes="*.jar"/>
    </library>

    <dataSource  id="DukesDataSource">
        <jdbcDriver libraryRef="jdbcLib"/>
        <properties serverName="localhost" portNumber="3306"
                    databaseName="dukes_data"
                    user="duke"
                    password="***"/>
    </dataSource>

    <databaseStore id="defaultDatabaseStore" createTables="true" dropTables="true"
                   tablePrefix="" dataSourceRef="DukesDataSource"/>
</server>
```

**Additional context**  
A complete working version using Long as the primary key can be found here:
https://github.com/ivargrimstad/dukes-data

**Comment by njr-11** [comment] 2023-10-19 13:16
Hi Ivar - thanks for reporting this!  I think Open Liberty currently has just one automated test using UUID with Jakarta Data (which is working in that particular scenario).  We will look into reproducing your scenario and see what updates are needed.  I'm going to switch the `release bug` label to `bug` because Jakarta Data is beta function, which is just a formality.  Either way, we want to get it working.

**Comment by njr-11** [comment] 2023-10-19 21:10
After trying it out, it looks like an issue in EclipseLink that I also ran into earlier this year #24925 . This will require a fix from EclipseLink to be brought into Open Liberty.

**Comment by Riva-Tholoor-Philip** [comment] 2024-03-12 02:51
PR# [27872](https://github.com/OpenLiberty/open-liberty/pull/27872) is merged

**Closed as completed** 2024-03-12 12:41 UTC
Labels: bug, in:JPA, team:Blizzard, Needs member attention
