### ISSUE TITLE
EclipseLink: ClassCastException for Boolean-Typed JPS-Query

### ISSUE THREAD

**Issue by bmhm** [OpenLiberty/open-liberty#14457] opened 2020-10-13 05:56 UTC
Dear Liberty Team,

**Describe the bug**

I found out that such a statement is broken with eclipseLink:
Create a typed query with `Boolean` as type and call `getSingleResult()`. It will result in a class cast exception instead.

**Steps to Reproduce**

```java
final EntityManager em = getEntityManager();
final TypedQuery<Boolean> query = em.createQuery(
  "select case when (count(pdo.field) > 0) then true else false end "
    + "from MyTableEntity pdo "
    + "where pdo.field = '__'", Boolean.class);
final Boolean singleResult = query.getSingleResult();
```

**Expected behavior**

`singleResult` becomes `Boolean.TRUE` or `Boolean.FALSE`

**Actual behaviour**

`java.lang.ClassCastException: java.lang.Integer incompatible with java.lang.Boolean`

**Known Workarounds**

Use Hibernate using jpaContainer or do not use select case.

**Diagnostic information:**

 - OpenLiberty Version: any, tested on 20.0.0.7 and 19.0.0.12
 - Java Version: Java 8 (OpenJ9  Java 8 build 232)
 - server.xml 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">
  <featureManager>
    <feature>jpa-2.2</feature>
  </featureManager>

  <dataSource type="javax.sql.Datasource">
  </dataSource>
</server>
```

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

FFDCs will be added later. I will create a test case and upload it into my github repository later today.

// Edit:
https://github.com/bmhm/OpenLiberty-jpa-14457

**Additional context**

1. JPA specification violated.
2. As this happens in the runtime, it will result in system outages.

**Comment by dazey3** [comment] 2020-10-14 02:08
Hello!
Thank you for supplying a simple test that helps to reproduce the failure on EclipseLink! I was able to use the sample provided to reproduce the failure. Looking at the EclipseLink trace while executing the query, we can see why it is failing:
```
[EL Fine]: sql: 2020-10-13 20:20:09.067--ServerSession(-1255592208)--Connection(-497420121)--Thread(Thread[main,5,main])--SELECT CASE  WHEN (COUNT(FIELD) > 0) THEN 1 ELSE 0 END FROM mytable WHERE (FIELD = 'hello')
```
It appears that EclipseLink is translating the boolean values in the JPQL query into integer values! In fact, the reason for this is behavior is fairly straightforward and easy to see in the EclipseLink code: 
https://github.com/eclipse-ee4j/eclipselink/blob/master/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java#L420-L426

I was able to find some existing EclipseLink bugs that appear to be encountering this same issue:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=545384
https://bugs.eclipse.org/bugs/show_bug.cgi?id=462663
However, this implementation of converting Boolean -> Integer values has been in EclipseLink for 13 years ever since the code was ported over from TopLink. I'm going to have to investigate some more to determine what the correct fix is here.

**Comment by bmhm** [comment] 2020-10-14 07:39
Hi Will,

good catch! Yes, those issues do seem related!

The first eclipse bug might get fixed by modifying `HANAPlatform.java`, overwriting the `appendBoolean()` you cited.

For the underlying issue, I suspect this code should be a bit smarter:
https://github.com/eclipse-ee4j/eclipselink/blob/master/jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryImpl.java#L530-L546

The result is taken "as is" (1 or 0 in this case). If you would want to keep the "1" and "0" for Oracle and other platforms, you could also track which result columns are being converted by "appendBoolean". However, "appendBoolean" has no knowledge of why it was called – inside a SELECT or inside a WHERE clause. So keeping track of which output value got converted might be a bit complicated.

On the other hand, if there is a "select case" visitor, this one might want to skip the "appendBoolean" method.

But all in all, if you can change the "append boolean" method to "true" and "false", this would help a lot. You can do this in e.g. all oracle platforms, HANAPlatform (as per your first linked eclipselink bug) and probably in most others. But as the query changes and people might relay on side effects, this is hard stuff as well which at least needed a kill switch (e.g. -Declipselink.oldbooleanbehaviour or persistence.xml-setting or similar).

You source code hint also helps to find workarounds. Actually with this knowledge, it is quite easy:

```java
    public Boolean hasFieldValue(final String content) {
        final EntityManager em = this.getEntityManager();
        final TypedQuery<Integer> query = em.createQuery("select case when (count(pdo.field) > 0) then true else false end "
                        + "from MyTableEntity pdo "
                        + "where pdo.field = :content",
                Integer.class);
        query.setParameter("content", content);

        return query.getSingleResult() == 1 ? Boolean.TRUE : Boolean.FALSE;
    }
```

That is not really readable (and not maintainable in large codebases without lots of comments), but it does work…

I am sorry I cannot help much more in this case besides that workaround. I will be OoF soon, but my colleagues will keep track of this case over at IBM’s site. 
Thanks for looking into it!

**Comment by dazey3** [comment] 2020-10-14 14:33
@bmhm 

> if you can change the "append boolean" method to "true" and "false", this would help a lot. You can do this in e.g. all oracle platforms, HANAPlatform (as per your first linked eclipselink bug) and probably in most others. But as the query changes and people might relay on side effects, this is hard stuff as well which at least needed a kill switch (e.g. -Declipselink.oldbooleanbehaviour or persistence.xml-setting or similar).

Yes, I think this may be the best solution. Since the 0/1 implementation has been around for so long, I think the best solution may not be to change that default behavior but instead add a persistence property that allows real Boolean values. I'm not thrilled with this fix, but it does have the huge benefit of not breaking customers that rely on this Integer implementation.

**Comment by dazey3** [comment] 2020-10-19 15:44
@bmhm 
Hello! I have created https://github.com/eclipse-ee4j/eclipselink/issues/922 to track fixing the issue in EclipseLink.

The solution I came up with was to convert the ResultSet value type back to Boolean after executing the SQL query. During JPQL parsing, EclipseLink rightly determines the return value of the CASE expression to be a Boolean type! However, this return value isnt being used as far as I can see. I added some logic that will convert the Integer value back to the expected Boolean type.

Unfortunately, I think the best way to enable this fix for EclipseLink 2.6 & 2.7 is to gate this behavior change with a persistence property that will need to be enabled to receive the fix. Since the ClassCastException is not from EclipseLink, but instead from the application, some customer applications may be written in a way to expect that an Integer value is returned, as a work around (though I agree that doesnt seem intuitive given the CASE expression). However, I will deliver this fix to EclipseLink master (3.0) without the gated property as this is a major update in the implementation. 

This persistence property is "eclipselink.allow-result-type-conversion". The default value is "false" for this property to preserve behavior.

**Comment by dazey3** [comment] 2020-10-29 15:06
@bmhm The fix for this issue has been delivered to Open Liberty. In order to enable the fix, you will need to set the EclipseLink persistence property:
```
    <property name="eclipselink.allow-result-type-conversion" value="true"/>
```
Can you verify the fix with your sample application?

**Comment by bmhm** [comment] 2020-10-29 19:50
Hi Will,

if the test from the PMR runs, it is fine for me! I will not be able to test it soon (i.e. within the next 3 weeks). And I probably will only run the same test case anyway.

Unrelated nit pick: The [bug label you removed](https://github.com/OpenLiberty/open-liberty/labels/bug) has the description "This bug is no present […]". I think a 't' is missing. ;-)

**Comment by dazey3** [comment] 2020-10-29 19:59
@bmhm 
Thank you for the reply. I can appreciate that it may take awhile for you to re-test and verify. I am monitoring the associated SalesForce case and will use the result of that testing as part of the verification; along with my own internal testing. Thank you for opening this issue as well!

Also, thank you for pointing out the spelling mistake in the description for that label. I have fixed it. If you notice any other mistakes like that, please point them out; I appreciate the help!

**Closed by dazey3** 2020-10-29 19:59 UTC
Labels: Needs member attention, in:JPA, release bug, team:Blizzard
