### ISSUE TITLE
Create Config 1.3 WAD

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#4295] opened 2018-07-17 14:03 UTC
This WAD includes all new features in MP Config 1.3 and server.xml as the dynamic config source.

**Comment by tevans78** [comment] 2018-07-17 14:17
duplicate of #4288

**Comment by tevans78** [comment] 2018-08-29 10:07
WAD is complete and all issues addressed. Closing.

**Closed by tevans78** 2018-08-29 10:07 UTC
Labels: team:MicroProfileUK
