### ISSUE TITLE
Remove STDOUT stacktrace hiding in containers, or provide way to disable it

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#10904] opened 2020-02-14 16:15 UTC
Liberty has a mechanism where it will hide many elements of the stack trace with `[internal classes]` in an effort to only show the most relevant parts of a stack trace to the application developer. 

For example:
```
 [ERROR   ] CWMRX1004E: The Reactive Messaging Kafka Outgoing Connector received an error. The error is io.smallrye.reactive.messaging.ProcessingException: Exception thrown when calling the method io.openliberty.guides.bar.BarResource#initBeverageOrder
 	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:50)
 	at [internal classes]
 Caused by: java.lang.reflect.InvocationTargetException
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:48)
 	... 1 more
 Caused by: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
 	... 16 more
```

## Problems:

1. When I develop applications on Liberty, this is often unhelpful because I have to go check the messages.log to see what is really going on.
2. As a developer of liberty trying to help users (such as on Stackoverflow) this is very cumbersome because users often only post the trimmed stack trace and I have to explain to them how to find messages.log and ask for the stack trace there.
3. As a user of Docker+Liberty, it is tedious to get messages.log out of a container, but it is very easy to get STDOUT/STDERR, which can easily be streamed to external sources such as logging services.

## ~Proposed solution A~

~Get rid of stack trace trimming in STDOUT/STDERR~

## Proposed solution B

Add an environment variable such as `WLP_TRIM_STACKTRACE=false` which can be used to easily disable stack trace trimming. Also, set this environment variable to `false` by default in the base docker images, so people don't need to fish messages.log out of docker containers.

**Comment by deboer-tim** [comment] 2020-03-03 16:29
A few comments:
1. This feature was put in because in general the stack trace output was bad. Embarrassingly unusable, 80+ line stack traces with multiple Caused by lines I need scrollbars bad. You might be seeing some that aren't that bad for certain exceptions, but I'd spend some time looking at problem determination usability of a variety of apps before changing any default.

2. If you need to open messages.log to understand a problem as a developer then by definition *something else is wrong*. Developers shouldn't need to know Liberty internals to use it, the error message is bad, or something else isn't getting out to the console... Don't get caught up thinking that exposing internal info is an easy or sole solution to any problem.

3. The console log with full stack traces is not equivalent to messages.log. If what you want for containers is streaming the log to sysout (which will likely be picked up by logging tools as well) then you should just do that instead.

**Comment by donbourne** [comment] 2020-03-04 16:37
I'm not sure this one has a perfect answer.  I agree mostly with Tim's point number one.  I also get the points you're making @aguibert .  The original assumption, when Liberty was first created, was that we're better to error on the side of usability in this case than full disclosure.  

IMO we'd only want to do something about this if we think it's significantly more likely that developers need the full stack trace than that they are fine with the trimmed one -- otherwise changing this might just annoy as many people as it helps.  Is there any way for us to find out if developers find the trimmed stacks annoying?

**Comment by gcharters** [comment] 2020-03-04 16:55
I tend to agree with Tim's view and every time we need to resort to a stack trace, we should be considering how to improve the error messages.  There have been a few cases where I've asked for message changes/improvements once I've got to the bottom of a problem where maybe I needed to trawl messages.log.

My current feeling is I would not want this changing by-default, to output full stack traces as I think, whilst it might provide all the info needed, it will also add a lot of noise and lead to people not seeing the wood for the trees.  If we do anything here, I think having an option to turn on full traces might be acceptable.

**Comment by aguibert** [comment] 2020-03-04 19:57
I can agree that for bare-metal Liberty instances there isn't sufficient evidence to change our default behavior for stack trace trimming, so we can set aside option (A) in the OP.

I'd like to refocus this issue on how the stack trace trimming impacts problem determination in Docker environments. Suppose I need to reference the full stack trace 1 out of every 20 stack traces I look at as an application developer. For bare-metal it's not too difficult to dip into messages.log, but on docker envrionments it is significantly more complicated and the cost/benefit goes way out of balance.

I like @deboer-tim 's suggestion in (3) to pipe messages.log to STDOUT instead of console.log. Is there a simple way we could set that option in an environment variable or something?

**Comment by yeekangc** [comment] 2020-03-05 04:38
From a(n application) developer's standpoint, I only want to know what I need to know for my application and how I can fix the issue that I ran into.  Personally, when I first saw the trimmed stack trace, I thought that was nice.  Long unusable stack traces have never really been helpful.  Liberty isn't the only runtime/framework that does this either.

As stated above, if we need to resort to stack traces, +1 that we should look to improve the error messages for all these occurrences.  In fact, I would even argue that Liberty should see how we can be smarter and return better/more relevant error messages and stack traces to developers.  (Another issue/epic to file here ...)

I am fine if we scope this to what makes sense in a containerized environment and improvements there.  Then, there will still be development scenarios vs non-development scenarios to consider.  Piping everything to STDOUT isn't necessary desirable for developers depending how they work.

**Comment by donbourne** [comment] 2020-03-05 12:58
In Docker scenarios we advocate that people use JSON logging to stdout.  That ensures that the downstream log analysis has the easiest to parse information already broken out neatly into fields.  I believe that for JSON logging we decided to NOT compress stacks, but I'll verify that.

**Comment by donbourne** [comment] 2020-03-05 13:16
see https://github.com/OpenLiberty/ci.docker#logging -- that's the guidance we give for running in Docker

**Comment by yeekangc** [comment] 2020-03-05 14:53
Thanks, Don.  That makes sense for production/deployment scenarios.

For (local) development scenarios, unless the tooling handles JSON logging, it won't be very useful.  Even if the tooling handles, Liberty will want to ensure that the tools surface what is relevant and necessary for application developers.

**Comment by donbourne** [comment] 2020-03-08 17:32
@aguibert , we should also be able to use messages.log format for the console.log once we complete https://github.com/OpenLiberty/open-liberty/issues/9884

**Comment by aguibert** [comment] 2020-03-11 21:12
thanks Don,  #9884 sounds like a good compromise. Just to be clear, when this function is enabled, we see full stack traces, right?

Also, I agree that we should be giving meaningful error messages in all cases, but in reality users hit error messages that the dev team hasn't come across or considered before, and for these situations the full stack trace (or at least nested exception messages) is needed.
Here is a specific instance of this problem that I ran into while working on MP Reactive Messaging: https://github.com/OpenLiberty/open-liberty/issues/11274

The error message I got in console.log was:
```
[ERROR   ] Unable to create the publisher or subscriber during initialization
java.lang.reflect.InvocationTargetException
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application kitchen. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException
```

But once I went and dug in messages.log for the nested exception it showed the real problem much more clearly:
```
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735)
	... 63 more
```

**Comment by donbourne** [comment] 2020-03-18 15:58
> thanks Don, #9884 sounds like a good compromise. Just to be clear, when this function is enabled, we see full stack traces, right?

Right, you'll see full stack traces

**Comment by donbourne** [comment] 2021-07-27 14:51
Closing this as I think the variety of output formats now available for the console output lets developers decide if they want the concise stack format or full stack output.

**Closed by donbourne** 2021-07-27 14:51 UTC
Labels: design-issue, enhancement
