### ISSUE TITLE
Annotation Liberty FAT Test corrections

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#3583] opened 2018-05-16 15:40 UTC
Problems to be fixed in new annotation fat tests, which were added with jandex support:

(1) Replacement of empty strings as messages in FAT assertions.
For example: 
/dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppTrueAppMgrTrueTest.java
    @Test // Line 112
    public void testUsingJandex() throws Exception {
        // Search for message indicating Jandex is being used.
        // CWWKC0092I: Read Jandex indexes for {0} out of {1} archives ({2} out of {3} classes) in {4}.
        List l = SHARED_SERVER.getLibertyServer().findStringsInLogs("CWWKC0092I");
        assertFalse("   ", l.isEmpty()); // The list should NOT be empty
    }

(2) Startup timer should be 120s (the preferred value), not 10s:
`SHARED_SERVER.getLibertyServer().waitForStringInLog("CWWKZ0001I.* TestServlet40", 10000);`

(3) Use LibertyServer instead of SharedServer (since the server is not shared across multiple test classes).

(4) Add the application for validation:
This is done by: `LibertyServer.addInstalledAppForValidation(String appName)`

**Comment by tbitonti** [comment] 2018-05-16 15:42
Tests are under:
dev/com.ibm.ws.anno_fat

**Comment by jimblye** [comment] 2018-05-16 19:34
What does addInstalledAppForValidation() do?

**Comment by jimblye** [comment] 2018-05-16 19:36
I have JandexApplicationHelper.addEarToServerApps( ...).   Maybe addInstalledAppForValidation() is a replacement for that?

**Comment by aguibert** [comment] 2018-05-16 19:43
all `addInstalledAppForValidation()` does is adds the application name to a list on the `LibertyServer` object so that `server.startServer()` blocks until it sees the "app XYZ started" message in logs (or blows up after some amount of time if that doesn't happen)

**Comment by jimblye** [comment] 2018-05-17 15:45
I removed the timeout.  The tests still fail, both in my PB and also locally.  I'm not sure what changed, but these all worked before.  I'll try replacing the SharedServer with LibertyServer, but I don't see how that matters.  Note also, the com.ibm.ws.webcontainer.servlet.4.0_fat has a 10-second timeout and apparently hasn't been an issue.  That's what I used as a model for the Jandex FATs.

java.lang.RuntimeException: componenttest.exception.TopologyException: Failures occured while waiting for app to start:
Application TestServlet40 failure: CWWKZ0014W: The application TestServlet40 could not be started as it could noot be found at location TestServlet40.ear.
at componenttest.topology.impl.LibertyServer.waitForStringInLog(LibertyServer.java:4547)
at com.ibm.ws.jandex.tests.JandexAppFalseAppMgrFalseTest.setUp(JandexAppFalseAppMgrFalseTest.java:79)
Caused by: componenttest.exception.TopologyException: Failures occured while waiting for app to start:
Application TestServlet40 failure: CWWKZ0014W: The application TestServlet40 could not be started as it could not be found at location TestServlet40.ear.
at componenttest.topology.impl.LibertyServer.validateAppLoaded(LibertyServer.java:1343)

at componenttest.topology.impl.LibertyServer.waitForStringInLog(LibertyServer.java:4542)

**Comment by jimblye** [comment] 2018-05-17 20:03
I found that I have to pass a timeout.  If I don't pass a timeout, the test fails in validateAppsLoaded() because it cannot find the app.    Possibly that is a timing issue?  But by passing in a timeout, we completely skip that code.

I pulled this into the test code:
 protected static final int LOG_SEARCH_TIMEOUT = FATRunner.FAT_TEST_LOCALRUN ? 12 * 1000 : 120 * 1000;

Then I do:

SHARED_SERVER.getLibertyServer().waitForStringInLog("CWWKZ0001I.* TestServlet40", LOG_SEARCH_TIMEOUT);

**Comment by aguibert** [comment] 2018-05-17 21:59
I don't think this could be a timing issue.  It doesn't make sense to me that you get this error:
> CWWKZ0014W: The application TestServlet40 could not be started as it could not be found at location TestServlet40.ear.

To be clear, you are still exporting the EAR to disk in addition to `addInstalledAppForValidation()` right?  The `addInstalledAppForValidation()` method will not build the app or export it to disk.  It's only a replacement for the `waitForStringInLog()` call.

I realize you asked this question earlier and I did not answer it directly:
> I have JandexApplicationHelper.addEarToServerApps( ...). Maybe addInstalledAppForValidation() is a replacement for that?

To answer that question -- no it is not a replacement.  You would need to call both methods, so I would recommend putting `addInstalledAppForValidation()` inside of `addEarToServerApps()` or something so you don't need to remember to call it everywhere.

**Comment by tbitonti** [comment] 2018-05-18 15:17
What makes it seem to be a timing issue is where the message is emitted.  A call to 'findFile' seems to be necessary to assign into _file or _container, but the message code path doesn't call 'findFile':

ResolveFileAction: public void execute(ExecutorService executor) {
        File f = new File(_locAdmin.resolveString(_location));
        if (f.isAbsolute()) {
            resolve(_location, _filesToMonitor);
        } else {
            resolve(AppManagerConstants.SERVER_APPS_DIR + _location, _filesToMonitor);
            resolve(AppManagerConstants.SHARED_APPS_DIR + _location, _filesToMonitor);
        }
        _mon.setProperty(FileMonitor.MONITOR_DIRECTORIES, _filesToMonitor);
        _mon.setProperty(FileMonitor.MONITOR_FILES, _filesToMonitor);

        if (_trigger == UpdateTrigger.DISABLED) {
            findFile(true);
        } else {
            _mon.register(_ctx, FileMonitor.class, this);
            if (_container.get() == null) {
                if (_file.get() == null) {
                    if (!FrameworkState.isStopping()) {
                        // Don't issue this message if the server is stopping
                        **AppMessageHelper.get(_handler.get()).warning("APPLICATION_NOT_FOUND", _name, _location);**
                    }
                }
            }
        }
    }

**Comment by jimblye** [comment] 2018-07-19 16:18
Fixed in pull request #3268

**Closed by jimblye** 2018-07-19 16:18 UTC
