### ISSUE TITLE
Test Failure: org.eclipse.microprofile.metrics.tck.MeterTest.testRates

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6400] opened 2019-02-05 15:13 UTC
RTC 260682

```
testRates
java.lang.AssertionError: expected:<100.0> but was:<114.33062621147577>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:443)
at org.junit.Assert.assertEquals(Assert.java:512)
at org.eclipse.microprofile.metrics.tck.TestUtils.assertEqualsWithTolerance(TestUtils.java:41)
at org.eclipse.microprofile.metrics.tck.MeterTest.testRates(MeterTest.java:95)
```

RTC 268568
```
testRate:java.lang.AssertionError: expected:<1.0> but was:<1.1203899899654197>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:443)
at org.junit.Assert.assertEquals(Assert.java:512)
at org.eclipse.microprofile.metrics.tck.TestUtils.assertEqualsWithTolerance(TestUtils.java:41)
at org.eclipse.microprofile.metrics.tck.TimerTest.testRate(TimerTest.java:107)
```

**Comment by Erikkre** [comment] 2019-02-25 20:21
Closed as non-reocurring.

**Comment by fmhwong** [comment] 2019-07-17 15:05
RTC defect has been reopened

**Comment by Erikkre** [comment] 2019-08-08 19:08
Closed as infrequent, occurs around every 6 months.

**Comment by kabicin** [comment] 2019-11-14 16:53
Closed as non-reproducible. When testing, stressing the JVM causes the testRates value to less than 100 rather than increasing to the failing ~114. It seems that decreasing Thread.sleep(1000) in the meter/timer test ticks by 12% for OpenJDK 11.0.2, and 14% for SUNJDK8 simulates the results close to the failures. There is so far a trend that the time discrepancy is related to Java version and only fails on Windows machines from test runs on different dates.

**Comment by fmhwong** [comment] 2020-10-13 20:21
Re-open and see if there is a way to fix this in the TCK.

**Comment by donbourne** [comment] 2020-10-22 13:47
looks like people in MicroProfile Metrics are ok with us adjusting the tolerance of this test. Note that from the description there are multiple places that may need to be adjusted in testRates to fix this problem.  Please also check to see, from past reports of this problem, what level of tolerance would fix all of the previously reported cases.

**Closed** 2020-11-09 16:38 UTC
Labels: team:Lumberjack
