### ISSUE TITLE
Port com.ibm.ws.jaxws.clientcontainer_fat_lwas into Open-Liberty

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#7023] opened 2019-03-25 20:36 UTC
Currently the jaxws-2.2 fat bucket that tests the Client Container component of the feature is not in Open-Liberty. The com.ibm.ws.jaxws.client_fat needs to moved over. 

Steps to port:

- [ ] Move com.ibm.ws.jaxws.clientcontainer_fat to OL
- [ ] Update references and copy-write headers
- [] Update FAT test apps to be built with the OL test framework
- [ ] After delivering the OL com.ibm.ws.jaxws.ejb_fat remove com.ibm.ws.jaxws.ejb_fat from CL

**Comment by BerksanAtes** [comment] 2019-07-30 16:43
Duplicate of #7429

**Closed by BerksanAtes** 2019-07-30 16:43 UTC
Labels: in:Web Services, team:Bobcats
