### ISSUE TITLE
binaryLog fileSwitchTime option not creating new messages.log file - z/OS Connect EE 

### ISSUE THREAD

**Issue by alanh-ibm-uk** [OpenLiberty/open-liberty#18162] opened 2021-08-12 17:00 UTC
Hello,
I am using z/OS Connect EE V3 which is based on Liberty for z/OS 21.0.0.6.
In bootstrap.properties I have 
websphere.log.provider=binaryLogging-1.0
com.ibm.hpel.log.fileSwitchTime=16
com.ibm.hpel.log.bufferingEnabled=true
com.ibm.hpel.log.outOfSpaceAction=PurgeOld
I then start the server with --clean option, run a workload, and force messages to appear in the binary message log .wbl file after 3pm and 4pm and 5pm. However, a new .wbl file is not created after 4pm, and all messages are appended to the one .wbl file created when the server started.
I have obtained a server dump, as requested by Prashanth Gunapalasingam @pgunapal

**Comment by alanh-ibm-uk** [comment] 2021-09-08 16:16
Hello, has there been any progress on this? 
Thanks, Alan.

**Comment by pgunapal** [comment] 2021-09-08 17:48
Still a work in progress, trying to reproduce it on a z/OS machine. As noted in our Slack conversations, we are unsuccessful in reproducing it on a distributed platform. Will update the issue, with our status soon.

**Comment by pgunapal** [comment] 2021-09-21 16:03
@alanh-ibm-uk I wasn't able to reproduce it on z/OS machine as well, as a new `.wbl` file was created for the incoming new message as soon as the configured `fileSwitchTime` elapsed. From the server dump, there are alot of server config files, making it difficult to diagnose. In order to progress on this, would it be possible to reproduce this issue with a simple server (no applications or features configured) and just enable the following in the bootstrap.properties file? Note: 
`websphere.log.provider=binaryLogging-1.0`
`com.ibm.hpel.log.fileSwitchTime=16`

In order to generate new messages, once the configured `fileSwitchTime` elapses, you can edit the server.xml file and add a trace specification or something as follows, to trigger a new message to be logged, which should create a new `.wbl` file.
`<logging traceSpecification="com.ibm.ws.logging.hpel.impl.*=fine/>`

Please send us the new log/server.xml files and tell us the time you triggered the new message to appear.

Note: Its best to create a brand new server to do the above testing.

**Comment by alanh-ibm-uk** [comment] 2021-09-30 18:14
Hello Prashanth, I ran this as requested using a new z/OS Connect EE server (using Liberty 21009). The problem still occurs and a second .wbl is not created after the fileSwitchTime should have triggered one.
My bootstrap.properties just contains:
websphere.log.provider=binaryLogging-1.0
com.ibm.hpel.log.fileSwitchTime=19
My server.xml has:
<logging traceSpecification="com.ibm.ws.logging.hpel.impl.*=fine"/>
I started my server just before 7pm (19:00), and a .wbl was created. However, after 7pm a second .wbl was not created.
As you can see from the job log, the timestamp has moved from 18:00 to 19:00
18.08.40 STC38395 ---- THURSDAY,  30 SEP 2021 ----                                    
18.08.40 STC38395  IEF695I START ZOSCONN  WITH JOBNAME ZOSCONN  IS ASSIGNED TO USER CT
18.08.40 STC38395  $HASP373 ZOSCONN  STARTED                                          
                   J E S 2  J O B  L O G  --  S Y S T E M  M V 2 2  --  N O D E  W I N
                                                                                      
18.08.40 STC38395 ---- THURSDAY,  30 SEP 2021 ----                                    
18.08.40 STC38395  IEF403I ZOSCONN - STARTED                                          
18.08.44 STC38395  +CWWKE0001I: The server server1 has been launched.                 
18.08.48 STC38395  +CWWKF0011I: The server1 server is ready to run a smarter planet. T
   361              server1 server started in 4.132 seconds.                          
19.10.46 STC38395  +CWWKB0004I: Refresh command completed successfully.               
19.10.46 STC38395  +CWWKB0005I: COMMAND RESPONSES COMPLETED SUCCESSFULLY FROM zcon.   
19.10.46 STC38395  +CWWKB0002I: MODIFY COMMAND ZCON,REFRESH COMPLETED SUCCESSFULLY.   

My server.xml is simply this:
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

<logging traceSpecification="com.ibm.ws.logging.hpel.impl.*=fine"/>

    
    <featureManager>
        <feature>zosconnect:zosConnect-2.0</feature>
        <feature>zosconnect:zosConnectCommands-1.0</feature>
    </featureManager>

    
    <httpEndpoint id="defaultHttpEndpoint"
                  host="*"
                  httpPort="9080"
                  httpsPort="9443" />
                  
                      
    <cors id="defaultCORSConfig"
          domain="/"
          allowedOrigins="*"
          allowedMethods="GET, POST, PUT, DELETE, OPTIONS"
          allowedHeaders="Origin, Content-Type, Authorization, Cache-Control, Expires, Pragma"
          allowCredentials="true"
          maxAge="3600"/>


	
	<config updateTrigger="mbean" monitorInterval="500"/>
	
    <zosconnect_zosConnectManager setUTF8ResponseEncoding="true"/>

    
    <zosconnect_zosConnectAPIs updateTrigger="disabled" pollingRate="5s"/>	
	
    
	<zosconnect_services updateTrigger="disabled" pollingRate="5s"/>

	
	<applicationMonitor updateTrigger="disabled" dropinsEnabled="false"/>
    
</server>

**Comment by pgunapal** [comment] 2021-10-04 15:51
HI @alanh-ibm-uk, would you mind, reproducing it on a plain simple server, without any features configured, such as no zosConnect features enabled 
`<feature>zosconnect:zosConnect-2.0</feature> <feature>zosconnect:zosConnectCommands-1.0</feature>`

We want to see if its reproducible using the simplest configuration possible, so its easier to diagnose and narrow down to the root cause, as I was unable to reproduce it using a plain simple server on z/OS. 

Again, in order to generate new messages, once the configured `fileSwitchTime` elapses, you can edit the server.xml file and add a trace specification or something as follows, to trigger a new message to be logged, which should create a new `.wbl ` file.
`<logging traceSpecification="com.ibm.ws.logging.hpel.impl.*=fine/>`

Please send us the new log/server.xml files and tell us the time you triggered the new message to appear.

Note: Its best to create a brand new server to do the above testing.

**Comment by alanh-ibm-uk** [comment] 2021-10-06 14:30
Hi @pgunapal , I have created a new Liberty server without any z/OS Connect EE features, and added the logging traceSpecification you suggested. 
The server.xml has:
<server description="LibServer">
    
    <featureManager>
        <feature>servlet-3.0</feature>
    </featureManager>
    <logging traceSpecification="com.ibm.ws.logging.hpel.impl.*=fine"/>
</server>
The bootstrap.properties has:
websphere.log.provider=binaryLogging-1.0
com.ibm.hpel.log.fileSwitchTime=10
I started the server at 9.56 (which appears at 8.56 GMT) but even after leaving the server running for 6 hours, a new file is not created. I tried to trigger a message by updating the server.xml adding a JSON feature and issuing a MODIFY REFRESH command, but this did not cause a new file to be created.
Trace file:
[binTrace.txt](https://github.com/OpenLiberty/open-liberty/files/7294815/binTrace.txt)
Two thoughts:
- paths? does Liberty expect specific paths to be used?
- timezone? I'm using GMT.

**Comment by pgunapal** [comment] 2021-10-14 14:24
Hi @alanh-ibm-uk, i took another look at our code and the file switching happens in the following [LogRepositoryWriterImpl.enableFileSwitch()](https://github.com/OpenLiberty/open-liberty/blob/24d8953853f3c5d66e4ae9482a5b9682b640a65e/dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/hpel/impl/LogRepositoryWriterImpl.java#L260) method, where it uses a Timer Daemon to schedule the file switching. From all my local testing, i have been using the same timezone that is on the system the Liberty server is started on and the configured hour in the fileSwitchTime reflects the same hour in the system's timezone. Is it possible to try with the same timezone throughout the test?

For the paths, i have been using the default paths that are configured in Liberty (`/usr/servers/log/logdata`). Are you using different paths?

Can you try setting the `com.ibm.hpel.trace.fileSwitchTime` as well in the bootstrap.properties file and set an hour for both log and trace fileSwitchTime that is later than the time you started the server and 5 minutes after the fileSwitchTime is reached, please try updating your server.xml, and ensure you save it. Please send us all the logs and server.xml (including logdata/tracedata) for further investigation and it would be good if you list the time stamps of the performed actions.

**Comment by alanh-ibm-uk** [comment] 2021-10-18 12:57
Hi @pgunapal , for z/OS Connect EE our default paths are /var/zosconnect/servers/<server name>
I wonder if this could be causing the problem?

**Comment by pgunapal** [comment] 2021-10-25 19:35
@alanh-ibm-uk Hmm, could be..., can you try using the default log path?

**Comment by alanh-ibm-uk** [comment] 2021-11-02 15:06
Hi @pgunapal , re. https://github.com/OpenLiberty/open-liberty/issues/18162#issuecomment-943409764 I assume you meant your default path of `/usr/servers/<server_name>/log/logdata`?
Unfortunately we don't have a servers directory under /usr, and I only have READ authority on this dir so cannot create a servers directory. 
Is it possible for you to try again (preferably on z/OS) but not use the default output directory? (server.output.dir) 
Thanks, Alan.

**Comment by pgunapal** [comment] 2021-11-17 15:25
Hi @alanh-ibm-uk, I had tried to reproduce the issue on z/OS, with the non-default output directory, where I set the `WLP_OUTPUT_DIR=/logsdir/test` in server.env, and I could not reproduce it. A new `.wbl` file is created once the hour set in the bootstrap.properties file for `fileSwitchTime` has passed and a new message was logged.

**Comment by pgunapal** [comment] 2022-01-21 16:42
Based on Slack discussions, Alan and I worked together on trying to reproduce this issue. Using a simple server without any features, the HPEL logs were rolled over and a new `.wbl` file was created. Using the `-listInstances` option, you will only see one instance, because by design, under the log data directory there is only one instance, even if there are multiple `.wbl` files. BinaryLogging works by repository instances, per server lifecycle. Within one server start/stop cycle, this is one instance, which is defined by the parent directory. Within that directory, there can be multiple `.wbl` files, but when you view the content, you will see everything at once, unless you filter it by time/date, loggers, and etc.

Closing this issue, as non-reproducible, and provided explanation on how binaryLogging works. Please re-open if the issue still persists on a z/OS Connect EE server.

**Closed as completed by pgunapal** 2022-01-21 16:42 UTC
Labels: bug, Needs member attention, team:Lumberjack
