### ISSUE TITLE
Improve feedback (avoid failure) when JAVA_HOME not set

### ISSUE THREAD

**Issue by deboer-tim** [OpenLiberty/open-liberty#21404] opened 2022-06-07 14:54 UTC
I'm using 22.0.0.5 on OpenJDK 17.0.3+7 on Mac M1. I used the Adoptium installer.

Starting a server that had been running fine on other machines (Linux, previous Macs) I got the following error:
`[ERROR   ] CWWKZ0002E: An exception occurred while starting the application X. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.WeldException: WELD-001524: Unable to load proxy class for bean Built-in Bean [javax.transaction.UserTransaction] with qualifiers [@Default] with class interface javax.transaction.UserTransaction`

While trying to figure out why this wouldn't work on my Mac I tried different versions of Liberty, reinstalled my JDK, and even created a new (empty) server, which failed on shutdown with:
```
[ERROR   ] CWWKE0701E: FrameworkEvent ERROR org.osgi.framework.BundleException: Exception in org.apache.aries.jndi.startup.Activator.stop() of bundle com.ibm.ws.org.apache.aries.jndi.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:890)
	at [internal classes]
Caused by: java.lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException: Unable to make field private static javax.naming.spi.ObjectFactoryBuilder javax.naming.spi.NamingManager.object_factory_builder accessible: module java.naming does not "opens javax.naming.spi" to unnamed module @bec3d62
	at org.apache.aries.jndi.startup.Activator.swapStaticField(Activator.java:271)
	... 1 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static javax.naming.spi.ObjectFactoryBuilder javax.naming.spi.NamingManager.object_factory_builder accessible: module java.naming does not "opens javax.naming.spi" to unnamed module @bec3d62
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.aries.jndi.startup.Activator.swapStaticField(Activator.java:262)
	... 1 more
 Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.org.apache.aries.jndi.core_1.1.64.cl220520220425-0301 [171]]
```

It turns out the underlying issue is that my JAVA_HOME wasn't set. Once I set it, everything works fine. No idea how long it would have taken me to figure this out if I hadn't texted an expert. :)

I'm assuming this is related to changing defaults when Java 11+ is detected, but this was totally not obvious as a user. Please consider adding a warning when JAVA_HOME is not set, changing the defaults (since using Java 11+ is becoming more common), finding a new way to detect - i.e. anything that would either make this work by default, or help the user understand why it is failing and how to fix it.

**Comment by kinueng** [comment] 2022-06-09 16:24
@deboer-tim was OK with me transferring this issue to the Open Liberty runtime repo.

**Comment by jhanders34** [comment] 2022-06-09 16:29
No this relates to how we determine what Java version is used to determine if we need to add --add-opens to the JVM arguments.  This is a duplicate of an existing issue:  https://github.com/OpenLiberty/open-liberty/issues/18412

**Comment by frowe** [comment] 2022-06-10 13:25
If it's a dup, why not close it?

**Comment by cbridgha** [comment] 2022-06-10 18:22
Closing as dup of https://github.com/OpenLiberty/open-liberty/issues/18412 - Also getting original's priority set asap.

**Closed as completed by cbridgha** 2022-06-10 18:22 UTC
Labels: Needs member attention
