### ISSUE TITLE
MP Config: Update to the latest versions of OSS before GA

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26618] opened 2023-10-16 16:36 UTC
Update to the latest versions of smallrye config and any other Open Source software that we consume for MP Config 3.1.

Can be done at any time but should be checked shortly before GA to ensure everything is up to date.

**Comment by tevans78** [comment] 2023-11-28 13:50
This is a duplicate of https://github.com/OpenLiberty/open-liberty/issues/26663
Closing this issue.

**Closed as completed by tevans78** 2023-11-28 13:50 UTC
Labels: in:MicroProfile/Config
