### ISSUE TITLE
Investigate failure of com.ibm.ws.fat.wc.tests.WCTrailersTest running locally

### ISSUE THREAD

**Issue by anupag** [OpenLiberty/open-liberty#12173] opened 2020-05-13 20:30 UTC
**Describe the bug**

When running the bucket locally 
```./gradlew com.ibm.ws.webcontainer.servlet.4.0_fat:buildandrun```

This test does not fail when running on builds,

The test fails locally with this in logs, 

[WARNING ] CWWKE0921W: Current Java 2 Security policy reported a potential violation of Java 2 Security Permission. The application needs to have permissions addedPermission: 
("java.net.SocketPermission" "127.0.0.1" "resolve")
Stack: 
java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1" "resolve")java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
java.base/java.security.AccessController.checkPermission(AccessController.java:897)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
java.base/java.lang.SecurityManager.checkConnect(SecurityManager.java:821)
java.base/sun.nio.ch.Net.getRevealedLocalAddress(Net.java:214)
java.base/sun.nio.ch.SocketAdaptor.getLocalAddress(SocketAdaptor.java:162)
java.base/java.net.Socket.getLocalSocketAddress(Socket.java:852)
com.ibm.ws.tcpchannel.internal.TCPReadRequestContextImpl.read(TCPReadRequestContextImpl.java:72)
com.ibm.ws.http.channel.internal.HttpServiceContextImpl.fillABuffer(HttpServiceContextImpl.java:4822)
com.ibm.ws.http.channel.internal.HttpServiceContextImpl.findBodyLength(HttpServiceContextImpl.java:3705)
com.ibm.ws.http.channel.internal.HttpServiceContextImpl.readSingleBlock(HttpServiceContextImpl.java:4028)
com.ibm.ws.http.channel.internal.HttpServiceContextImpl.readBodyBuffer(HttpServiceContextImpl.java:4157)
com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.getRequestBodyBuffer(HttpInboundServiceContextImpl.java:1509)
com.ibm.ws.http.channel.internal.inbound.HttpInputStreamImpl.checkBuffer(HttpInputStreamImpl.java:115)
com.ibm.ws.http.channel.internal.inbound.HttpInputStreamImpl.read(HttpInputStreamImpl.java:393)
com.ibm.ws.webcontainer.srt.SRTInputStream.read(SRTInputStream.java:73)
com.ibm.ws.webcontainer31.srt.SRTInputStream31.read(SRTInputStream31.java:311)
testservlet40.war.servlets.ServletGetTrailers.service(ServletGetTrailers.java:75)
javax.servlet.http.HttpServlet.service(HttpServlet.java:791)

**Steps to Reproduce**
When running the bucket locally 
```./gradlew com.ibm.ws.webcontainer.servlet.4.0_fat:buildandrun```

**Comment by anupag** [comment] 2020-05-13 20:31
[servlet40_wcServer-13-05-2020-12-33-57.zip](https://github.com/OpenLiberty/open-liberty/files/4624534/servlet40_wcServer-13-05-2020-12-33-57.zip)

**Comment by anupag** [comment] 2020-05-13 20:46
Discussed With Harry Hoots , based on the stack... it sounds like the app needs it: The application needs to have permissions addedPermission:
 ("java.net.SocketPermission" "127.0.0.1" "resolve")

**Comment by pnicolucci** [comment] 2021-12-08 21:08
Myself and @isaacrivriv  have both tested this locally and we can't reproduce the error. We also don't have any build break defects. For now, I'm going to clean up the FATSuite that talks about this issue and we can close this one out. If we see a problem in the future we can look to address it then.

**Closed** 2021-12-17 11:37 UTC
Labels: bug, in:Web Components, team:Sirius
