### ISSUE TITLE
Test Failure: com.ibm.ws.microprofile.metrics.tck.launcher.FATSuite.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8892] opened 2019-09-09 15:15 UTC
RTC 267260

```
launchTck:junit.framework.AssertionFailedError: Timeout occurred. Please note the time in the report does not reflect the time until the timeout.
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.Try.execute(Try.java:119)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.ForEach.execute(ForEach.java:158)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.If.execute(If.java:85)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.aries.buildtasks.BuildProjects.doExecute(BuildProjects.java:399)
at com.ibm.aries.buildtasks.BuildProjects.execute(BuildProjects.java:231)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base
```

This may be related to https://github.com/OpenLiberty/open-liberty/issues/8667

**Comment by lamkavan** [comment] 2019-09-16 13:55
One week has passed without any recurrences. Will monitor for one more week.

**Comment by lamkavan** [comment] 2019-09-23 13:19
Has not reoccurred in 2 weeks. Closing.

**Comment by lamkavan** [comment] 2019-11-18 15:49
As of Nov 18, 2019 there are two occurrences. The first was caused by a failure in retrieving a dependency from Maven Central which has been fixed by https://github.com/OpenLiberty/open-liberty/issues/9279 . The second occurrence does not seem to be caused by the same issue (no issues gathering dependencies) and appears to be a failure in starting the test. An investigation will be conducted to further diagnose the issue.

**Comment by lamkavan** [comment] 2019-11-20 15:47
After comparing the mvnOutput_test_tck-suite file from the failed build to a normal one it appears the test gets stuck while gathering dependencies. About half of the dependencies were retrieved successfully before getting "stuck". No errors or failures can be found in the logs other than the timeout. To be clear, this is not an issue with Maven Central as the last dependency being retrieved before getting stuck should not be coming from Maven Central. 

Possible causes for this test failure
- Technical glitch with Artifactory (perhaps related to high stress)
- Technical glitch with the build machine running the test

No other conclusions can be made with the logs generated from the test failure. Best course of action is to wait for other occurrences and see if there are any commonality between the failures. Finding commonalities between the failures will give us better insight into what the root issue is.

**Comment by fmhwong** [comment] 2019-11-25 16:07
Tom cancelled this as non-reproducible

**Comment by fmhwong** [comment] 2020-02-19 15:16
RTC defect was reopened on Feb 17, 2020

**Closed** 2020-04-20 14:17 UTC
Labels: team:Lumberjack

**Comment by lamkavan** [comment] 2020-04-20 14:22
This issue is not caused by Liberty and is believed to be caused by network and/or Artifactory issues. Efforts have been made to reduce/prevent the issue.
