### ISSUE TITLE
FFDC entries not being sent through logstashCollector-1.0

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#9757] opened 2019-11-13 16:27 UTC
**Describe the bug**
Liberty's logstashCollector-1.0 doesn't appear to be pushing any FFDC entries to Logstash

**Steps to Reproduce**
Steps to reproduce the bug

1. enable logstashCollector-1.0 feature
1. set logging element to <logging traceSpecification="com.ibm.ws.webcontainer.*=finer />

**Expected behavior**
FFDC is created in ffdc directory (since traceSpec is broken -- missing a quotation mark)
FFDC event should be pushed to ELK

**Current behavior**
FFDC is created as expected
FFDC event is not pushed to ELK

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.10]

**Comment by ellen-lau** [comment] 2020-01-07 19:03
Closing because currently non-reproducible.

**Closed by ellen-lau** 2020-01-07 19:03 UTC
Labels: bug, team:Lumberjack
