### ISSUE TITLE
JAX-RS Application Proxy should override getProperties()

### ISSUE THREAD

**Issue by rslemos** [OpenLiberty/open-liberty#12695] opened 2020-06-18 16:03 UTC
An instance of class [com.ibm.ws.jaxrs20.injection.ApplicationInjectionProxy](https://github.com/OpenLiberty/open-liberty/blob/bf37a4958be605085667280962413f7a91f2e6e5/dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/ApplicationInjectionProxy.java#L24) gets injected in resource fields. But it does not override `getProperties()` method, which defaults to `Collections.emptyMap()`.

```
@Path(...)
public class SomeJAXRSResource {
  @Context
  private Application appInField;

  @Path(...)
  public Response someEndpoint(@Context Application appInParam) {
    ...
    // appInParam is an instance of concrete subclass of Application
    appInParam.getProperties(); // yields correct properties
    // appInField is an instance of ApplicationInjectionProxy
    appInField.getProperties(); // yields Collections.emptyMap()
  }
}
```

**Diagnostic information:**
Not really needed. Quick inspection on source code in HEAD reveals that `getProperties()` is not overridden.

**Comment by jim-krueger** [comment] 2020-06-18 20:27
Hi,   On the latest version of Open Liberty I am not able to reproduce the issue you are reporting here.  
`@ApplicationPath("app8")
public class App8 extends Application {

    @Override
    public Map<String,Object> getProperties() {
        Map<String,Object> properties = new HashMap<String,Object>();
        properties.put("TestProperty", 100);
        return properties;
    }
'

`@Path("/resource4")
public class MyResource4 {

    @Context
    private Application appInField;

    @GET
    public String get(@Context Application appInParam) {

        Map<String,Object> fieldMap = appInField.getProperties();
        Map<String,Object> paramMap = appInParam.getProperties();

        if (!(fieldMap.containsKey("TestProperty"))) {
            return "Failed... missing property in injected field.";
        }
        if (!(paramMap.containsKey("TestProperty"))) {
            return "Failed... missing property in injected parameter.";
        }

        return "Success!";
    }
}
`

This always returns "Success!".

**Comment by rslemos** [comment] 2020-06-18 22:27
CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:**20.0.0.6**:zip

**Comment by rslemos** [comment] 2020-06-18 22:31
My JAX-RS class, besides field `@Context Application app` also has `@Resource(lookup = "url") private URL url`.

server.xml has `<jndiURLEntry jndiName="url" value="..."/>`

Perhaps this changes the actual instance of `Application` that gets injected.

**Comment by rslemos** [comment] 2020-06-18 22:35
Also, when switching to constructor injection:

```
public class MyResource {
  @Resource(lookup = "url") private URL url;

  public MyResource(@Context Application app) {
    // app has an instance of concrete subclass of Application
    // and, then, correct properties
  }

  @Path(...)
  public Response someEndpoint() {
    // url is not injected anymore
    // that is, it is null
  }
```

**Comment by rslemos** [comment] 2020-06-18 23:05
Removing feature `cdi-2.0` makes field `@Context Application` correcly hold a concrete instance of my application's subclass of `Application`, with correct properties.

But `@Resource(...) URL url` is not being injected anymore.

Feature `cdi-1.2` is not available for me, I don't know why: 
```
CWWKF1385E: The [cdi-1.2, com.ibm.websphere.appserver.transactionContext-1.0, com.ibm.websphere.appserver.cdi1.2-transaction1.2, com.ibm.websphere.appserver.cdi1.2-appSecurity1.0, com.ibm.websphere.appserver.cdi1.2-jndi1.0] assets depend on com.ibm.websphere.appserver.javax.servlet-3.1, which is not available in the IBM WebSphere Liberty Repository. If the required asset is a feature that you previously downloaded, install the missing feature by specifying the location of the feature ESA file on the featureManager install --location option, and try to install [cdi-1.2, com.ibm.websphere.appserver.transactionContext-1.0, com.ibm.websphere.appserver.cdi1.2-transaction1.2, com.ibm.websphere.appserver.cdi1.2-appSecurity1.0, com.ibm.websphere.appserver.cdi1.2-jndi1.0] again.
```

**Comment by jim-krueger** [comment] 2020-06-21 17:33
@rslemos:  Thanks for the additional information.   When I add the @Resource injection I am able to reproduce the issue you are seeing with @Context injection on the field.   

As for your question about cdi-1.2, I suspect you are seeing that message because you are using the jaxrs-2.1 feature.  JAXRS 2.1 uses cdi-2.0 and JAXRS 2.0 uses cdi-1.2.

**Comment by jim-krueger** [comment] 2020-07-02 15:39
@rslemos Thank you for identifying this issue.  The problem has been resolved by adding the getProperties() method to our ApplicationInjectionProxy class.  You can obtain the fix from any of the latest available drivers: https://openliberty.io/downloads/#development_builds.

If you disagree or have problems with this solution please re-open this issue or create a new issue.  Thanks.

**Closed by jim-krueger** 2020-07-02 15:39 UTC
Labels: Needs member attention, bug, in:JAX-RS, release bug, team:Wendigo West
