### ISSUE TITLE
mpOpenAPI generated UI does not send HeaderParams when "Try it out"

### ISSUE THREAD

**Issue by mnesarco** [OpenLiberty/open-liberty#10306] opened 2020-01-07 14:42 UTC
**Describe the bug**
When try resources from the OpenAPI UI, the form ask for Header params but they are not included in the request.

**Comment by arturdzm** [comment] 2020-01-07 15:39
Some parameters will not work by design, like Authorization and Accept headers for example as it uses different mechanism to select and send those.
Also UI was updated recently and will be available with next release.
I could test specific scenario if you provide the yaml snippet

**Comment by mnesarco** [comment] 2020-01-07 16:22
Hi @arturdzm , thank you for your response. My current use case is exactly Authorization header. Can you point me out to the mechanism you mentioned to send Authorization header?

Thank you very much.

**Comment by arturdzm** [comment] 2020-01-07 18:06
For Authorization in OAS there are: 

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securitySchemeObject

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securityRequirementObject

The first one creates security scheme types like basic, oauth, api key etc.
The second one is used to add it to openapi globally or per individual operations 

In MicroProfile they are represented by `org.eclipse.microprofile.openapi.annotations.security. SecurityScheme` and `org.eclipse.microprofile.openapi.annotations.security. SecurityRequirement` annotations.

**Comment by Emily-Jiang** [comment] 2021-05-18 11:01
@mnesarco have you tried what @arturdzm suggested? Since it was answered a while ago, I am going to close this one. Please reopen if you are still have problems with this.

**Closed by Emily-Jiang** 2021-05-18 11:01 UTC
Labels: bug, in:MicroProfile/OpenAPI
