### ISSUE TITLE
JAX-RS Client undesirable behaviour when target host contains underscores

### ISSUE THREAD

**Issue by BenCornwell1** [OpenLiberty/open-liberty#20067] opened 2022-02-08 16:00 UTC
**Describe the bug**  
When using javax.ws.rs.client.Client to invoke a remote HTTP/JSON service, I used the following code

        Flight[] flights  = client.target(DB_SERVER_URL)
            .path(DB_RESOURCE)
            .queryParam("departureDate", dateString)
            .queryParam("number", number)
            .request().get(Flight[].class);

If there is an underscore in the hostname (DB_SERVER_URL in this example), such as when using docker compose with default container names then it is accepted, but the subsequent methods path() and queryParam() don't have any effect.  It fails silently, and the client makes the request to the hostname only, which causes the invocation to fail.  This was observed in a docker container but NOT on Mac - it worked fine.

**Steps to Reproduce**  

        WebTarget wt = client.target("http://host_name_with_underscore")
            .path("resource")
            .queryParam("departureDate", dateString)
            .queryParam("number", number);
        System.out.println(wt.getUri());

The displayed URI only includes the hostname, not the path and the query parameters.

**Expected behavior**  
Since underscores are not permitted in hostnames according to RFC 822, an error should be thrown.

**Diagnostic information:**  
 - Open Liberty 22.0.0.1/wlp-1.0.60.cl220120220103-1900
 - Affected feature(s) jaxrsClient-2.1
 - Java Version: openjdk version "16.0.1" 2021-04-20

The issue was observed when running a JAR packaged liberty server running inside a container build from the openjdk:16.0.1 image on Docker hub.

**Comment by jim-krueger** [comment] 2022-07-06 18:52
@BenCornwell1 Getting back to this issue.   Back in February I tried to reproduce this issue on Windows but was unable to.  Is this something you can still reproduce using docker compose?

**Comment by jim-krueger** [comment] 2023-05-09 12:24
Closing as duplicate of #24380

**Closed as completed by jim-krueger** 2023-05-09 12:24 UTC
Labels: in:JAX-RS, Needs member attention, release bug
