### ISSUE TITLE
Two -Xshareclasses in the jvm properties affecting startup performance in docker environments.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#9662] opened 2019-11-06 14:24 UTC
In the server script, we set -Xshareclasses here:
https://github.com/OpenLiberty/open-liberty/blob/419f77eba1567b1c1340ae50cb4f65d20f831939/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L585

However, before the server script is invoked, In the OL Dockerfile, we also set it here:
https://github.com/OpenLiberty/ci.docker/blob/1dbe93bfcd3612b81e490104556a8262c7067d77/official/latest/kernel/java8/openj9/Dockerfile#L72

This is in a different location due to permissions issues with Openshift I believe.

Having two set is slowing down startup performance in docker envs.

Can we change the server script to not add -Xshareclasses if it's already specified?

**Comment by jdmcclur** [comment] 2019-11-07 19:02
I should note that the docker location does not set -Xscmx80m, so it will default to 24m (I think). So, maybe if it's not set on the jvm args, keep it at 80m?

**Comment by brenthdaniel** [comment] 2019-11-07 20:57
It also looks like 19.0.0.11 will break this.. Xshareclasses would have to be specified in OPENJ9_JAVA_OPTIONS rather than IBM_JAVA_OPTIONS (not the intention, just a bug.. see #9096  )

**Comment by jdmcclur** [comment] 2019-11-21 15:34
Brent, what is the status on this. Do you need my help, or help from the docker team?

**Comment by brenthdaniel** [comment] 2019-11-21 15:36
No, thanks, just waiting for the bugs introduced in 19.0.0.11 to be fixed (someone else is working on it.)

**Comment by jhanders34** [comment] 2019-11-25 12:45
Brent, would reverting the fix in 19.0.0.11, temporarily fix this problem, or would that also still have the problem?

**Comment by jhanders34** [comment] 2019-12-06 17:56
I understand now that the changes in #9096 did not cause this problem.  We are testing with a build before 19.0.0.11 and still seeing this problem, so you can disregard the question about doing a revert unless you think it would help to do one.

Is there an issue open or a pull request started for the bugs introduced in 19.0.0.11?  Maybe the issue should be marked as a regression if one exists.

**Comment by brenthdaniel** [comment] 2019-12-07 00:23
@canterburymalcolm is opening an issue

**Comment by jdmcclur** [comment] 2020-01-13 19:28
Any updates on this? I don't see an issue from @canterburymalcolm.

**Comment by brenthdaniel** [comment] 2020-01-13 20:13
Yep, he didn't finish before going back to school. I'm just finishing up some tests, but I should deliver both fixes as part of this work item in the next day or so.

**Closed** 2020-01-24 15:50 UTC
Labels: in:Kernel/Bootstrap, performance
