### ISSUE TITLE
Improve behavior of feature manager when conflicts occur

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#13928] opened 2020-09-14 16:23 UTC
When a server is configured with features that support javaEE and jakartaEE programming models, e.g. jsf-2.3 and faces-3.0, the server will emit an error message CWWKF0044E indicating the configured features include incompatible features:

>`[ERROR   ] CWWKF0044E: The features jsf-2.3 and el-4.0 cannot be loaded at the same time.  The feature jsp-2.3 of Java EE 8 is incompatible with the feature el-4.0 of Jakarta EE 9 (*).  The configured features jsp-2.3 and faces-3.0 include an incompatible combination of features.  Your configuration is not supported.  Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.`

The message would be more useful if the sentence ending at (*) indicated the configured feature, faces-3.0, rather than el-4.0.  And this is good opportunity to improve message content, if possible.

What happened here is that the configured features have dependency chains which eventually intersect on conflicting singleton eeCompatible-x.0 features.  The server reported the conflict detected in the shortest conflict chain, which involves jsf-2.3 and el-4.0.  And even that seems odd, because the configured features have immediate dependencies on conflicting eeComptable-x.0 features.  We would expect the server to immediately detect the conflict involving the configured features, but it does not.  To realize this behavior the feature manager could create the conflicts on immediate eeCompatible dependencies before launching the resolver.

**Comment by tjwatson** [comment] 2020-09-14 18:13
Anything that involves doing a preresolution for conflicts on eeCompatible I think is going to be error prone.  I think a better approach is to try and contain this to the resolver and to the resolver report processing after resolution if possible.  I'm going to take a quick look at what is going on to try and determine the feasibility of that.

**Comment by volosied** [comment] 2020-09-15 19:59
Since faces-3.0 has not yet been merged, a similar error can be seen with jsp-3.0 (page-3.0)  & jsf-2.3:

` The features jsp-2.3 and el-4.0 cannot be loaded at the same time.  The feature jsp-2.3 of Java EE 8 is incompatible with the feature el-4.0 of Jakarta EE 9.`

**Comment by tjwatson** [comment] 2020-09-21 21:27
Note that #13936 has been merged.  This will now cause the following message if `jsf-2.3` and `jsp-3.0` are configured:

```
[ERROR   ] CWWKF0044E: The features jsf-2.3 and jsp-3.0 cannot be loaded at the same time.  The feature jsf-2.3 of Java EE 8 is incompatible with the feature jsp-3.0 of Jakarta EE 9.  The configured features jsf-2.3 and jsp-3.0 include an incompatible combination of features.  Your configuration is not supported.  Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.
```

But this does result in a load of bundle resolution issues followed by a message that claims the following:

```
[AUDIT   ] CWWKF0012I: The server installed the following features: [el-3.0, el-4.0, jsp-2.3]
```

Notice that the single features `el-3.0` and `el-4.0` end up claiming to be both enabled.  This is a symptom of how the feature resolver reports conflicts and how the feature manager processes singleton conflicts that the resolver reports.  The feature resolver will only report a single conflict (a conflict involves two chains) for any given single feature name (e.g. `com.ibm.websphere.appserver.eeCompatible`).  And that single conflict is the one that involves the shortest chain.  So here that is the root features `jsf-2.3` and `jsp-3.0` because both of these features directly include different versions of `eeCompatible`.  But both of these features also end up pulling different conflicting versions of `el`.  But the resolution report that feature manager looks at will not include this conflict and it will happily let both versions of `el` to be included in the feature set to be installed.

It would be much more helpful if we simply didn't let any features install if any singleton conflicts are found.  This would be a change in behavior because the current runtime detects the invalid configuration but it still allows for some set of features to be installed.  This often leads to invalid sets of bundles to be installed which then results in a long list of bundle resolution errors that are of no help to the end user.  If we instead didn't install any features once a conflict is found then it would avoid installing invalid sets of bundles and producing useless bundle resolution errors for the end user.  Instead they can focus on the root cause of the invalid configuration which is the set of features enabled is not valid.

In theory this could be an issue if there is a user that has an invalid configuration but somehow the sets of bundles that did get installed produced some kind of functional server.  This user may be upset of we all of a sudden "break them" by not installing any feature bundles at all.  My view is that supporting such an invalid configuration is not sustainable and we are bound to break such a user at some point in the future.  Do we really want to have to continue to install invalid sets of bundles in the same exact way for all possible invalid configurations?

**Comment by dazavala** [comment] 2020-09-23 17:44
Regarding design considerations, here are the solutions we prefer. 
1. Stop installing all feature bundles when a single conflict is detected in the configured features
2. Stop installing all feature bundles only when a conflict is found on eeCompatible 
3. Leave current behavior and continue to allow invalid bundles to be installed for invalid feature configuration

Partial solutions are less preferrable -- e.g. stop installing only the bundles for features appearing in a conflict whenever a conflict is found on eeCompatible -- as they will cause the server to install incomplete bundle sets that do not support the users' feature configuration.  Since any option but 3 could impact migrated server configurations, we should also consider the value of adding a migration mitigation to the solution.

**Comment by tjwatson** [comment] 2020-09-28 19:07
Option 1 is my preferred solution, but this poses concerns for zero migration.

Option 2 tries to mitigate this concern by only limiting the new behavior for eeCompatible conflicts.  But this approach requires more special case knowledge of eeCompatible feature into feature manager and it still has zero migration concerns for other conflicts between different features from different versions of Java EE that also conflict on the eeCompatible feature.  We could probably try to be more smart there, but that puts even more special case logic for eeCompatible feature into the feature manager.

Option 3: Will continue to confuse users and it is made worse by the renaming of single features between Java EE and Jakarta EE leading more conflicts to empty private features like eeCompatible.

There has been some discussion of another option to make the feature resolver smarter so we can do something like Option 2.a.  The idea being that the feature manager should avoid installing bundles for features involved in a chain leading to a conflict.  This way other features not involved in the conflict can continue to function.  But this is a change in behavior for existing configurations with respect the set of bundles that would get installed for a conflict.

```
A->B->CONFLICT-1.0
C->D->CONFLICT-2.0
E
```
The current behavior is that features A,B,C,D,E will all get enabled and all their included bundles will get installed.  The conflicting features `CONFLICT-1.0` and `CONFLICT-2.0` will not enabled, but for the eeCompatible case that feature has no bundles so it hardly means anything to not enable that feature.  The idea is that `A->B` and `C->D` chains should not get enabled because they are involved in a conflict leading up to the two versions of `CONFLICT`.  But there could be a user that depends on the bundles from A,B,C,D being installed in this invalid configuration.  Changing this behavior will be considered a breaking change for them.

One option is to gate the new behavior with a new flag that is disabled by default, but we update all our templates to enable it when new servers are created.  It is unclear to me if this covers the case where users are updating a current server configuration from Java EE 8 to Jakarta EE 9.  For these cases I am not sure a new server configuration is always created.

Another way to avoid the zero migration concern is to introduce an Option 4:
Add meta-data to all new features.  As an example, this could be added as a directive to the Subsystem-SymbolicName similar to the `singleton:=true` like `disable-all-features-on-conflict:=true` (default is `false`)
or this could be as a separate header `DisableAllFeatures-OnConflict: true`

If any of the conflicting feature names is a feature marked `true` for `disable-all-features-on-conflict` then the result is no features at all will get enabled.  This way new behavior is only observed when new features are introduced into the users configuration, any existing configurations will not change in behavior at all.

**Comment by tevans78** [comment] 2020-09-29 15:01
Agreed to Option 4

**Comment by tjwatson** [comment] 2020-09-29 16:19
Requirements for solution to work with zero-migration mandate

`DisableAllFeatures-OnConflict` will be set to :
1. `true` for all new non-auto features
1. `false` for all existing GA released features
1. `true` for all non-auto features currently set for beta and must be set to `true` before they can GA.
1. `false` for all existing and future auto-features by default.
1. `false` for all features from usr/product extensions by default.

Proposed solution:

1. Liberty runtime (Feature Manager) will treat the absence of the `DisableAllFeatures-OnConflict` header to be `false`
1. All of Liberty's existing GA released features will be updated to explicitly set `DisableAllFeatures-OnConflict: false` in their specified `.feature` file.
1. For all non-auto features the build code which processes `.feature` files will automatically add the header `DisableAllFeatures-OnConflict: true` if it is not already specified in the `.feature` file.

Items 2 and 3 can be done independently and before item 1.  Item 1 must be blocked on item 2 and 3 getting done first.

**Comment by tjwatson** [comment] 2020-09-29 16:25
Actually item 1 could happen first because if no headers are set then the behavior remains the same as it is today.  But if item 1 is done first then item 3 CANNOT happen until item 2 is complete otherwise we will end up with all existing released features setting `DisableAllFeatures-OnConflict: true`

Therefore there should be a hard dependency for item 2 to get done before item 3.

**Comment by jhanders34** [comment] 2021-10-06 11:24
@dazavala and @tjwatson is this issue complete now?

**Comment by tjwatson** [comment] 2021-10-06 13:21
> @dazavala and @tjwatson is this issue complete now?

Yes, closing.

**Closed by tjwatson** 2021-10-06 13:21 UTC
Labels: design-issue, jakartaEE9

**Comment by dazavala** [comment] 2021-10-06 16:35
Yes.
