### ISSUE TITLE
Test Failure (Liberty z/OS Platform Build - 20181020-0122): io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest.io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5459] opened 2018-10-23 13:11 UTC
RTC 258833
```
io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest
java.lang.RuntimeException: Arquillian has previously been attempted initialized but failed. See cause for previous exception
at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:103)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:166)
at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:103)
at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:52)
at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:114)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
at sun.reflect.DelegatingCo
```

Occurred on the following Platforms:
Liberty z/OS Platform Build - 20181020-0122

**Comment by Channyboy** [comment] 2018-11-27 19:04
Monitoring https://github.com/OpenLiberty/open-liberty/pull/5671 for a fix as the encoding seems to be impacting all MP tests. Unfortunately the PR did not resolve the issue.

**Comment by Channyboy** [comment] 2018-12-10 16:08
Closing as duplicate of #5671 
See https://github.com/OpenLiberty/open-liberty/pull/5923 for the fix.

**Closed by Channyboy** 2018-12-10 16:08 UTC
Labels: team:Lumberjack
