### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing_fat: com.ibm.ws.request.timing.fat.TimingRequestTiming.testContextInfoWildCardMatchOverrideDefault

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14373] opened 2020-10-07 14:52 UTC
RTC 277172

```
java.lang.Throwable: 2020-08-19-06:56:52:542 There were 2 errors:
  componenttest.exception.TopologyException(Failures occured while waiting for app to start:
  Application jdbcTestPrj_3 failure: CWWKZ0002E: An exception occurred while starting the application jdbcTestPrj_3. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.NoClassDefFoundError: com.ibm.ws.classloading.internal.providers.Providers)
  java.lang.Exception(Errors/warnings were found in server RequestTimingServer logs:
<br>[8/19/20 6:56:48:651 BST] 00000053 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred while starting the application jdbcTestPrj_3. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.NoClassDefFoundError: com.ibm.ws.classloading.internal.providers.Providers)
at componenttest.custom.junit.runner.FATRunner.newThrowableWithTimeStamp(FATRunner.java:293)
at componenttest.custom.junit.runner.FATRunner.access$700(FATRunner.java:66)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:265)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
  componenttest.exception.TopologyException(Failures occured while waiting for app to start:
  Application jdbcTestPrj_3 failure: CWWKZ0002E: An exception occurred while starting the application jdbcTestPrj_3. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.NoClassDefFoundError: com.ibm.ws.classloading.internal.providers.Providers)
  java.lang.Exception(Errors/warnings were found in server RequestTimingServer logs:
<br>[8/19/20 6:56:48:651 BST] 00000053 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred

```

**Comment by pgunapal** [comment] 2020-10-21 21:20
Looks like the issue is related to Classloading and OSGI bundle, as there were other FAT failing with similar errors. Re-assigned the RTC defect to the appropriate team, closing this for now.

**Closed by pgunapal** 2020-10-21 21:20 UTC
Labels: team:Lumberjack
