### ISSUE TITLE
Websocket hang

### ISSUE THREAD

**Issue by deboer-tim** [OpenLiberty/open-liberty#3358] opened 2018-04-30 17:04 UTC
I was running an Open Liberty server with several clients connected, including about 10 open websocket connections and 60-80 concurrent streaming servlets and REST clients at the time. Other traffic was unaffected, but we noticed that websocket messages stopped coming though.

After taking a stack dump we noticed 2 websocket threads: one on a wait disconnecting a client, and one unable to send a message. This was confirmed by taking another dump a few minutes later. As far as I can tell, this is the same issue reported by other users here: https://stackoverflow.com/questions/40587658/websphere-spring-websocket-clientoutboundchannelexecutor-deadlock

Please feel free to ping me for the full stack trace (913K), or I can attach it here.

"Default Executor-thread-1319" #2381 daemon prio=5 os_prio=0 tid=0x00001461100ed000 nid=0x4668 in Object.wait() [0x0000146050bd1000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at com.ibm.ws.tcpchannel.internal.SimpleSync.simpleWait(SimpleSync.java:29)
    - locked <0x00000006d1d999c8> (a com.ibm.ws.tcpchannel.internal.SimpleSync)
    at com.ibm.ws.tcpchannel.internal.NioTCPWriteRequestContextImpl.processSyncWriteRequest(NioTCPWriteRequestContextImpl.java:62)
    at com.ibm.ws.tcpchannel.internal.TCPWriteRequestContextImpl.write(TCPWriteRequestContextImpl.java:96)
    at com.ibm.ws.channel.ssl.internal.SSLWriteServiceContext.write(SSLWriteServiceContext.java:166)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessageSync(MessageWriter.java:107)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessage(MessageWriter.java:72)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessage(MessageWriter.java:51)
    at com.ibm.ws.wsoc.LinkWrite.writeBuffer(LinkWrite.java:176)
    at com.ibm.ws.wsoc.WsocConnLink.outgoingCloseConnection(WsocConnLink.java:899)
    at com.ibm.ws.wsoc.SessionImpl.close(SessionImpl.java:438)
    at com.ibm.ws.wsoc.EndpointManager.httpSessionExpired(EndpointManager.java:180)
    at com.ibm.ws.wsoc.WsocHttpSessionListener.sessionDestroyed(WsocHttpSessionListener.java:62)
    at com.ibm.ws.session.http.HttpSessionObserver.sessionDestroyed(HttpSessionObserver.java:199)
    at com.ibm.ws.session.SessionEventDispatcher.sessionDestroyed(SessionEventDispatcher.java:154)
    at com.ibm.ws.session.StoreCallback.sessionInvalidated(StoreCallback.java:116)
    at com.ibm.ws.session.store.memory.MemorySession.invalidate(MemorySession.java:223)
    - locked <0x00000006d1da8850> (a com.ibm.ws.session.store.memory.MemorySession)
    at com.ibm.ws.session.store.memory.MemoryStore.runInvalidation(MemoryStore.java:491)
    - locked <0x00000006d1da8850> (a com.ibm.ws.session.store.memory.MemorySession)
    at com.ibm.ws.session.SessionInvalidatorWithThreadPool$InvalidationTask.run(SessionInvalidatorWithThreadPool.java:70)
    at com.ibm.ws.threading.internal.SchedulingRunnableFixedHelper.run(SchedulingRunnableFixedHelper.java:272)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

"CDS Worker" #418 daemon prio=5 os_prio=0 tid=0x000014614407e000 nid=0x1eea in Object.wait() [0x0000146073f00000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at com.ibm.ws.tcpchannel.internal.SimpleSync.simpleWait(SimpleSync.java:29)
    - locked <0x00000006d1d999c8> (a com.ibm.ws.tcpchannel.internal.SimpleSync)
    at com.ibm.ws.tcpchannel.internal.NioTCPWriteRequestContextImpl.processSyncWriteRequest(NioTCPWriteRequestContextImpl.java:62)
    at com.ibm.ws.tcpchannel.internal.TCPWriteRequestContextImpl.write(TCPWriteRequestContextImpl.java:96)
    at com.ibm.ws.channel.ssl.internal.SSLWriteServiceContext.write(SSLWriteServiceContext.java:166)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessageSync(MessageWriter.java:107)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessage(MessageWriter.java:72)
    at com.ibm.ws.wsoc.MessageWriter.WriteMessage(MessageWriter.java:51)
    at com.ibm.ws.wsoc.LinkWrite.writeBuffer(LinkWrite.java:176)
    at com.ibm.ws.wsoc.WsocConnLink.writeBufferForBasicRemoteSync(WsocConnLink.java:1066)
    at com.ibm.ws.wsoc.RemoteEndpointBasicImpl.sendBinaryCommon(RemoteEndpointBasicImpl.java:139)
    at com.ibm.ws.wsoc.RemoteEndpointBasicImpl.sendBinary(RemoteEndpointBasicImpl.java:85)
    at com.ibm.ws.wsoc.external.RemoteEndpointBasicExt.sendBinary(RemoteEndpointBasicExt.java:72)
    at org.acmicpc.cds.presentations.Client.sendData(Client.java:87)
    at ...

**Comment by billw1024** [comment] 2018-04-30 17:28
The stackoverflow issue appears to be running 16.0.0.3, so I think that has probably been fixed.

Two thread dumps of problem that are more than 5 minutes apart would be good to see here.

Liberty trace is probably going to be needed for debug, a trace spec of this, assuming it is reproducible (maxFiles and maxFileSize and traceFileName is up to you, but it needs to catch the problem):
    <logging maxFileSize="200" maxFiles="3" traceFileName="wsocTrace.log" traceSpecification="*=info:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:com.ibm.ws.webcontainer31*=all:HTTPChannel=all:TCPChannel=all:websockets=all"/> 

If that trace spec proves too verbose, then at least TCPChannel=all:websockets=all

If possible be really nice to have a network trace (wireshark) also, since the issue here may be that the other side of the connection has quit Reading on the connection, but has also not closed the connection, therefore the network buffers are full, and the writes will hang.

**Comment by deboer-tim** [comment] 2018-04-30 20:42
Was there a specific fix since 16.0.0.3 that you think would have solved the stackoverflow issue, or are you just guessing that it might have been fixed in the last year? FWIW, I was on 17.0.0.3 (image was locked down in the fall) and you can see the last few lines of the stack are similar.

I've sent the stack dump and message log via email. We did take two dumps several minutes apart, but I did not save the second (or maybe first?) copy because these two stacks were the only thing that was related and consistent/hadn't changed between the two.

We were on a network that wasn't 100% reliable, but in this case other content like streaming servlets didn't appear to hiccup and were still streaming data, so I do not believe there was a general network drop. For instance, I had physical access to 6/10 of the clients whose websockets had hung and they were all showing new data continuing to be streamed over HTTP.

I don't have access to the machine this was running on anymore and hence can't run a trace. I have successfully run as many websocket & streaming HTTP connections in the past without failure - including with network failures - so my guess is that this is not very easy to reproduce at will. The main reason I was concerned enough to open a bug is that this seems to indicate that failure disconnecting one client may lock up the entire websocket stack, i.e. the equivalent of one failed servlet bringing down all servlet traffic. Although it may be rare this requires you to detect this partial failure and restart the server.

**Comment by billw1024** [comment] 2018-05-01 15:16
There were a couple of fixes put in since 16.0.0.3 that may have resolved the problem mentioned at that time.

This hang should not impact any other websocket connection, since connections are processed independent of each other, and there is no central thread or resource lock.  But hanging a thread every once in a great while is still unacceptable.  My guess is something will close the connection eventually, and then this thread would get returned, but still, a possible hang is a possible hang.

I can see a code path where if the client code quits reading data but doesn't ever close the connection, and  the network buffers have become full due to the server side websocket app continuing to write data, and neither any software on the client nor any network hardware/software detects a (probable) error and closes the connection, then a timing window could be hit where the websocket code will attempt to write a close frame, and the write will hang because the connection is alive, it never gets closed, the client is not reading any data, and enough (non-read) data has already been written such that the network buffers are full.  So a rather ill-behaved client, or very buggy network situation.  

I can try to put in a fix for this case, but I'll need to make sure it is obviously safe and doesn't alter the more typical close paths that can occur, since there are a number of competing close paths, given the full duplex async nature of a websocket connection.  

A trace would prove this theory, but if one can't be gotten, then I am willing to go with this theory, and provide what I think will be the right fix.

**Comment by billw1024** [comment] 2018-08-23 16:57
Merged in June, will be in 18.0.0.3

**Closed by billw1024** 2018-08-23 16:57 UTC
Labels: Needs member attention, bug, in:Web Components
