### ISSUE TITLE
RM: Clearance to use SmallRye and other OSS

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#6684] opened 2019-02-26 10:54 UTC
Need to get clearance for consuming MP Reactive Messaging and SmallRye impl of Reactive Messaging

**Comment by tevans78** [comment] 2019-04-02 12:04
So far have used:
org.eclipse.microprofile.reactive-messaging:microprofile-reactive-messaging-api:1.0 (not released, not on maven central yet)
io.smallrye.reactive:smallrye-converter-api:1.0.1
io.smallrye.reactive:smallrye-reactive-messaging-provider:0.0.4

**Comment by tevans78** [comment] 2019-05-02 14:08
Initial note sent to Cass but this will be an ongoing process

**Comment by hutchig** [comment] 2019-07-23 09:30
I believe the versions for 1.0 are set and cleared now. @tevans78 @Azquelt please reopen if not correct.

**Comment by hutchig** [comment] 2019-07-23 09:34
Latest note I have:
Hi Tom,

Thanks so much for the heads up.  Are we aiming for Liberty 19.0.0.5 or 19.0.0.6?

You can go ahead and start using since the license is Apache V2.

regards,
Cassandra Tucker, MBA, PMP®, SCPM
WebSphere Application Server
cdtucker@us.ibm.com
919.486.0261   T/L 526.0261 (office)
 ___________________________________________
If you think you can, you can. And if you think you can't, you're right.
- Mary Kay Ash




From: Tom Evans/UK/IBM
To: Cassandra Tucker/Raleigh/IBM@IBMUS
Cc: Gordon Hutchison/UK/IBM@IBMGB, Emily Jiang/UK/IBM@IBMGB, Andrew Rouse/UK/IBM@IBMGB
Date: 04/30/2019 11:04 AM
Subject: OSS Clearance


Hi Cass,

A short while ago we started work on a new feature called MicroProfile Reactive Messaging. I wanted to get a head-start on making sure we have your approval to ship the open source dependencies. Our initial OSS dependencies are

io.smallrye.reactive:smallrye-converter-api:1.0.1
        http://central.maven.org/maven2/io/smallrye/reactive/smallrye-converter-api/1.0.1/

io.smallrye.reactive:smallrye-reactive-messaging-provider:0.0.4
        http://central.maven.org/maven2/io/smallrye/reactive/smallrye-reactive-messaging-provider/0.0.4/
        http://smallrye.io/smallrye-reactive-messaging/
        https://github.com/smallrye/smallrye-reactive-messaging
I am almost certain that the version of this one will change (version 0.0.7 is already available).

Once the API has been properly released, there will also be a dependency on the MP Reactive Messaging API. At the moment we are prototyping using a checked in copy of the source from here;
 https://github.com/eclipse/microprofile-reactive-messaging

It is also likely that we will be using the Apache Kafka Client but we have not yet decided if we will ship it ourselves or not.
        http://central.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.0/

The license for all of these is Apache v2.0.

**Comment by tevans78** [comment] 2019-08-21 13:22
Updated to smallrye reactive messaging provider 1.0.1 and confirmed with Cass. Closing this issue now.

**Closed by tevans78** 2019-08-21 13:22 UTC
Labels: in:MicroProfile/Reactive, team:MicroProfileUK
