### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#7369] opened 2019-04-29 20:11 UTC
@lulseged commented on [Mon Apr 29 2019](https://github.com/OpenLiberty/openliberty.io/issues/1162)

Hi

When using JAVA 11/12 the following is printed out and sometimes prevents to proceed.

 [INFO] WARNING: An illegal reflective access operation has occurred
[INFO] WARNING: Illegal reflective access by com.ibm.ws.logging.internal.impl.IntrospectionLevelMember$2 (file:/D:/appz/wlp-kernel-19.0.0.4/lib/com.ibm.ws.logging_1.0.27.jar) to field java.util.logging.Logger.emptyHandlers
[INFO] WARNING: Please consider reporting this to the maintainers of com.ibm.ws.logging.internal.impl.IntrospectionLevelMember$2
[INFO] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[INFO] WARNING: All illegal access operations will be denied in a future release

BR
Lulseged Zerfu

**Comment by fmhwong** [comment] 2019-04-29 21:01
This is a duplicate of #2328.

**Closed by fmhwong** 2019-04-29 21:01 UTC
Labels: Needs member attention, team:Lumberjack
