### ISSUE TITLE
MP Health 2.0 readiness check returns HTTP 200 before app is ready

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#9609] opened 2019-11-01 19:04 UTC
If I have an app that enables the `mpHealth-2.0` feature enabled in server.xml and has an app baked into the /dropins directory in a docker container using the `openliberty:microProfile3` base image, the readiness check at `/health/ready` returns HTTP 200 before the app is actually available.

## Steps to reproduce

The issue can be reproduced by cloning this repo: https://github.com/aguibert/microshed-testing/tree/mphealth-issue

```
git clone git@github.com:aguibert/microshed-testing.git
cd microshed-testing
git checkout mphealth-issue
./gradlew :microshed-testing-everything-app:test
```
After running the gradle test, the tests will fail with HTTP 404 errors because the tests try to run before the app is ready.

**Comment by aguibert** [comment] 2019-11-01 19:22
[trace.log](https://github.com/OpenLiberty/open-liberty/files/3799303/trace.log)

**Comment by pgunapal** [comment] 2019-11-15 15:52
@aguibert I took a look at the trace and it seems like the `/health/ready` endpoint was called before the ApplicationStateListener.applicationStarting() method registered the application for mpHealth. After discussing the issue with a few folks, I found that there is a design-issue that was being discussed (https://github.com/OpenLiberty/open-liberty/issues/7709), which I believe should resolve this issue. The new design is basically, delaying the opening of the ports till the server has actually started. I worked with Bill W., got a PB to try out from the PR (https://github.com/OpenLiberty/open-liberty/pull/8016) associated with that issue. I replaced the wlp directory in the Docker Container from MicroShed with the one from the PB, and tried to reproduce the issue, and I could not anymore. Basically, the ports will not be exposed till the server has started, meaning the `/health/ready` endpoint can not be accessed, till the server has started, so a false positive HTTP 200 will not be returned before the app is ready. I also tested the case where the server has started and ports are now opened, however the application has not started yet, this works fine with the currently implementation of MP Health 2.0, as it returns the expected the HTTP 503 status, since the ApplicationStateListener works as expected and the deployed applications are registered correctly. According to Bill W, the PR (https://github.com/OpenLiberty/open-liberty/pull/8016) will only be merged after 19.0.0.12, is that okay with you?

**Comment by aguibert** [comment] 2019-11-15 15:56
HI @pgunapal, thanks for following up on this. That sounds like a good solution. So to summarize the flow of events we will have:
1. Server starts with ports shut
2. applicationStarting() events fire (for all apps on disk at the time)
3. Server starts and ports open
4. appStarting() events finish, allowing /health/ready to return HTTP 200

**Comment by pgunapal** [comment] 2019-11-15 16:01
Yeah, that's the flow of the events, in a normal case.

For a case where the app have not started yet:
    1. Server starts with ports shut
    2. applicationStarting() events fire (for all apps on disk at the time)
    3. Server starts and ports open
    **4. Apps still in STARTING state, /health/ready will return HTTP 503, until apps have started.**
    5. Apps have started, appStarting() events finish, allowing /health/ready to return HTTP 200

**Comment by pgunapal** [comment] 2020-01-14 20:15
@aguibert The PR #8016 that fixes this issue was merged and is in master. Looks like it is targeted to be included in the 20.0.0.2 fix pack release. Is it possible for you to verify it using the daily builds on docker?

**Comment by aguibert** [comment] 2020-01-20 04:11
hi @pgunapal, I ran the test again with the `openliberty/daily` tag (`Open Liberty 20.0.0.2/wlp-1.0.37.cl200220200118-1900`) and everything passed.

I was thinking that if we do not already have one, we should create a FAT test for MP Health 2.0 that polls the MP Health 2.0 readiness path (as opposed to the usual log scraping) to determine if the app is ready or not.

**Comment by pgunapal** [comment] 2020-01-20 16:30
@aguibert we do have an existing Readiness FAT test that tests for applications that start up slowly, and checks if the app has not started yet, the Readiness check will return 503.

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java

**Comment by aguibert** [comment] 2020-01-20 16:47
was this test added before or after I raised this issue? My concern is that this issue was not caught by a FAT bucket in the first place. If the above test was in place before this issue was found in the field, we will need more test coverage.

**Comment by pgunapal** [comment] 2020-01-20 16:54
It was added before. You right, this issue goes through a different flow, where the `/health/ready` endpoint was accessed, immediately after the server was started, which is not covered by our tests. We will add a test case to test this particular scenario.

**Comment by aguibert** [comment] 2020-01-20 17:01
thanks, that will be an important test scenario because in container environments (Kube, OpenShift, etc) the container gets started and immediately the infra will start polling `/health/ready` until it returns HTTP 200

**Closed** 2020-02-03 20:06 UTC
Labels: in:MicroProfile/Health, release bug, team:Lumberjack
