### ISSUE TITLE
Resource adapters should not be shut down before applications that use them

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#15184] opened 2020-12-04 19:43 UTC
**Describe the bug**
During the shutdown of the Open Liberty, if there's a servlet running the Open Liberty don't cancel it. Meanwhile, the resource adapters are shut down, and if the application uses it, the application will fail because it is in an invalid state.
In our case, the resource adapter is the IronJacamar, used to provide the DataSource.

```
[INFO] [AUDIT   ] J2CA7001I: Resource adapter IronJacamar installed in 3.119 seconds.
[...]
[INFO] com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource@55489eec
[INFO] org.jboss.jca.adapters.jdbc.WrapperDataSource@7484a35
[INFO] CWWKM2001I: Invoke command is [/sample-getting-started/target/liberty/wlp/bin/server, stop, sampleAppServer].
[INFO] 
[INFO] [AUDIT   ] CWWKE0085I: The server sampleAppServer is stopping because the JVM is exiting.
[INFO] [AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://127.0.0.1:9080/
[INFO] Stopping server sampleAppServer.
[INFO] [AUDIT   ] CWWKE0055I: Server shutdown requested on Friday, December 4, 2020 at 4:26 PM. The server sampleAppServer is shutting down.
[INFO] [WARNING ] CWWKE1102W: The quiesce operation did not complete. The server will now stop.
[INFO] [WARNING ] CWWKE1107W: 1 threads did not complete during the quiesce period. 
[INFO] [AUDIT   ] J2CA7009I: The resource adapter IronJacamar has uninstalled successfully.
[INFO] com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource@66a4ec94
[INFO] [ERROR   ] SRVE0777E: Exception thrown by application class 'io.openliberty.sample.SampleApplication.doGet:52'
[INFO] java.lang.RuntimeException: javax.naming.NamingException: CWNEN1001E: The object referenced by the java:comp/env/jdbc/db2 JNDI name could not be instantiated. If the reference name maps to a JNDI name in the deployment descriptor bindings for the application performing the JNDI lookup, make sure that the JNDI name mapping in the deployment descriptor binding is correct. If the JNDI name mapping is correct, make sure the target resource can be resolved with the specified name relative to the default initial context. [Root exception is com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/jdbc/db2 reference.  The exception message was: CWNEN1003E: The server was unable to find the jdbc/db2 binding with the javax.sql.DataSource type for the java:comp/env/jdbc/db2 reference.]
[INFO]  at io.openliberty.sample.SampleApplication.doGet(SampleApplication.java:52)
[INFO]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
[INFO]  at [internal classes]
[INFO] Caused by: javax.naming.NamingException: CWNEN1001E: The object referenced by the java:comp/env/jdbc/db2 JNDI name could not be instantiated. If the reference name maps to a JNDI name in the deployment descriptor bindings for the application performing the JNDI lookup, make sure that the JNDI name mapping in the deployment descriptor binding is correct. If the JNDI name mapping is correct, make sure the target resource can be resolved with the specified name relative to the default initial context. [Root exception is com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/jdbc/db2 reference.  The exception message was: CWNEN1003E: The server was unable to find the jdbc/db2 binding with the javax.sql.DataSource type for the java:comp/env/jdbc/db2 reference.]
[INFO]  at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.newCannotInstantiateObjectException(InjectionJavaColonHelper.java:183)
[INFO]  at [internal classes]
[INFO]  at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
[INFO]  at java.naming/javax.naming.InitialContext.doLookup(InitialContext.java:282)
[INFO]  at io.openliberty.sample.SampleApplication.doGet(SampleApplication.java:50)
[INFO]  ... 2 more
[INFO] Caused by: com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/jdbc/db2 reference.  The exception message was: CWNEN1003E: The server was unable to find the jdbc/db2 binding with the javax.sql.DataSource type for the java:comp/env/jdbc/db2 reference.
[INFO]  at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1454)
[INFO]  ... 6 more
[INFO] Caused by: com.ibm.wsspi.injectionengine.InjectionException: CWNEN1003E: The server was unable to find the jdbc/db2 binding with the javax.sql.DataSource type for the java:comp/env/jdbc/db2 reference.
[INFO]  at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.getObjectInstance(IndirectJndiLookupObjectFactory.java:203)
[INFO]  ... 6 more
[INFO] 
[INFO] [AUDIT   ] CWWKZ0009I: The application io.openliberty.sample.getting.started has stopped successfully.
[INFO] [AUDIT   ] WTRN0105I: The transaction service has shutdown successfully with no transactions requiring recovery.
[INFO] [AUDIT   ] CWWKE0036I: The server sampleAppServer stopped after 1 minutes, 43.147 seconds.
```

**Steps to Reproduce**
1. `$ mvn liberty:dev`
2. Access `http://localhost:9080/hello`
3. Hit Ctrl+C in the terminal to shutdown the server
[example.zip](https://github.com/OpenLiberty/open-liberty/files/5644990/example.zip)

**Expected behavior**
Both Liberty's and IronJacamar's DataSource showing in the console. Only the Open Liberty data source is shown.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.12
 - Java Version: 
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
 - server.xml configuration: In the example.zip

**Comment by njr-11** [comment] 2020-12-04 21:12
This is due to Liberty's 30 second server quiesce timeout being exceeded.  Under normal circumstances, Liberty follows the JCA specification in stopping applications before stopping resource adapters.  However, in this case, the application sleeps for 60 seconds before attempting additional JNDI lookups, an interval during which the server quiesce timeout is exceeded.  After that, Liberty stop the resource adapter and completes its own shutdown. I don't think it would make sense to continue waiting for a graceful shutdown of the application after the quiesce expires.  There is no way to know how much more time the application will need.  If an application were hung, it would wait forever, which would be an undesirable behavior.  It looks like you have also opened #15188 to allow for configuring a longer interval for server quiesce, which seems like the better way to address applications that take a long time to gracefully stop.

**Comment by njr-11** [comment] 2020-12-07 14:27
close as duplicate of #15188

**Closed by njr-11** 2020-12-07 14:27 UTC
Labels: Needs member attention, bug, duplicate
