### ISSUE TITLE
startup failure -  java.io.IOException: Property 'ant.home' not found

### ISSUE THREAD

**Issue by gireeshpunathil** [OpenLiberty/open-liberty#130] opened 2017-09-21 12:58 UTC
I followed the instructions in `Quick start` section, but the last step (mvn clean package -P start) failed (after around 20 minutes) thus:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Conference ......................................... SUCCESS [ 28.170 s]
[INFO] Conference :: Bootstrap Data ....................... SUCCESS [02:46 min]
[INFO] Conference :: Session .............................. SUCCESS [02:17 min]
[INFO] Conference :: Vote ................................. SUCCESS [04:00 min]
[INFO] Conference :: Speaker .............................. SUCCESS [03:29 min]
[INFO] Conference :: Schedule ............................. SUCCESS [ 15.015 s]
[INFO] Conference :: Web .................................. FAILURE [09:49 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:56 min
[INFO] Finished at: 2017-09-21T18:15:14+05:30
[INFO] Final Memory: 45M/100M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (open-ui-in-browser) on project web-application: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot locate antRun script: Property 'ant.home' not found
[ERROR] around Ant part ...<exec vmlauncher="false" executable="open">... @ 4:46 in /Users/gireeshpunathil/Desktop/liberty/sample-mpconf/web-application/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :web-application
#
```

host: macOS X Sierra
Java: 
```c
#java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
#
```
Any hints?

**Comment by aguibert** [comment] 2017-09-22 17:01
do you have ant on your `$PATH`?  Can confirm on a unix-like cmdline by doing `which ant`

**Comment by realModusOperandi** [comment] 2017-09-22 20:45
I can confirm that it's not sufficient to have ant on the path--running after `brew install ant`, which placed ant in `/usr/local/bin` which is on my PATH, does not fix the issue. Neither does setting `ANT_HOME` in the env. 

macOS Sierra as well

**Comment by aguibert** [comment] 2017-09-29 18:51
Seems to be only reproducible on Mac OS (which I don't have).  Un-assigning from myself and tagging help-wanted so someone with a mac can pick up.

**Comment by kwsutter** [comment] 2017-09-29 20:41
I experienced the exact same issue as the originator.  As a quick test, I tried installing ant with "brew install ant".  I did not try setting ant.home or ANT_HOME yet.  Still same issue.  I'll try other variations as time permits...

**Comment by realModusOperandi** [comment] 2017-09-29 20:45
After a lot of discussion with some people, I was able to work around by specifying `-Dant.home=<ant_path>` directly after `mvn`. Is there some way to automatically specify this so I don't have to each time?

**Comment by kwsutter** [comment] 2017-09-30 13:35
Agree with @realModusOperandi ...  If I put the -Dant.home on the mvn command, it all works as expected.  At a minimum, we need to update the front-facing README with these additional instructions (for a mac, at least).  But, it would be better to update the build scripts to either not rely on Ant, or do this setup automatically.  Thanks.

**Comment by gireeshpunathil** [comment] 2017-09-30 17:34
apologies, missed the questions and updates on this thread after the original posting. I will try the recommendations and get back.
`which ant` yielded nothing, so no `ant` is in the system. I was bluntly following the build commands as documented.

**Comment by McPringle** [comment] 2017-10-20 21:23
I tried it today with the actual version on macOS 10.13 High Sierra with Java 1.8.0_144-b01 and it worked like a charm. This issue seems to be fixed with https://github.com/OpenLiberty/sample-mpconf/pull/14.

**Closed** 2017-12-02 03:24 UTC
Labels: help wanted
