### ISSUE TITLE
Use JSON-P and JSON-B RI or use Apache Johnzon

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#125] opened 2017-09-20 21:35 UTC
Had a call today to discuss whether to use the reference implementations for JSON-P/JSON-B as was the case when the features were first released in the WebSphere Liberty beta, or to use Apache Johnzon as is currently the case for Open Liberty.

Currently JSON-P 1.0 is based on the reference implementation.

On the conference call was @kwsutter @nottycode @aguibert @njr-11 @andymc12 @WhiteCat22 @realModusOperandi @alexsm82 

The discussion looked at 3 issues:

1. Would there be any migration problems for someone going from JSON-P 1.0 to JSON-P 1.1 if we change implementation
1. Which JSON-B implementation has the failure semantics we preferred
1. Which JSON-P/JSON-B implementations perform better.

Interestingly although Jackson has the best performance when you are running in a Java SE environment when used from JAX-RS in Liberty the performance of Jackson, Johnzon and the RI's are similar. Jackson is best for serialization, and Johnson for deserialization and the reference implementation is in the middle. This suggests that while Jackson has the best performance in raw terms, the marshalling and unmarshalling of the JSON is such a small component of the JAX-RS performance that it doesn't matter which is used.

Moving from JSON-P to Johnzon would result in some differences in behaviour. When calling build on a JsonObjectBuilder or a JsonArrayBuilder the RI resets the map. So you can call build, and reuse the builder. However Johnzon throws a NullPointerException on a JsonObjectBuilder and the JsonArrayBuilder acts as if all the state added prior to the build is still there. Both of these would likely surprise and disappoint people used to the behaviour of the reference implementation.

In general none of the implementations have first class parse error messages, so that wasn't a major issue, but Johnzon tended not to provide context for the failure, so if it reported an error message it would tell you the value, but not the attribute, nor where in the json structure the error was which could make debug quite hard.

Overall the decision was made that the RI should be used in favour of Johzon, however given the problems found in Johnzon are ones we think others would see we will contact the Apache Johnzon community to let them know of our findings.

There was one interesting behaviour of the JSON-B reference implementation that wasn't liked and seemed inconsistent with jackson and johnzon which is that if you tried to put a JsonObject into a String in the reference implementation you end up with the Object being created with an empty string injected, the others threw exceptions. It was felt that fail fast would be preferable as a default object and the behaviour of the reference implementation was thus not ideal. It also contrasts badly with the behaviour of JPA entities which would throw an error if the database row type and the entity type were incompatible.

**Comment by aguibert** [comment] 2017-09-21 18:50
The key issue remaining which would block us from making this change is resolving the following:
> There was one interesting behaviour of the JSON-B reference implementation that wasn't liked and seemed inconsistent with jackson and johnzon which is that if you tried to put a JsonObject into a String in the reference implementation you end up with the Object being created with an empty string injected, the others threw exceptions.

We have done some investigation on this and actually found out that putting a JsonObject into a String results in an empty string value in the POJO for both the RI and Johnzon.

However, we found a new/related issue where unrecognized keys are encountered in a JSON during deserialization, Jackson rejects this by default, and the JSON-B RI creates the java object and simply ignores the extra key.  This behavior seems to be defined by the JSON-B spec:
> **3.18 Must-Ignore policy**
When JSON Binding implementation during deserialization encounters key in key/value pair that it does not recognize, it should treat the rest of the JSON document as if the element simply did not appear, and in particular, the implementation MUST NOT treat this as an error condition.

Based on this wording, there does not to seem to be any way to opt out of this behavior.  Looking at the available API, I don't see any way to opt-out either.  I've raised the following issue on the JSON-B spec repo in GitHub: https://github.com/javaee/jsonb-spec/issues/56

However, assuming there is no way to opt-out of this "Must-Ignore" policy, does it change your opinion @NottyCode

**Comment by kwsutter** [comment] 2017-09-21 19:46
It does not change my opinion.  Since the spec is very clear on the
expected behavior, whether we like it or not is moot.  We should have
argued against this processing while the spec was being generated, but we
missed it.  No big deal, we don't catch everything during the JSR review
process.  It's good that we raised the issue.  If they provide an "out" in
a future revision of the RI, then we can consider including it.

**Comment by aguibert** [comment] 2017-09-25 20:28
The change from Johnzon -> RI's has been delivered and is now in `master`.  Closing this issue

**Closed by aguibert** 2017-09-25 20:28 UTC
Labels: in:Java EE Platform
