### ISSUE TITLE
Enum value different from EnumType result in JsonbException

### ISSUE THREAD

**Issue by igbluz** [OpenLiberty/open-liberty#29964] opened 2024-10-25 16:13 UTC
**Describe the bug**  
Using OpenApi we define following object:
    PropertyDto:
      type: object
      properties:
        propertyId:
          type: string
        propertyType:
          type: string
          enum:
            - TYPE_STRING
            - TYPE_STRING_LIST

Using the OpenApi Generator for Java with microprofile library and serializationLibrary Jackson the following class is generated:

  public static enum PropertyTypeEnum {
        STRING(String.valueOf("TYPE_STRING")),
        STRING_LIST(String.valueOf("TYPE_STRING_LIST"));

        String value;

        private PropertyTypeEnum(String v) {
            this.value = v;
        }

        @JsonValue
        public String value() {
            return this.value;
        }

        public String toString() {
            return String.valueOf(this.value);
        }

        @JsonCreator
        public static PropertyTypeEnum fromValue(String value) {
            PropertyTypeEnum[] var1 = values();
            int var2 = var1.length;

            for(int var3 = 0; var3 < var2; ++var3) {
                PropertyTypeEnum b = var1[var3];
                if (b.value.equals(value)) {
                    return b;
                }
            }

            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

This fromValue() Implementation is correct and can handle the discrepancy in Enum between STRING and TYPE_STRING.

Now Using from OpenLiberty Server with Microprofile RestClientBuilder the Service I get on the response the following error:

Internal error: No enum constant PropertyTypeEnum.TYPE_STRING during yasson deserialization

[INFO] Caused by: jakarta.json.bind.JsonbException: Internal error: No enum constant PropertyDto.PropertyTypeEnum.TYPE_STRING
[INFO]  at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:142)
[INFO]  at [internal classes]
[INFO]  ... 160 more
[INFO] Caused by: java.lang.IllegalArgumentException: No enum constant PropertyDto.PropertyTypeEnum.TYPE_STRING
[INFO]  at java.base/java.lang.Enum.valueOf(Enum.java:293)
[INFO]  at org.eclipse.yasson.internal.deserializer.types.EnumDeserializer.deserializeStringValue(EnumDeserializer.java:31)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.yasson.internal.deserializer.Positi
[INFO] onChecker.deserialize(PositionChecker.java:34)
[INFO]  at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
[INFO]  at [internal classes]
[INFO]  ... 167 more

On the Server because yasson is used it does the following Enum handling:
    Object deserializeStringValue(String value, DeserializationContextImpl context, Type rType) {
        return Enum.valueOf((Class)rType, value);
    }

Using just Enum.valueOf() results in the error.

**Steps to Reproduce**  
--

**Expected behavior**  
Enum Deserializer would give the correct result and create an Type PropertyTypeEnum.STRING

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.10]
 - Affected feature(s) [e.g. jsonb-3.0]
 - Java Version:  Launching defaultServer (Open Liberty 24.0.0.10/wlp-1.0.94.cl241020240923-1638) on Eclipse OpenJ9 VM, version 21.0.2+13-LTS (en_US)

Is there a possibility to tell openliberty to use another implementation.

**Comment by KyleAure** [comment] 2024-10-27 18:59
@igbluz Please see the Jakarta JSON Binding spec section on ENUM: https://jakarta.ee/specifications/jsonb/3.0/jakarta-jsonb-spec-3.0#enum

```txt
Deserialization of a JSON value into an enum instance MUST be done by calling the enum’s valueOf(String) method.
```

Therefore, it seems the behavior you are experiencing is expected.
The work around would be to not use a `@JsonCreator` but instead use a `@JsonbDeserializer` class to do the conversion between the enum `value` field and the enum object. 
Ref: https://jakarta.ee/specifications/jsonb/3.0/jakarta-jsonb-spec-3.0#serializersdeserializers

This issue is a duplicate of an issue already raised against the yasson project: https://github.com/eclipse-ee4j/yasson/issues/221

**Comment by igbluz** [comment] 2024-10-28 07:57
Hi @KyleAure, thank you so much for your quick response and clarification. Yes you are right. Because we define the "Interface" using OpenApi and using its generators, the class are generated in that way. Using yasson does result in the problem I tried to explain. I found another solution to this, in just using the gson with <serializationLibrary>gson</serializationLibrary> as generator config option. Like this a different PropertyTypeEnum is generated which handle correct the desserialization of the "special" EnumType.

```
  @JsonbTypeSerializer(PropertyTypeEnum.Serializer.class)
  @JsonbTypeDeserializer(PropertyTypeEnum.Deserializer.class)
  public enum PropertyTypeEnum {

    BINARY(String.valueOf("TYPE_BINARY")), BOOLEAN(String.valueOf("TYPE_BOOLEAN")), 
    DATETIME(String.valueOf("TYPE_DATETIME")), DOUBLE(String.valueOf("TYPE_DOUBLE")), GUID(String.valueOf("TYPE_GUID")), 
    INTEGER(String.valueOf("TYPE_INTEGER")), OBJECT(String.valueOf("TYPE_OBJECT")), STRING(String.valueOf("TYPE_STRING")), 
    STRING_LIST(String.valueOf("TYPE_STRING_LIST")), STRING_PARAMETER(String.valueOf("TYPE_STRING_PARAMETER"));

    String value;

    PropertyTypeEnum (String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static final class Deserializer implements JsonbDeserializer<PropertyTypeEnum> {
        @Override
        public PropertyTypeEnum deserialize(JsonParser parser, DeserializationContext ctx, Type rtType) {
            for (PropertyTypeEnum b : PropertyTypeEnum.values()) {
                if (String.valueOf(b.value).equals(parser.getString())) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + parser.getString() + "'");
        }
    }
```

So it is not really a bug of OpenLiberty, more a handling between yasson and OpenApi Generator.
Case can be closed, thank you.

**Comment by KyleAure** [comment] 2024-10-28 13:20
Closing as resolved :D. Glad I could help.

**Closed as completed by KyleAure** 2024-10-28 13:20 UTC
Labels: team:Zombie Apocalypse
