### ISSUE TITLE
ContainerRequestContext.abortWith() doesn't seem to preserve the "payload" of the Response provided

### ISSUE THREAD

**Issue by MarkBluemel** [OpenLiberty/open-liberty#18350] opened 2021-08-27 07:17 UTC
**Describe the bug**
We are migrating from jaxrs-1.1 to jaxrs-2.1 and have to change from Wink handlers to CXF filters for various operations on the incoming Requests.

Our old Wink handlers reported errors with detailed error information in JSON-formatted content in the `Response `following a pattern like this:

               (`msgContext `is the `org.apache.wink.server.handlers.MessageContext `received by the handler)

```
		HttpServletResponse resp = msgContext.getAttribute(javax.servlet.http.HttpServletResponse.class);
		JSONObject result = new JSONObject();
		_<fill the result with appropriate data>_
		resp.setStatus(_<appropriate status>_);
		resp.setContentType("application/json");
		resp.setCharacterEncoding("UTF-8");
		resp.getWriter().write(result.toString(2));
		resp.getWriter().flush();
```

To produce the same result under a CXF filter, I presume we need to use code  which builds the same `Response `and then calls `ContainerRequestContext.abortWith()`, passing the Response, using the following pattern:

               (`context`is the `javax.ws.rs.container.ContainerRequestContext` received by the filter)
```

		ResponseBuilder respBuilder = Response.serverError();
		JSONObject result = new JSONObject();
		_<fill the result with appropriate data>_
		respBuilder.encoding("UTF-8");
		respBuilder.type("application/json");
		respBuilder.entity(result);
		Response resp = respBuilder.status(_<appropriate status>_).build();
		context.abortWith(resp);
```

But in this case while the status is as set by the filter, the content of the `Response`, as received by the client, is simply a JSON Object of the form
               `{ "empty" : "false" }`

I'd be happy to be told my code is incorrect and shown how to achieve the result required with CXF filters, but I'd like to understand why the entity that was set has apparently been discarded.

**Steps to Reproduce**
I think the description above should be sufficient.

**Expected behavior**
The client should receive the JSON formatted by the filter.

**Diagnostic information:**
 
    OpenLiberty Version: WebSphere Application Server 21.0.0.3 (wlp-1.0.50.cl210320210309-1101)
    Java Version: Java(TM) SE Runtime Environment (8.0.6.31 - pwa6480sr6fp31-20210510_01(SR6 FP31)
    server.xml configuration: I doubt this would be helpful.

**Additional context**

**Comment by andymc12** [comment] 2021-08-27 19:00
Hi @MarkBluemel - I attempted to reproduce this using a filter similar to yours, but it worked for me.  You can see my code, Liberty config, and output here: https://gist.github.com/andymc12/7f27049ebff9417317cc538daae3388f

My app is super simple (the app endpoint would normally just return "Hello World"), and so most of the code is in the filter on gist.  I wonder if you've got something else in your environment/application that might be reconstructing the HTTP response entity.  A trace of this request might be helpful in diagnosing further.  Thanks!

**Comment by andymc12** [comment] 2021-09-02 14:30
I talked with Mark offline, and he was able to resolve the problem.  I'll try to write-up the issue here in case others run into the same issue.

The application registers the `JacksonJsonProvider` to handle the serialization and de-serialization of Java objects to JSON for the HTTP entity.  The application also uses the `org.json.JSONObject` APIs (JSON4J) in the `ContainerRequestFilter` - in the case where a client error is detected in the filter, it calls the `abortWith` method to send an error response back to the client with information necessary to resolve the error.  This information is placed in the `JSONObject` that is passed to the `Response` object to be sent to the client.  The JAX-RS implementation then searches for a `MessageBodyWriter` to serialize the entity in the `Response` - and it selects the `JacksonJsonProvider` because that MBW supports the media type of `application/json` and the `java.lang.Object` type. The Jackson provider then attempts to serialize the `JSONObject` not realizing that it is already effectively JSON - so it serializes it incorrectly.

There are a few different options for resolving this:
(1) Instead of using a `JSONObject` the filter could create some sort of Java object to represent the client error information, and just let Jackson serialize it like any other Java object.
(2) Switch over to using JSON-P (which is very similar to JSON4J) APIs since Open Liberty has a built-in JSON-P `MessageBodyWriter` that would be selected instead of Jackson's.
(3) Create (or maybe just package, if one exists...) a `MessageBodyWriter` that handles `org.json.JSONObject` types. This MBW would be selected over Jackson's, and would ensure proper serialization of the object to JSON.
(4) Call `JSONObject#toString(...)` - this will allow JAX-RS to select a MBW that handles `String` objects and will write the string directly to the HTTP entity.

Mark selected (4) and was able to get the results he was looking for.  I think any of these options would work - and all have some merit. Options (1) and (2) remove the dependency on the `org.json.*` APIs (so one less dependency to ship in the app). Option (3) requires no changes to existing code. (4) is certainly the simplest fix.

Thanks for opening the issue - glad that it is resolved - and hopefully this text will help somebody else in a similar situation.

**Closed as completed** 2021-09-02 14:30 UTC
Labels: bug, in:JAX-RS, team:Wendigo West, Needs member attention
