### ISSUE TITLE
Liberty 23.0.0.9 - 6% Performance Throughput Regression on MicroProfile 6 OpenAPI scenario

### ISSUE THREAD

**Issue by eramos2** [OpenLiberty/open-liberty#26023] opened 2023-08-22 16:07 UTC
**Describe the bug**  
There is a 6% throughput regression in the MicroProfile 6 OpenAPI benchmark, seen between Liberty builds `230820230807-0401` (23.0.0.8 GA) and `230920230820-1457`.
It seems to be related to  #25724 on `dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/ProxySupportUtil.java`. 
From the 23.0.0.9 profile`extractURL` is spending 7% more time under compared to the same call in 23008 profile.

**Steps to Reproduce**  
Measure throughput (req/sec) in `230820230807-0401` (23.0.0.8 GA) build
Measure throughput (req/sec) in`230920230820-1457` build
Compare the Difference in throughput between builds

**Diagnostic information:**  
OpenLiberty Version: 
`WebSphere Application Server 23.0.0.9 (wlp-1.0.81.cl230920230820-1457)`
Affected feature(s): 
`microProfile-6.0 (openapi)`
Java Version:
 `IBM Semeru Runtime Certified Edition (11.0.18+10)`

**Comment by eramos2** [comment] 2023-08-22 16:28
@abutch3r @Azquelt Could you take a look at this?

**Comment by Azquelt** [comment] 2023-08-22 16:37
Please add information about what the benchmark covers.

If it's just the time to serve the `/openapi` endpoint, I'm inclined to say this is not a big issue though we will take a look.

**Comment by Azquelt** [comment] 2023-08-22 16:42
Do you have more detail about what is taking the time within `extractURL`?

From the code changes I can see we're retrieving the bundle context and doing a service lookup which may be the slow part?

Other than that on the normal path we should just be testing some short strings which should not be slow.

If it is the service lookup, we should be able to use a service tracker to avoid doing the lookup on every request.

**Comment by eramos2** [comment] 2023-08-22 16:47
This is what I'm seeing on the 23.0.0.9 profile that is not in the 23.0.0.8 `OpenAPIEndpointProvider endpointProvider = bundleContext.getService(bundleContext.getServiceReference(OpenAPIEndpointProvider.class));`

**Comment by jdmcclur** [comment] 2023-08-22 16:54
This test hits the /openapi endpoint repeatedly. It's not a super important test, I've considered dropping it, but do want to catch any major regressions.

**Comment by Azquelt** [comment] 2023-08-22 17:07
We can try using a service tracker instead and see if that improves the performance.

@abutch3r May be easier to have the tracker in the servlet which already has lifecycle callbacks to set it up and close it and pass it through to the proxy support method.

**Comment by jhanders34** [comment] 2023-08-22 17:15
Unless you can use an activator to save off the bundleContext during activation and not need to look this up on every request.

**Comment by jhanders34** [comment] 2023-09-05 14:22
Since this wasn't fixed before the release that it was introduced, marking this as a #regression `release bug`.

**Closed as completed** 2023-09-05 14:27 UTC
Labels: in:MicroProfile/OpenAPI, regression, release bug, performance, release:230010
