### ISSUE TITLE
Test Failure: com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8340] opened 2019-07-24 13:56 UTC
RTC 263632

```
launchTck:junit.framework.AssertionFailedError: 2019-05-30-18:31:16:996 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs.
ResultsDir: /WebSphere/Misc/jazz_build/jbe_zrock083/jazz/buildsystem/buildengine/eclipse/build/dev/com.ibm.ws.microprofile.metrics_fat_tck/autoFVT/results/tck_tck-suite/surefire-reports
at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:178)
at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:446)
at componenttest.topology.utils.MvnUtils.runCleanTest(MvnUtils.java:599)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:139)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:121)
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck(MetricsTCKLauncher.java:60)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by lamkavan** [comment] 2019-08-01 15:36
This work item has been marked as a duplicate of work item 261073

**Closed by lamkavan** 2019-08-01 15:36 UTC
Labels: team:Lumberjack
