### ISSUE TITLE
Deliver Eclipselink 2.7.3

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#1682] opened 2018-01-18 21:28 UTC
Deliver Eclipselink 2.7.2 to Open Liberty once it is published to Maven Central.

**Comment by dazey3** [comment] 2018-08-27 21:12
Duplicate of https://github.com/OpenLiberty/open-liberty/issues/4587

**Closed by dazey3** 2018-08-27 21:12 UTC
Labels: in:JPA, priority/medium, team:Blizzard
